### ISSUE TITLE
Skip creating groups if exist

### ISSUE THREAD

**Issue by Piknik1990** [python-gitlab/python-gitlab#1090]
## Description of the problem, including code/CLI snippet
Hello! 
I'd like to create some a GitLab's group via the "python-gitlab" module and it's work but for first time only. In the next times I get a "already exist" error. 

My code:
```
subgroupcreate = connectdist.groups.create({'name': fullpathdistgroup[-1], 'path': fullpathdistgroup[-1], 'visibility': 'private', 'parent_id': subgroupcreateparent.id})
subgroupcreate.save()
```
Do you have any tools for ignore this case? Or another way?

If I found a some option for ignoring this case - it's will be very good

For example:
```
subgroupcreate = connectdist.groups.create({'name': fullpathdistgroup[-1], 'path': fullpathdistgroup[-1], 'visibility': 'private', 'parent_id': subgroupcreateparent.id})
subgroupcreate.save('skip_exist': True)
```

## Expected Behavior
```
{:path=>["has already been taken. Skipping"]}
```

## Actual Behavior
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/gitlab/exceptions.py", line 251, in wrapped_f
    return f(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/gitlab/mixins.py", line 204, in create
    **kwargs)
  File "/usr/lib/python3.7/site-packages/gitlab/__init__.py", line 604, in http_post
    post_data=post_data, files=files, **kwargs)
  File "/usr/lib/python3.7/site-packages/gitlab/__init__.py", line 510, in http_request
    response_body=result.content)
gitlab.exceptions.GitlabHttpError: 400: Failed to save group {:path=>["has already been taken"]}
```

## Specifications

  - python-gitlab version:
  - API version you are using (v3/v4):
  - Gitlab server version (or gitlab.com):

**Comment by max-wittig** [comment]
You might want to read python handling of exceptions: https://docs.python.org/3/tutorial/errors.html
