### ISSUE TITLE
ProjetcLabel object are not JSON serializable

### ISSUE THREAD

**Issue by MatthieuPERIN** [python-gitlab/python-gitlab#1116]
## Description of the problem, including code/CLI snippet

Idea is to use Gitlab-Python to manage Labels in numerous project in a more scallable way 😅 

MWE
```python
# setup gl-py
gl = gitlab.Gitlab(GITLAB_ADRESS, private_token=TOKEN, ssl_verify=False)
gl.auth()

#get the project
src_prj = gl.projects.get(SRC_PRJ_ID)

# try to serialize the first Label Project
with open('data.txt', 'w') as outfile:
    json.dump(src_prj.labels.list(all=True)[0], outfile)

```

Get the following 
```python
Traceback (most recent call last):
  File "C:/Users/MPERIN/Git/labelautomation/labelmodel.py", line 79, in <module>
    json.dump(src_prj.labels.list(all=True)[0], outfile)
  File "C:\Users\MPERIN\AppData\Local\Continuum\miniconda3\envs\labelautomation\lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\MPERIN\AppData\Local\Continuum\miniconda3\envs\labelautomation\lib\json\encoder.py", line 438, in _iterencode
    o = _default(o)
  File "C:\Users\MPERIN\AppData\Local\Continuum\miniconda3\envs\labelautomation\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ProjectLabel is not JSON serializable
```

## Expected Behavior
The Gilabl-python object are well serialized into JSON

## Actual Behavior
The serialization crashes 😒 

## Specifications

  - python-gitlab version: 2.2 (pip)
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 11.10.0

**Comment by max-wittig** [comment]
You can always request the `.attributes` of an objects. That should be json serializable, but I guess it would make sense for all projects to be serializable.

Btw. your GitLab version is not supported by python-gitlab and it's dangerous to use. No security whatsoever, all vulnerabilities of it are public. You should upgrade to 13.0.0

**Comment by MatthieuPERIN** [comment]
@max-wittig Thanks for the solution on `.attributes` and yes a "builtin" solution would be nicer

Agree for the GitLab version but this is a corporate internal-only use forge pending upgrade to 13.X pending (long-due) hardware migration (always the same music it seems).

**Comment by max-wittig** [comment]
@MatthieuPERIN Maybe you should raise some security concerns and include this page with all vulnabilities 😄  https://hackerone.com/gitlab/hacktivity

**Comment by JohnVillalovos** [comment]
I have proposed https://github.com/python-gitlab/python-gitlab/pull/1872 that would allow you to serialize the objects.
