### ISSUE TITLE
Get notes from Epics - GET /groups/:id/epics/:epic_id/notes

### ISSUE THREAD

**Issue by danyfdz92** [python-gitlab/python-gitlab#1142]
## Description of the problem, including code/CLI snippet

It is not possible to get epics notes. I would like to be able to call the GET /groups/:id/epics/:epic_id/notes, described as in the official documentation:
https://docs.gitlab.com/ce/api/notes.html#list-all-epic-notes

## Expected Behavior
List all epic notes

epics.notes.list() -> return epic_notes

## Actual Behavior
epics.notes.list()
AttributeError: notes

## Specifications

  - python-gitlab version: 1.0.2
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 13.1.3

**Comment by iloving** [comment]
Are there any plans on implementing this?  Not being able to manage notes in epics is a pain.

**Comment by nejch** [comment]
Hi @iloving, this is an EE feature so it had a little less priority as most of us don't have access to that, but the epic notes are similar to some other resource so should be quick. So just keep pinging here if there's no activity soon ;)

**Comment by iloving** [comment]
It's now less urgent for me as I wrote my own quick and dirty API call to handle this particular task.

**Comment by johngun3** [comment]
Is this issue meant to be resolved? I see that [this commit ](https://github.com/python-gitlab/python-gitlab/commit/7f4edb53e9413f401c859701d8c3bac4a40706af) seems to have added support for epic notes.

However, when I try to get notes from an epic as mentioned in the docs, I get a stack trace like below. I'm using version `3.6.0`.
```
>>> epic.notes.list()
Traceback (most recent call last):
  File "/opt/miniconda/envs/platform/lib/python3.8/site-packages/gitlab/base.py", line 105, in __getattr__
    return self.__dict__["_updated_attrs"][name]
KeyError: 'notes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda/envs/platform/lib/python3.8/site-packages/gitlab/base.py", line 108, in __getattr__
    value = self.__dict__["_attrs"][name]
KeyError: 'notes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda/envs/platform/lib/python3.8/site-packages/gitlab/base.py", line 128, in __getattr__
    return self.__dict__["_parent_attrs"][name]
KeyError: 'notes'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/miniconda/envs/platform/lib/python3.8/site-packages/gitlab/base.py", line 144, in __getattr__
    raise AttributeError(message) from exc
AttributeError: 'GroupEpic' object has no attribute 'notes'
```
Not sure if this is a user error or not. Would love some feedback, thanks.

**Comment by JohnVillalovos** [comment]
> Is this issue meant to be resolved? I see that [this commit ](https://github.com/python-gitlab/python-gitlab/commit/7f4edb53e9413f401c859701d8c3bac4a40706af) seems to have added support for epic notes.
> 
> However, when I try to get notes from an epic as mentioned in the docs, I get a stack trace like below. I'm using version `3.6.0`.
> 
> Not sure if this is a user error or not. The epic in question has comments attached so I would expect there to be a notes object. Would love some feedback, thanks.

I think the feature was not fully implemented. In `gitlab/v4/objects/epics.py` `GroupEpic` looks like it needs a `notes` attribute which  would be a `GroupEpicNoteManager`.

Not 100% sure about that but just a very quick look.

If you would like to work on adding that with a PR, would be great 👍

**Comment by nejch** [comment]
Hehe - I guess we should really ask for tests even for EE features ;) thanks for the catch @johngun3 @JohnVillalovos!

**Comment by johngun3** [comment]
I made a super quick edit. https://github.com/python-gitlab/python-gitlab/pull/2154 If more is required I'll have to come back to this later.
