### ISSUE TITLE
Project creation and time to sync before reading ssh_to_url ?

### ISSUE THREAD

**Issue by nyue** [python-gitlab/python-gitlab#1193]
## Description of the problem, including code/CLI snippet
    group = gl.groups.create({'name': 'nicholasgroup', 'path': 'nicholasgroup'})
    if group:
        subgroup = gl.groups.create({'name': 'mysubgroup', 'path': 'mysubgroup'},parent_id=group.id)
        if subgroup:
            created_project = gl.projects.create({'name': 'myrepo', 'namespace_id': subgroup.id})
            print(created_project.id)
            time.sleep(5)
            project = gl.projects.get(created_project.id)
            print('ssh url = {}'.format(project.ssh_to_url))

## Actual Behavior

21183262
Traceback (most recent call last):
  File "/home/nyue/projects/ACI/gitlab-api_git/dev_venv/lib/python3.7/site-packages/gitlab/base.py", line 59, in __getattr__
    return self.__dict__["_updated_attrs"][name]
KeyError: 'ssh_to_url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nyue/projects/ACI/gitlab-api_git/dev_venv/lib/python3.7/site-packages/gitlab/base.py", line 62, in __getattr__
    value = self.__dict__["_attrs"][name]
KeyError: 'ssh_to_url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nyue/projects/ACI/gitlab-api_git/dev_venv/lib/python3.7/site-packages/gitlab/base.py", line 82, in __getattr__
    return self.__dict__["_parent_attrs"][name]
KeyError: 'ssh_to_url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "home/gitlab_tutorial.py", line 31, in <module>
    print('ssh url = {}'.format(project.ssh_to_url))
  File "/home/nyue/projects/ACI/gitlab-api_git/dev_venv/lib/python3.7/site-packages/gitlab/base.py", line 84, in __getattr__
    raise AttributeError(name)
AttributeError: ssh_to_url

## Specifications

  - python-gitlab version: 2.5.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): gitlab.com

**Comment by nyue** [comment]
My bad, I was reading the wrong field.
