### ISSUE TITLE
Project export fails with "AttributeError: exports"

### ISSUE THREAD

**Issue by Johny-faillab** [python-gitlab/python-gitlab#1262]
## Description of the problem, including code/CLI snippet

The project export as described in the documentation [here](https://python-gitlab.readthedocs.io/en/stable/gl_objects/projects.html) does not work. The following code results in a `AttributeError: exports` at the line: `export = p.exports.create({}) ` The same issue was already closed [here](https://github.com/python-gitlab/python-gitlab/issues/977)

## Expected Behavior

This code should initiated a project export and then download the resulting tar file.

## Code

```
#!/usr/bin/python3
import gitlab

gl = gitlab.Gitlab('https://gitlab.com', private_token='token')
groups = gl.projects.list()
group = gl.groups.get(group_id)
projects = group.projects.list(include_subgroups=True)
for each in projects:
    print("Exporting...")
    print(each.attributes['name'])
    # Create the export
    export = each.exports.create({})
    # Wait for the 'finished' status
    export.refresh()
    while export.export_status != 'finished':
        time.sleep(1)
        export.refresh()
    # Download the result
    with open('/tmp/export.tgz', 'wb') as f:
        export.download(streamed=True, action=f.write)
```

## Actual Behavior

**Error**:

```
Exporting...
<'project_name'>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gitlab/base.py", line 59, in __getattr__
    return self.__dict__["_updated_attrs"][name]
KeyError: 'exports'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gitlab/base.py", line 62, in __getattr__
    value = self.__dict__["_attrs"][name]
KeyError: 'exports'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gitlab/base.py", line 82, in __getattr__
    return self.__dict__["_parent_attrs"][name]
KeyError: 'exports'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/john/projects/gitlab-backup/main.py", line 12, in <module>
    export = each.exports.create({})
  File "/usr/local/lib/python3.8/dist-packages/gitlab/base.py", line 84, in __getattr__
    raise AttributeError(name)
AttributeError: exports
```

## Specifications

python-gitlab version: python-gitlab-2.5.0
API version you are using (v3/v4): v4
Gitlab server version (or gitlab.com): gitlab.com
Python version: 3.8.5
System: Ubuntu 20.04

**Comment by Johny-faillab** [comment]
Never mind. My code cased the issue.

This code works just fine:

```
!/usr/bin/python3

import gitlab
import time

gl = gitlab.Gitlab('https://gitlab.com', private_token='token')
groups = gl.projects.list()
group = gl.groups.get(group_id)
projects = group.projects.list(include_subgroups=True)
for each in projects:
    project_id = each.attributes['id']
    project_name = each.attributes['name']
    project_path = f"/tmp/{project_name}.tgz"
    # Create the export
    export = gl.projects.get(project_id).exports.create({})
    # Wait for the 'finished' status 
    export.refresh()
    while export.export_status != 'finished':
        time.sleep(1)
        export.refresh()
    # Download the result
    with open(project_path, 'wb') as f:
        export.download(streamed=True, action=f.write)
    # Print export successful  status
    print(project_name, 'was successfully exported')
```

**Comment by Johny-faillab** [comment]
Never mind. My code cased the issue.

This code works just fine:

```
!/usr/bin/python3

import gitlab
import time

gl = gitlab.Gitlab('https://gitlab.com', private_token='token')
groups = gl.projects.list()
group = gl.groups.get(group_id)
projects = group.projects.list(include_subgroups=True)
for each in projects:
    project_id = each.attributes['id']
    project_name = each.attributes['name']
    project_path = f"/tmp/{project_name}.tgz"
    # Create the export
    export = gl.projects.get(project_id).exports.create({})
    # Wait for the 'finished' status 
    export.refresh()
    while export.export_status != 'finished':
        time.sleep(1)
        export.refresh()
    # Download the result
    with open(project_path, 'wb') as f:
        export.download(streamed=True, action=f.write)
    # Print export successful  status
    print(project_name, 'was successfully exported')
```
