### ISSUE TITLE
404 when trying to Programatically Delete Snippets

### ISSUE THREAD

**Issue by jrieffel** [python-gitlab/python-gitlab#1291]
## Description of the problem, including code/CLI snippet
My server has been overrun by bot-generated accounts that have been spamming the public snippets.  I am trying to find a way to use python-gitlab to delete the snippets in question.  Code in question is below:

This is easy to do in the sense that the *only* snippets on our server are public.

I'm an admin on the machine.

Oddly I also get a 404 if I try to delete the snippet directly using a CURL command.

```
snippets = gl.snippets.public()#all=True)
print("num snipppets:", len(snippets))
for s in snippets:
    s.delete() 
```

## Expected Behavior

Snippets are removed

## Actual Behavior

```
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/gitlab/exceptions.py", line 267, in wrapped_f
    return f(*args, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/gitlab/mixins.py", line 331, in delete
    self.gitlab.http_delete(path, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/gitlab/__init__.py", line 736, in http_delete
    return self.http_request("delete", path, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/gitlab/__init__.py", line 568, in http_request
    response_body=result.content,
gitlab.exceptions.GitlabHttpError: 404: 404 Snippet Not Found
```
## Specifications

  - python-gitlab version: most recent stable version
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): (not sure how to find this out)

**Comment by jrieffel** [comment]
I've tried adding 

```
for s in snippets:
    #print(s)
    auth = s.author
    print(auth['name'])
    s.delete(sudo=auth['name'])
```

But still get a 404

**Comment by jrieffel** [comment]
Resolved:

- I just had to sudo

```
    auth = s.author
    authname = auth['username']
    s.delete(sudo=auth['username'])
```
