### ISSUE TITLE
why python-gitlab runs in a shell and in script not in the same environment?

### ISSUE THREAD

**Issue by unclesamwk** [python-gitlab/python-gitlab#1377]
## Description of the problem, including code/CLI snippet
I installed a new virtualenv with python3.8 and install python-gitlab.
The following script failed but in a python shell the same code works perfect.

Any idea?

## Expected Behavior
script
```
#!/usr/bin/env python3
import gitlab

gl = gitlab.Gitlab('https://gitlab.example.com', private_token='****')
```
script output
```
root@2e4b73341c64:/# python3 widgets/gitlab.py 
Traceback (most recent call last):
  File "widgets/gitlab.py", line 2, in <module>
    import gitlab
  File "/widgets/gitlab.py", line 4, in <module>
    gl = gitlab.Gitlab('https://gitlab.example.com', private_token='****')
AttributeError: partially initialized module 'gitlab' has no attribute 'Gitlab' (most likely due to a circular import)
```
shell output
```
root@2e4b73341c64:/# python3
Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gitlab
>>> gl = gitlab.Gitlab('https://gitlab.example.com', private_token='****')
>>> gl.auth()
```
## Specifications

  - python-gitlab version: 2.6.0
  - API version you are using (v3/v4): v4

**Comment by nejch** [comment]
Can you try to rename your `widgets/gitlab.py` to something else? I think you have a namespace clash with the library there.

**Comment by unclesamwk** [comment]
Thank you, it works. I am stupid ;-)
