### ISSUE TITLE
TypeError: quote_from_bytes() expected bytes when doing project.mergerequests.get

### ISSUE THREAD

**Issue by mjram0s** [python-gitlab/python-gitlab#1430]
## Description of the problem, including code/CLI snippet
Related to https://github.com/python-gitlab/python-gitlab/issues/1425. Upon updating to python-gitlab v2.7.1 we are encountering the following error:
```
Traceback (most recent call last):
File "/var/task/tagbotgitlab/tagbot.py", line 30, in handler
status, msg = 200, handle_event(json.loads(evt.get("body", "
{}
")))
File "/var/task/tagbotgitlab/tagbot.py", line 52, in handle_event
return handle_open(payload)
File "/var/task/tagbotgitlab/tagbot.py", line 67, in handle_open
mr = p.mergerequests.get(mr_id, lazy=True)
File "/var/task/gitlab/exceptions.py", line 287, in wrapped_f
return f(*args, **kwargs)
File "/var/task/gitlab/mixins.py", line 104, in get
id = utils.clean_str_id(id)
File "/var/task/gitlab/utils.py", line 60, in clean_str_id
return quote(id, safe="")
File "/var/lang/lib/python3.8/urllib/parse.py", line 850, in quote
return quote_from_bytes(string, safe)
File "/var/lang/lib/python3.8/urllib/parse.py", line 875, in quote_from_bytes
raise TypeError("quote_from_bytes() expected bytes")
TypeError: quote_from_bytes() expected bytes
STATUS : 500
ERROR : Runtime error
```

## Expected Behavior
p.mergerequests.get(mr_id, lazy=True) should return an MR instead of throwing an error

## Actual Behavior
TypeError: quote_from_bytes() expected bytes

## Specifications
python-gitlab version: 2.7.1
API version you are using (v3/v4): v4
Gitlab server version (or gitlab.com): 13.11.1-ee

**Comment by JohnVillalovos** [comment]
Do you know what the value of `mr_id` is in the `p.mergerequests.get(mr_id, lazy=True)` call?

**Comment by JohnVillalovos** [comment]
Also what is the output of`type(mr_id)`

Thanks

**Comment by JohnVillalovos** [comment]
Any chance `mr_id` is a `float`?

```
Python 3.8.9 (default, Apr  6 2021, 00:00:00)
[GCC 10.2.1 20201125 (Red Hat 10.2.1-9)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import urllib.parse
>>> mr_id = 2.0
>>> urllib.parse.quote(mr_id, safe="")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.8/urllib/parse.py", line 850, in quote
    return quote_from_bytes(string, safe)
  File "/usr/lib64/python3.8/urllib/parse.py", line 875, in quote_from_bytes
    raise TypeError("quote_from_bytes() expected bytes")
TypeError: quote_from_bytes() expected bytes
```

We are expecting either an `int` or `string` value.

**Comment by mjram0s** [comment]
Thanks for your help. It turns out this is an error on our side. We're getting an unexpected `mr_id = None`. I will close this issue now.

**Comment by JohnVillalovos** [comment]
No problem. I'm glad you figured it out!
