### ISSUE TITLE
Configuration helper to get password needs to prompt for my keyring's password

### ISSUE THREAD

**Issue by armellarcier** [python-gitlab/python-gitlab#1545]
## Description of the problem, including code/CLI snippet

This is my config file :

```
[global]
default = gitlab
ssl_verify = true
timeout = 5

[gitlab]
url = https://gitlab.com
private_token = helper: ~/showGitlabToken.sh
```

The `~/showGitlabToken.sh` runs a `keepassxc-cli` command to show the gitlab token.

This `keepassxc-cli` needs to prompt me for my password.

## Expected Behavior

When I run `gitlab ls` I get a prompt for my keyring password, then a result

## Actual Behavior

I get an error

```
Traceback (most recent call last):
  File "/home/MYUSERNAME/.local/bin/gitlab", line 8, in <module>
    sys.exit(main())
  File "/home/MYUSERNAME/.local/lib/python3.9/site-packages/gitlab/cli.py", line 204, in main
    config = gitlab.config.GitlabConfigParser(options.gitlab, options.config_file)
  File "/home/MYUSERNAME/.local/lib/python3.9/site-packages/gitlab/config.py", line 164, in __init__
    self._get_values_from_helper()
  File "/home/MYUSERNAME/.local/lib/python3.9/site-packages/gitlab/config.py", line 224, in _get_values_from_helper
    subprocess.check_output(commmand, stderr=subprocess.PIPE)
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/MYUSERNAME/showGitlabToken.sh'

```

## Specifications

  - python-gitlab version: 2.9.0
  - API version you are using (v3/v4):
  - Gitlab server version (or gitlab.com):

**Comment by JohnVillalovos** [comment]
This might work:

```
private_token = helper: bash ~/showGitlabToken.sh
```

**Comment by armellarcier** [comment]
Thanks, it does... something. It hangs instead of failing. I have no output though so I don't know whether it's listening to stdin. If I press enter 4 times, it does execute and I get a 404 error. I really don't know what I'm doing...

**Comment by JohnVillalovos** [comment]
Ah. Okay. The helper program must provide the credentials. It can not ask for input from my understanding. As the way it works is that `gitlab ls` is going to call the helper and try to get the output from it. So prompts such as asking for the password will be interpreted as the credentials.

More info here: https://python-gitlab.readthedocs.io/en/stable/cli-usage.html#credential-helpers

So I don't think it is going to work for for your use case, the way it is currently implemented 😟

**Comment by armellarcier** [comment]
Alright, I actually don't need the `bash` part. It works the same if the wrapper script starts with `#!/bin/sh`

I got a result by calling the gitlab command, then ENTER once, then my keyring's password (blindly cause there was no output) and then ENTER again.

I successfuly got a result. It's just really weird to not getting output

**Comment by JohnVillalovos** [comment]
Glad you got it working! But kind of of an ugly way needed to get it to work.
