### ISSUE TITLE
Dumb question - namespaces and modules: my code doesn't find Gitlab

### ISSUE THREAD

**Issue by larean** [python-gitlab/python-gitlab#1554]
## Description of the problem, including code/CLI snippet
Hello. Not very knowledgeable with namespaces in modules and submodules. The problem is that the very first example in your documentation doesn't work for me.

```python
import gitlab

gl = gitlab.Gitlab("https://www.gitlab.com")
```

I get the message:

```python
AttributeError: module 'gitlab' has no attribute 'Gitlab'
```

I research a bit and find that Gitlab is defined in client.py, so I do:

```python
import gitlab
import gitlab.client

gl = gitlab.client.Gitlab("https://www.gitlab.com")
```
OK, it works this time, but deeper in the code there are still calls to gitlab.Gitlab which do not work:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/arean/.local/lib/python3.6/site-packages/gitlab/client.py", line 107, in __init__
    import gitlab.v4.objects
  File "/home/arean/.local/lib/python3.6/site-packages/gitlab/v4/objects/__init__.py", line 18, in <module>
    from .access_requests import *
  File "/home/arean/.local/lib/python3.6/site-packages/gitlab/v4/objects/access_requests.py", line 2, in <module>
    from gitlab.mixins import (
  File "/home/arean/.local/lib/python3.6/site-packages/gitlab/mixins.py", line 74, in <module>
    class GetMixin(_RestManagerBase):
  File "/home/arean/.local/lib/python3.6/site-packages/gitlab/mixins.py", line 82, in GetMixin
    gitlab: gitlab.Gitlab
AttributeError: module 'gitlab' has no attribute 'Gitlab'
```

How do you arrange the namespace so it recognizes Gitlab just importing gitlab?

## Expected Behavior

No errors when I execute the first example; gitlab namespace expected to containg Gitlab

## Actual Behavior

Documented above. A dir(gitlab) with only the gitlab import gives this:

```python
    ['__doc__', '__loader__', '__name__', '__package__', '__path__', '__spec__']


## Specifications
  - Python: 3.6
  - python-gitlab version:
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): www,gitlab.com latest version

**Comment by JohnVillalovos** [comment]
What is your `python-gitlab` version?

For me I do this:
```
$ python
Python 3.9.6 (default, Jul 16 2021, 00:00:00)
[GCC 11.1.1 20210531 (Red Hat 11.1.1-3)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gitlab
>>> print(gitlab.__version__)
2.9.0
```

**Comment by JohnVillalovos** [comment]
As a note when I try it using Python 3.6

```
$ python3.6
Python 3.6.14 (default, Jun 29 2021, 00:00:00)
[GCC 11.1.1 20210531 (Red Hat 11.1.1-3)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gitlab
>>> print(gitlab.__version__)
2.9.0
>>> import pprint
>>> pprint.pprint(dir(gitlab))
['Any',
 'Callable',
 'DEVELOPER_ACCESS',
 'GUEST_ACCESS',
 'Gitlab',
 'GitlabActivateError',
 'GitlabAttachFileError',
 'GitlabAuthenticationError',
 'GitlabBlockError',
 'GitlabBuildCancelError',
 'GitlabBuildEraseError',
 'GitlabBuildPlayError',
 'GitlabBuildRetryError',
 'GitlabCancelError',
 'GitlabCherryPickError',
 'GitlabConnectionError',
 'GitlabCreateError',
 'GitlabDeactivateError',
 'GitlabDeleteError',
 'GitlabError',
 'GitlabFollowError',
 'GitlabGetError',
 'GitlabHousekeepingError',
 'GitlabHttpError',
 'GitlabImportError',
 'GitlabJobCancelError',
 'GitlabJobEraseError',
 'GitlabJobPlayError',
 'GitlabJobRetryError',
 'GitlabLicenseError',
 'GitlabList',
 'GitlabListError',
 'GitlabMRApprovalError',
 'GitlabMRClosedError',
 'GitlabMRForbiddenError',
 'GitlabMROnBuildSuccessError',
 'GitlabMRRebaseError',
 'GitlabMarkdownError',
 'GitlabOperationError',
 'GitlabOwnershipError',
 'GitlabParsingError',
 'GitlabPipelineCancelError',
 'GitlabPipelinePlayError',
 'GitlabPipelineRetryError',
 'GitlabProjectDeployKeyError',
 'GitlabProtectError',
 'GitlabRenderError',
 'GitlabRepairError',
 'GitlabRetryError',
 'GitlabRevertError',
 'GitlabSearchError',
 'GitlabSetError',
 'GitlabStopError',
 'GitlabSubscribeError',
 'GitlabTimeTrackingError',
 'GitlabTodoError',
 'GitlabTransferProjectError',
 'GitlabUnblockError',
 'GitlabUnfollowError',
 'GitlabUnsubscribeError',
 'GitlabUpdateError',
 'GitlabUploadError',
 'GitlabVerifyError',
 'MAINTAINER_ACCESS',
 'MASTER_ACCESS',
 'MINIMAL_ACCESS',
 'NOTIFICATION_LEVEL_CUSTOM',
 'NOTIFICATION_LEVEL_DISABLED',
 'NOTIFICATION_LEVEL_GLOBAL',
 'NOTIFICATION_LEVEL_MENTION',
 'NOTIFICATION_LEVEL_PARTICIPATING',
 'NOTIFICATION_LEVEL_WATCH',
 'NO_ACCESS',
 'OWNER_ACCESS',
 'Optional',
 'REPORTER_ACCESS',
 'RedirectError',
 'SEARCH_SCOPE_BLOBS',
 'SEARCH_SCOPE_COMMITS',
 'SEARCH_SCOPE_GLOBAL_SNIPPET_TITLES',
 'SEARCH_SCOPE_ISSUES',
 'SEARCH_SCOPE_MERGE_REQUESTS',
 'SEARCH_SCOPE_MILESTONES',
 'SEARCH_SCOPE_PROJECTS',
 'SEARCH_SCOPE_PROJECT_NOTES',
 'SEARCH_SCOPE_USERS',
 'SEARCH_SCOPE_WIKI_BLOBS',
 'TYPE_CHECKING',
 'Type',
 'TypeVar',
 'USER_AGENT',
 'Union',
 'VISIBILITY_INTERNAL',
 'VISIBILITY_PRIVATE',
 'VISIBILITY_PUBLIC',
 '__author__',
 '__builtins__',
 '__cached__',
 '__copyright__',
 '__doc__',
 '__email__',
 '__file__',
 '__license__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__title__',
 '__version__',
 'cast',
 'client',
 'config',
 'const',
 'exceptions',
 'functools',
 'gitlab',
 'on_http_error',
 'utils',
 'warnings']
```

**Comment by max-wittig** [comment]
Did you name some of your script to `gitlab.py` or something like that? That could collide

**Comment by larean** [comment]
What I did previously was install gitlab 1.0.2 (not python-gitlab). It worked fine for me but not for some users, especially Windows. I am running Ubuntu 18.04.5 LTS. Then I installed python-gitlab, which, it seems, has pretty much the same source files. I tried to uninstall gitlab several times, but I wonder if something is left on some cache.

I have a Windows environment too, which never let me install gitlab 1.0.2 (in fact, it was trying to solve this problem that I ran into the above issue). Now, when I install python-gitlab on Windows and I do a dir(gitlab), it DOES show all the names in John's message.

I am starting to suspect this is a pip problem. I will reinstall all the environment.

**Comment by larean** [comment]
OK, it seems to have been a conflict between both gitlabs. Uninstalling old gitlab with pip did not work. Physically removing its files did not work. I took a drastic step, uninstalled python 3.6 completely and reinstalled both python and pip. That worked. 

Still, I have five or six pre-production users and I would like to find a less draconian solution, if available, since my development environment has few modules, but this approach would severely impacto some environments.  Erase the Python cache? Install WITHOUT cache? There is an option in pip called "--no-cache-dir". Will let you know if it works.

**Comment by larean** [comment]
Update:

The problem seems to be that __init__.py was not installed, and possibly __version__.py. I am at a loss to understand why. I am positive this happened as I myself wrote an __init__.py to try to solve the problem.
