### ISSUE TITLE
AttributeError: module 'gitlab' has no attribute 'exceptions'

### ISSUE THREAD

**Issue by DaveSpe** [python-gitlab/python-gitlab#1573]
## Description of the problem, including code/CLI snippet
Code I am trying to execute:

```
  - name: Delete Gitlab Project
    community.general.gitlab_project:
      api_url: "https://gitlab.{{ org }}"
      api_token: "{{ vault_kv2.aro_ansible_token }}"
      group: "{{ git_group  }}"
      validate_certs: False
      name: "{{ git_repo_name }}"
      state: absent
    delegate_to: localhost
```

Error I am getting when I try: 

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: module 'gitlab' has no attribute 'exceptions'
fatal: [localhost -> localhost]: FAILED! => changed=false
  module_stderr: |-
    Traceback (most recent call last):
      File "/tmp/ansible_community.general.gitlab_project_payload_prpum4l8/ansible_community.general.gitlab_project_payload.zip/ansible_collections/community/general/plugins/module_utils/gitlab.py", line 93, in gitlabAuthentication
    AttributeError: module 'gitlab' has no attribute '__version__'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/ossunix/.ansible/tmp/ansible-tmp-1629392508.6360693-13440-121342390527051/AnsiballZ_gitlab_project.py", line 100, in <module>
        _ansiballz_main()
      File "/home/ossunix/.ansible/tmp/ansible-tmp-1629392508.6360693-13440-121342390527051/AnsiballZ_gitlab_project.py", line 92, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/home/ossunix/.ansible/tmp/ansible-tmp-1629392508.6360693-13440-121342390527051/AnsiballZ_gitlab_project.py", line 40, in invoke_module
        runpy.run_module(mod_name='ansible_collections.community.general.plugins.modules.gitlab_project', init_globals=dict(_module_fqn='ansible_collections.community.general.plugins.modules.gitlab_project', _modlib_path=modlib_path),
      File "/opt/rh/rh-python38/root/usr/lib64/python3.8/runpy.py", line 207, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/opt/rh/rh-python38/root/usr/lib64/python3.8/runpy.py", line 97, in _run_module_code
        _run_code(code, mod_globals, init_globals,
      File "/opt/rh/rh-python38/root/usr/lib64/python3.8/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_community.general.gitlab_project_payload_prpum4l8/ansible_community.general.gitlab_project_payload.zip/ansible_collections/community/general/plugins/modules/gitlab_project.py", line 476, in <module>
      File "/tmp/ansible_community.general.gitlab_project_payload_prpum4l8/ansible_community.general.gitlab_project_payload.zip/ansible_collections/community/general/plugins/modules/gitlab_project.py", line 409, in main
      File "/tmp/ansible_community.general.gitlab_project_payload_prpum4l8/ansible_community.general.gitlab_project_payload.zip/ansible_collections/community/general/plugins/module_utils/gitlab.py", line 100, in gitlabAuthentication
    AttributeError: module 'gitlab' has no attribute 'exceptions'
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
```

## Expected Behavior
Code block will delete gitlab repo

## Actual Behavior
Above exception

## Specifications

  - python-gitlab version: 
```
python-gitlab in /opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages (2.10.0)
requests-toolbelt>=0.9.1 in /opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages (from python-gitlab) (0.9.1)
requests>=2.22.0 in /home/ossunix/.local/lib/python3.8/site-packages (from python-gitlab) (2.25.1)
chardet<5,>=3.0.2 in /home/ossunix/.local/lib/python3.8/site-packages (from requests>=2.22.0->python-gitlab) (4.0.0)
certifi>=2017.4.17 in /home/ossunix/.local/lib/python3.8/site-packages (from requests>=2.22.0->python-gitlab) (2020.12.5)
urllib3<1.27,>=1.21.1 in /home/ossunix/.local/lib/python3.8/site-packages (from requests>=2.22.0->python-gitlab) (1.26.5)
idna<3,>=2.5 in /home/ossunix/.local/lib/python3.8/site-packages (from requests>=2.22.0->python-gitlab) (2.10)

```
  - API version you are using (v3/v4):  4?
  - Gitlab server version (or gitlab.com): GitLab Community Edition 13.11.4

**Comment by JohnVillalovos** [comment]
I'm sorry. But can you provide a smaller reproducer.

My theory is that this is an issue with the Ansible package:
https://github.com/ansible-collections/community.general/blob/6ac410b3f617074bb7af86050d8adfa4d495a3e6/plugins/module_utils/gitlab.py

I think first file an issue with them about it.
https://github.com/ansible-collections/community.general/issues

**Comment by DaveSpe** [comment]
Will do, thank you for the link.

**Comment by DaveSpe** [comment]
Closing for now raising issue with ansible-collections community.
