### ISSUE TITLE
gitlab.exceptions.GitlabHttpError: 404: 404 Not Found

### ISSUE THREAD

**Issue by IlyaNakhaichuk** [python-gitlab/python-gitlab#1574]
## Description of the problem, including code/CLI snippet
I’m trying to put release notes to the tag, after the release, but after updating to version GITLAB 14, I get this error? What additional steps do I need to do to work around this issue?
`
changelog_libs.project.tags.get(release_tag_name).set_release_description("".join(new_changelog))`

```
https://gitlab.io/api/v4/projects/number/repository/tags/TAG
<Response [200]>
<PreparedRequest [POST]>
https://gitlab.io/api/v4/projects/number/repository/tags/TAG/release
<Response [404]>
Traceback (most recent call last):
  File "/Users/xxx/PycharmProjects/venv/lib/python3.7/site-packages/gitlab/v4/objects/tags.py", line 40, in set_release_description
    path, post_data=data, **kwargs
  File "/Users/xxx/PycharmProjects/venv/lib/python3.7/site-packages/gitlab/client.py", line 767, in http_post
    **kwargs,
  File "/Users/xxx/PycharmProjects/venv/lib/python3.7/site-packages/gitlab/client.py", line 633, in http_request
    response_body=result.content,
gitlab.exceptions.GitlabHttpError: 404: 404 Not Found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "xxx/changelog_generator.py", line 226, in <module>
    generate_changelog(args.project, slack_channel, args.environment, args.download_url)
  File "txxx/changelog_generator.py", line 142, in generate_changelog
    git_release_tag_name)
  File "txxxchangelog_generator.py", line 208, in generate_release_notes
    changelog_libs.project.tags.get(release_tag_name).set_release_description("".join(new_changelog))
  File "/Users/xxx/PycharmProjects/venv/lib/python3.7/site-packages/gitlab/cli.py", line 61, in wrapped_f
    return f(*args, **kwargs)
  File "/Users/xxx/PycharmProjects/venv/lib/python3.7/site-packages/gitlab/v4/objects/tags.py", line 43, in set_release_description
    raise exc.GitlabCreateError(e.response_code, e.error_message) from e
gitlab.exceptions.GitlabCreateError: 404 Not Found: 404
```

**Comment by nejch** [comment]
GitLab deprecated creating release notes via the tags API a long time ago. They completely removed it in 14.0. Please use the Releases API instead to create releases. https://python-gitlab.readthedocs.io/en/master/gl_objects/releases.html
