### ISSUE TITLE
With package_file object, I can't call delete method on it

### ISSUE THREAD

**Issue by simonisateur** [python-gitlab/python-gitlab#1731]
## Description of the problem, including code/CLI snippet
With package_file object, I can't call delete on it. I need the package object to do so.

```python
# expected
package_file.delete()

# working
package.delete(package_file.id)
```

## Expected Behavior
The package file is deleted

## Actual Behavior
```
Traceback (most recent call last):
  File "/home/manjaro/.cache/pypoetry/virtualenvs/delete-old-packages-jUJPup_k-py3.10/lib/python3.10/site-packages/gitlab/base.py", line 85, in __getattr__
    return self.__dict__["_updated_attrs"][name]
KeyError: 'delete'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/manjaro/.cache/pypoetry/virtualenvs/delete-old-packages-jUJPup_k-py3.10/lib/python3.10/site-packages/gitlab/base.py", line 88, in __getattr__
    value = self.__dict__["_attrs"][name]
KeyError: 'delete'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/manjaro/.cache/pypoetry/virtualenvs/delete-old-packages-jUJPup_k-py3.10/lib/python3.10/site-packages/gitlab/base.py", line 108, in __getattr__
    return self.__dict__["_parent_attrs"][name]
KeyError: 'delete'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/manjaro/.pyenv/versions/3.10.0/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/manjaro/.pyenv/versions/3.10.0/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/manjaro/IdeaProjects/delete-old-packages/paclab/__main__.py", line 9, in <module>
    main()
  File "/home/manjaro/IdeaProjects/delete-old-packages/paclab/__main__.py", line 5, in main
    paclab.main()
  File "/home/manjaro/IdeaProjects/delete-old-packages/paclab/__init__.py", line 28, in main
    args.func(args)
  File "/home/manjaro/IdeaProjects/delete-old-packages/paclab/ui/cli/launcher.py", line 47, in __call__
    dt_pkg[1].delete()
  File "/home/manjaro/.cache/pypoetry/virtualenvs/delete-old-packages-jUJPup_k-py3.10/lib/python3.10/site-packages/gitlab/base.py", line 110, in __getattr__
    raise AttributeError(name)
AttributeError: delete

Process finished with exit code 1
```

## Specifications

  - python-gitlab version: 2.10.1
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 13.12.12-ee

**Comment by simonisateur** [comment]
Thank you @JohnVillalovos for the quick answer.

To fix it, I added ObjectDeleteMixin to ProjectPackageFile and added DeleteMixin to ProjectPackageFileManager.

The main branch already got DeleteMixin, the only change necessary was ObjectDeleteMixin as suggested.

I will create the merge request.

**Comment by simonisateur** [comment]
#1733 simonisateur:fix-package-file-delete
