### ISSUE TITLE
🐛  UNAUTHORIZED ACCESS 401

### ISSUE THREAD

**Issue by tonnyhideyori** [python-gitlab/python-gitlab#1767]
## Description of the problem, including code/CLI snippet
```
class GitlabProjects(object):
    def __init__(self):
        self.url=Config.load('gitlab')['url']
        self.gl=gitlab.Gitlab(self.url,job_token=os.environ.get('GITLAB_TOKEN')) 

    def list_projects(self):
        project=self.gl.projects.list()[0]
        repo=project.members.list()[0]
        print(repo)

```
## Expected Behavior
It should return the repo

## Actual Behavior
gitlab.exceptions.GitlabAuthenticationError: 401: 401 Unauthorized
```
Traceback (most recent call last):
  File "main.py", line 105, in <module>
    main()
  File "xxx.local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "xxx.local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "xxx.local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "xxx.local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "xxx.local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "main.py", line 101, in gitauto
    GA.list_projects()
  File "xxxDesktop/ddautomation/automation/gitautomation.py", line 13, in list_projects
    repo=project.members.list()[0]
  File "xxx.local/lib/python3.8/site-packages/gitlab/exceptions.py", line 304, in wrapped_f
    return f(*args, **kwargs)
  File "xxx.local/lib/python3.8/site-packages/gitlab/mixins.py", line 242, in list
    obj = self.gitlab.http_list(path, **data)
  File "xxx.local/lib/python3.8/site-packages/gitlab/client.py", line 722, in http_list
    return list(GitlabList(self, url, query_data, get_next=False, **kwargs))
  File "xxx.local/lib/python3.8/site-packages/gitlab/client.py", line 881, in __init__
    self._query(url, query_data, **self._kwargs)
  File "xxx.local/lib/python3.8/site-packages/gitlab/client.py", line 891, in _query
    result = self._gl.http_request("get", url, query_data=query_data, **kwargs)
  File "xxx.local/lib/python3.8/site-packages/gitlab/client.py", line 622, in http_request
    raise gitlab.exceptions.GitlabAuthenticationError(
gitlab.exceptions.GitlabAuthenticationError: 401: 401 Unauthorized

```
## Specifications

  - python-gitlab version:2.10.1
  - API version you are using (v3/v4):v4
  - Gitlab server version (or gitlab.com):  14.4.4-ee

**Comment by JohnVillalovos** [comment]
I would think that either your URL and/or token is wrong.

I doubt it is an issue with `python-gitlab` as we test that path.

**Comment by tonnyhideyori** [comment]
But project.name gives the name of the project.

**Comment by JohnVillalovos** [comment]
Does it make any difference if you do `self.gl.auth()` after you create `self.gl`?

**Comment by lgatellier** [comment]
Hi,
Is your GITLAB_TOKEN really a job_token (like CI_JOB_TOKEN provided by Gitlab CI, or is it another token, like Project Access Token, ou Personal Access Token ?

Did you try with `private_token` argument instead of `job_token` ?

**Comment by nejch** [comment]
As mentioned above, `job_token` is very limited and probably won't work with these endpoints. This should do the trick:

```diff
class GitlabProjects(object):
-        self.gl=gitlab.Gitlab(self.url,job_token=os.environ.get('GITLAB_TOKEN')) 
+        self.gl=gitlab.Gitlab(self.url, private_token=os.environ.get('GITLAB_TOKEN')) 
```

This limitation is mentioned in the intro for API usage.
https://python-gitlab.readthedocs.io/en/latest/api-usage.html
