### ISSUE TITLE
GitLab's API returns 403 error

### ISSUE THREAD

**Issue by IllanRULDACUNHA** [python-gitlab/python-gitlab#1920]
## Description of the problem, including code/CLI snippet

I try with gitlab Python library to find all scheduled pipelines on my GitLab (to loop over all projects and find the scheduled pipelines of all these projects).

```
 for project in all_projects:
     project_ids.append((project.path_with_namespace, project.id))
     for pipeline in project.pipelineschedules.list():
         scheds.append((pipeline.id, pipeline.cron))
         print(scheds)
```

## Expected Behavior

All scheduled pipelines listed with their ID and cron schedule.

## Actual Behavior

I get 2-3 scheduled pipelines and then the GitLab's API returns 403 Forbidden.

> [(219, '0 */4 * * *'), (218, '0 */4 * * *')]
> [(219, '0 */4 * * *'), (218, '0 */4 * * *'), (216, '0 */4 * * *')]
> File "C:\Program64\Python\Python\lib\site-packages\gitlab\exceptions.py", line 311, in wrapped_f
>     return f(*args, **kwargs)
> [...]
> File "C:\Program64\Python\Python\lib\site-packages\gitlab\client.py", line 727, in http_request
>     raise gitlab.exceptions.GitlabHttpError(
> gitlab.exceptions.GitlabHttpError: 403: 403 Forbidden

## Specifications

  - python-gitlab version: 3.2.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 12.7.5

**Comment by JohnVillalovos** [comment]
Maybe you don't have access to one of the projects? Add more print statements to narrow down where the code is.

Print when a statement when finished printing the schedule. Print the project ID at the start.

I don't believe this is a bug in `python-gitlab`

**Comment by IllanRULDACUNHA** [comment]
Hello,

I have access to all projects, as I'm admin of the GitLab.

I added a print of the project ID and a print at the end of the printing of the scheds.

[16611, 16610, 16609, 16608, 16607, 16606, 16605, 16604, 16603, 16602, 16601, 16600, 16598, 16597, 16596, 16595, 16594, 16593, 16592, 16591, 16590, 16589, 16588, 16587, 16585, 16584, 16583, 16582, 16581, 16580, 16579, 16578, 16577, 16576, 16575, 16574, 16573, 16572, 16571, 16570, 16569, 16568, 16567, 16566, 16565, 16564, 16563, 16562, 16561, 16555, 16553, 16552, 16551, 16549, 16548, 16547, 16546, 16545, 16544, 16543, 16542, 16541, 16540, 16538, 16537, 16536, 16535, 16534, 16533, 16532, 16531, 16530, 16529, 16528, 16527, 16526, 16525, 16524, 16523, 16521, 16519, 16516, 16515, 16514, 16513, 16512, 16511, 16510, 16507, 16506, 16505, 16504, 16503, 16502, 16501, 16500, 16499, 16498, 16497, 16496, 16495, 16494, 16493, 16492, 16491, 16490, 16489, 16487, 16486, 16485, 16484, 16483, 16482, 16481, 16480, 16479, 16478, 16477, 16476, 16475, 16474, 16472, 16471, 16470, 16469, 16468, 16467, 16466, 16465, 16464, 16463, 16462, 16461, 16460, 16459, 16458, 16457, 16456, 16455, 16454, 16453, 16452, 16451, 16450, 16449, 16448, 16446, 16445, 16444, 16442, 16441, 16440, 16439, 16437, 16436, 16434, 16430, 16428, 16427, 16426, 16425, 16424, 16423, 16422, 16421, 16420, 16419, 16418, 16417, 16416, 16415, 16414, 16413, 16412, 16411, 16409, 16408, 16407, 16406, 16405, 16404, 16403, 16402, 16401, 16400, 16399, 16398, 16397, 16396, 16395, 16394, 16393, 16392, 16391, 16390, 16389, 16388, 16387, 16386, 16385, 16384, 16383, 16382, 16381, 16380, 16379, 16378, 16377, 16376, 16375, 16374, 16373, 16372, 16369]
Traceback (most recent call last):
  File "C:\Program64\Python\Python\lib\site-packages\gitlab\exceptions.py", line 311, in wrapped_f
    return f(*args, **kwargs)
  File "C:\Program64\Python\Python\lib\site-packages\gitlab\mixins.py", line 241, in list
    obj = self.gitlab.http_list(path, **data)
  File "C:\Program64\Python\Python\lib\site-packages\gitlab\client.py", line 821, in http_list
    return list(GitlabList(self, url, query_data, get_next=False, **kwargs))
  File "C:\Program64\Python\Python\lib\site-packages\gitlab\client.py", line 980, in __init__
    self._query(url, query_data, **self._kwargs)
  File "C:\Program64\Python\Python\lib\site-packages\gitlab\client.py", line 990, in _query
    result = self._gl.http_request("get", url, query_data=query_data, **kwargs)
  File "C:\Program64\Python\Python\lib\site-packages\gitlab\client.py", line 727, in http_request
    raise gitlab.exceptions.GitlabHttpError(
gitlab.exceptions.GitlabHttpError: 403: 403 Forbidden

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\ut2nyp\Downloads\list_scheduled_pipelines.py", line 24, in <module>
    for pipeline in project.pipelineschedules.list():
  File "C:\Program64\Python\Python\lib\site-packages\gitlab\exceptions.py", line 313, in wrapped_f
    raise error(e.error_message, e.response_code, e.response_body) from e
gitlab.exceptions.GitlabListError: 403: 403 Forbidden

I see that not all project ID are printed, as my GitLab has 9 831 projects.

**Comment by JohnVillalovos** [comment]
> Hello,
> 
> I have access to all projects, as I'm admin of the GitLab.
> 
> I added a print of the project ID and a print at the end of the printing of the scheds.
> 
> > [16611, 16610, 16609, 16608, 16607, <snip>, 16372, 16369]

I don't understand what is being printed. I just see a list with a lot of numbers.

As a note your GitLab version is quite old (it was released over two years ago). The issue is maybe a bug in that version?

I will re-state that I don't think this is a `python-gitlab` issue.

> I see that not all project ID are printed, as my GitLab has 9 831 projects.

Please see: https://python-gitlab.readthedocs.io/en/stable/api-usage.html#pagination

I would recommend using `.list(as_list=False)` to get all entries.

**Comment by IllanRULDACUNHA** [comment]
> > Hello,
> > I have access to all projects, as I'm admin of the GitLab.
> > I added a print of the project ID and a print at the end of the printing of the scheds.
> > > [16611, 16610, 16609, 16608, 16607, , 16372, 16369]
> 
> I don't understand what is being printed. I just see a list with a lot of numbers.

These are project IDs.

> As a note your GitLab version is quite old (it was released over two years ago). The issue is maybe a bug in that version?
> 
> I will re-state that I don't think this is a `python-gitlab` issue.

I don't understand why you keep saying that the issue is not caused by python-gitlab. My point is not to blame anyone, GitLab nor python-gitlab, it is just to make the script works for me. Don't worry. ;)

> > I see that not all project ID are printed, as my GitLab has 9 831 projects.
> 
> Please see: https://python-gitlab.readthedocs.io/en/stable/api-usage.html#pagination
> 
> I would recommend using `.list(as_list=False)` to get all entries.

OK, I will try with this. So like this: ``all_projects = gl.projects.list(all=True, as_list=False)``?

**Comment by nejch** [comment]
> I don't understand why you keep saying that the issue is not caused by python-gitlab. My point is not to blame anyone, GitLab nor python-gitlab, it is just to make the script works for me. Don't worry. ;)

I don't think John meant to be defensive here, we just get _a lot_ of reports that are actually GitLab API permission issues, not an issue with the library, hence the assumption :)

403 almost always means a permission issue. What token are you using there? The fact that you're getting 213 out of 9k projects when using list tells me that it's probably not an admin token, but your snippet doesn't actually show how you list the projects. Either `all=True` or `as_list=False` should be enough to iterate over all of the projects, yes. If you use `gl.enable_debug()` you will also get more verbose output of the actual requests, so this might help here.

**Comment by njoneill** [comment]
I'm running into the same thing with python-gitlab 2.10.1 and GitLab 14.10.5.  The problem appears to be with the GitLab REST API showing unexpected behavior if the project in question has the "Repository" project feature disabled.

With "Repository" disabled I get the following for a project that I own:
```
> curl -K curl.config "https://mydomain.foo/gitlab/api/v4/projects/61/pipeline_schedules"
{"message":"403 Forbidden"}
```
With "Repository" enabled I get something more reasonable:
```
curl -K curl.config "https://mydomain.foo/gitlab/api/v4/projects/61/pipeline_schedules"
[]
```
(The project does not have any scheduled pipelines, so the empty list is correct.)

**Comment by nejch** [comment]
@njoneill I think this is normal behavior and likely also explains OP's original issue: if you hit a project with either repository disabled or CI/CD disabled, the endpoints that require these features will either return 403 or 404 in some cases. In other cases, project endpoints might be missing certain attributes with these features disabled.

So this is just something you'll need to handle on the application side (e.g. skip `if not project.jobs_enabled`, this seems to be purely how the server responds, as your curl example also shows this is not a client-specific issue.
