### ISSUE TITLE
Get a single file from an artifact archive doesn't work

### ISSUE THREAD

**Issue by devtonhere** [python-gitlab/python-gitlab#2133]
## Description of the problem, including code/CLI snippet
Cannot download a single file from an artifact.

## Expected Behavior
`gitlab project-job artifact --project-id=11576 --id=44137462 --path=file/from/artifiact-archive.json` return the content of a single file from an artifact archive

## Actual Behavior
Without specifing a `--path` I get this error:

```
Traceback (most recent call last):
  File "/Users/repos/my-project/bottom-up/venv3/bin/gitlab", line 8, in <module>
    sys.exit(main())
  File "/Users/repos/my-project/bottom-up/venv3/lib/python3.9/site-packages/gitlab/cli.py", line 364, in main
    gitlab.v4.cli.run(
  File "/Users/repos/my-project/bottom-up/venv3/lib/python3.9/site-packages/gitlab/v4/cli.py", line 524, in run
    data = g_cli.run()
  File "/Users/repos/my-project/bottom-up/venv3/lib/python3.9/site-packages/gitlab/v4/cli.py", line 98, in run
    return self.do_custom()
  File "/Users/repos/my-project/bottom-up/venv3/lib/python3.9/site-packages/gitlab/v4/cli.py", line 119, in do_custom
    return getattr(class_instance, method_name)(**self.args)
  File "/Users/repos/my-project/bottom-up/venv3/lib/python3.9/site-packages/gitlab/cli.py", line 62, in wrapped_f
    return f(*args, **kwargs)
  File "/Users/repos/my-project/bottom-up/venv3/lib/python3.9/site-packages/gitlab/exceptions.py", line 330, in wrapped_f
    return f(*args, **kwargs)
TypeError: artifact() missing 1 required positional argument: 'path'
```

Or when specifing `--path` I get this:

`gitlab: error: unrecognized arguments: --path=sv-test-report/overview-features.html`

## Specifications

  - python-gitlab version: 3.6.0
  - API version you are using (v3/v4): 4
  - Gitlab server version (or gitlab.com): own GitLab instance with [15.0.3-ee](https://gitlab.com/gitlab-org/gitlab/-/tags/v15.0.3-ee)

**Comment by nejch** [comment]
This should be fixed when https://github.com/python-gitlab/python-gitlab/pull/1879/files is merged.

**Comment by nejch** [comment]
@devtonhere just realized we're already tracking this in https://github.com/python-gitlab/python-gitlab/issues/1926, please upvote/follow that issue. I'll work on this to try and have it in this month's release.
