### ISSUE TITLE
import gitlab failing under Python 2.7.13 on El Capitan 10.11.6

### ISSUE THREAD

**Issue by mainderay** [python-gitlab/python-gitlab#240]
Terminal session below. Showing a "pip list" command to verify that python-gitlab is installed and then starting python and importing gitlab to get an error.

```
raymond ~ $ pip2 list
appdirs (1.4.3)
asn1crypto (0.22.0)
cffi (1.9.1)
cryptography (1.8.1)
enum34 (1.1.6)
idna (2.5)
ipaddress (1.0.18)
Jinja2 (2.9.5)
MarkupSafe (1.0)
packaging (16.8)
paramiko (2.1.2)
pip (9.0.1)
pyasn1 (0.2.3)
pycparser (2.17)
pyparsing (2.2.0)
python-gitlab (0.19)
PyYAML (3.12)
requests (2.13.0)
setuptools (34.3.2)
six (1.10.0)
wheel (0.29.0)
raymond ~ $ python
Python 2.7.13 (default, Dec 17 2016, 23:03:43)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import gitlab
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/gitlab/__init__.py", line 28, in <module>
    import requests
  File "/usr/local/lib/python2.7/site-packages/requests/__init__.py", line 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/usr/local/lib/python2.7/site-packages/requests/packages/__init__.py", line 27, in <module>
    from . import urllib3
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 3, in <module>
    import logging
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 89, in <module>
    _startTime = time.time()
TypeError: 'module' object is not callable
>>>
```

**Comment by gpocentek** [comment]
From the trace the problem doesn't seem to come from python-gitlab, but from python or requests. Could you try to ``import requests`` in an interpreter?

**Comment by muddman** [comment]
python 2.7.13 on ubuntu 16.04:

$ pip freeze
appdirs==1.4.3
packaging==16.8
pyparsing==2.2.0
python-gitlab==0.19
requests==2.13.0
six==1.10.0

$ python
Python 2.7.13 (default, Feb  2 2017, 12:53:28) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import gitlab
/home/user/git/virt_env/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/home/user/git/virt_env/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "gitlab.py", line 8, in <module>
    for project_item in resp.json():
  File "/home/user/git/virt_env/lib/python2.7/site-packages/requests/models.py", line 866, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/user/.pyenv/versions/2.7.13/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/home/user/.pyenv/versions/2.7.13/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/user/.pyenv/versions/2.7.13/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
>>>

**Comment by gpocentek** [comment]
The ``gitlab.py`` file that is imported does not come from python-gitlab. Try to move/rename this file.

**Comment by gpocentek** [comment]
@muddman I'm closing this issue since I didn't hear from you in a while. Feel free to reopen if needed.
