### ISSUE TITLE
403 GitLabHttpError: "Checking your Browser" HTML returned rather than API output

### ISSUE THREAD

**Issue by tomaarsen** [python-gitlab/python-gitlab#2510]
## Description of the problem, including code/CLI snippet
Whenever I try to interact with the API, I receive a 403 `GitlabHttpError` with a HTTP page with "Checking your Browser". I was unable to find any documentation on this, nor any issues. If I'm using the API incorrectly, please let me know.

## Expected Behavior
I expect to be able to successfully call e.g. `.get(...)` or `.list()` on one of the Manager instances:
```python
>>> import gitlab
>>> gl = gitlab.Gitlab("https://gitlab.com/gitlab-com/content-sites/docsy-gitlab")
>>> gl.projects.list()
[...]
```

## Actual Behavior
```python
>>> import gitlab
>>> gl = gitlab.Gitlab("https://gitlab.com/gitlab-com/content-sites/docsy-gitlab")
>>> gl.projects.list()
Traceback (most recent call last):
  File "C:\Users\tom\.conda\envs\unstructured\lib\site-packages\gitlab\exceptions.py", line 337, in wrapped_f
    return f(*args, **kwargs)
  File "C:\Users\tom\.conda\envs\unstructured\lib\site-packages\gitlab\mixins.py", line 122, in get
    server_data = self.gitlab.http_get(path, **kwargs)
  File "C:\Users\tom\.conda\envs\unstructured\lib\site-packages\gitlab\client.py", line 830, in http_get
    result = self.http_request(
  File "C:\Users\tom\.conda\envs\unstructured\lib\site-packages\gitlab\client.py", line 796, in http_request
    raise gitlab.exceptions.GitlabHttpError(
gitlab.exceptions.GitlabHttpError: 403: <!DOCTYPE html>
...
```

<details><summary>Full Traceback</summary>

```
Traceback (most recent call last):
  File "C:\Users\tom\.conda\envs\unstructured\lib\site-packages\gitlab\exceptions.py", line 337, in wrapped_f
    return f(*args, **kwargs)
  File "C:\Users\tom\.conda\envs\unstructured\lib\site-packages\gitlab\mixins.py", line 246, in list
    obj = self.gitlab.http_list(path, **data)
  File "C:\Users\tom\.conda\envs\unstructured\lib\site-packages\gitlab\client.py", line 953, in http_list
    gl_list = GitlabList(self, url, query_data, get_next=False, **kwargs)
  File "C:\Users\tom\.conda\envs\unstructured\lib\site-packages\gitlab\client.py", line 1155, in __init__
    self._query(url, query_data, **self._kwargs)
  File "C:\Users\tom\.conda\envs\unstructured\lib\site-packages\gitlab\client.py", line 1165, in _query
    result = self._gl.http_request("get", url, query_data=query_data, **kwargs)
  File "C:\Users\tom\.conda\envs\unstructured\lib\site-packages\gitlab\client.py", line 796, in http_request
    raise gitlab.exceptions.GitlabHttpError(
gitlab.exceptions.GitlabHttpError: 403: <!DOCTYPE html>
<html>
<head>
  <meta content="width=device-width, initial-scale=1, maximum-scale=1" name="viewport">
  <title>Checking your Browser - GitLab</title>
  <style>body{align-items:center;color:#666;display:flex;flex-direction:column;font-family:Helvetica Neue,Helvetica,Arial,sans-serif;font-size:14px;justify-content:center;margin:auto;text-align:center}hr{border:0;border-bottom:1px solid #fff;border-top:1px solid #eee;margin:18px auto;max-width:800px}img{max-width:40vw}.container{margin:auto 20px}.cferror_details{list-style-type:none}.cf-error-details h1{color:#456;font-size:20px;font-weight:400;line-height:28px}</style>
<meta http-equiv="refresh" content="35">
</head>

<body>
  <h1>
    <img src="data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjE5MiIgdmlld0JveD0iMCAwIDI1IDI0IiBmaWxsPSJub25lIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciPgogIDxwYXRoIGQ9Im0yNC41MDcgOS41LS4wMzQtLjA5TDIxLjA4Mi41NjJhLjg5Ni44OTYgMCAwIDAtMS42OTQuMDkxbC0yLjI5IDcuMDFINy44MjVMNS41MzUuNjUzYS44OTguODk4IDAgMCAwLTEuNjk0LS4wOUwuNDUxIDkuNDExLjQxNiA5LjVhNi4yOTcgNi4yOTcgMCAwIDAgMi4wOSA3LjI3OGwuMDEyLjAxLjAzLjAyMiA1LjE2IDMuODY3IDIuNTYgMS45MzUgMS41NTQgMS4xNzZhMS4wNTEgMS4wNTEgMCAwIDAgMS4yNjggMGwxLjU1NS0xLjE3NiAyLjU2LTEuOTM1IDUuMTk3LTMuODkuMDE0LS4wMUE2LjI5NyA2LjI5NyAwIDAgMCAyNC41MDcgOS41WiIKICAgICAgICBmaWxsPSIjRTI0MzI5Ii8+CiAgPHBhdGggZD0ibTI0LjUwNyA5LjUtLjAzNC0uMDlhMTEuNDQgMTEuNDQgMCAwIDAtNC41NiAyLjA1MWwtNy40NDcgNS42MzIgNC43NDIgMy41ODQgNS4xOTctMy44OS4wMTQtLjAxQTYuMjk3IDYuMjk3IDAgMCAwIDI0LjUwNyA5LjVaIgogICAgICAgIGZpbGw9IiNGQzZEMjYiLz4KICA8cGF0aCBkPSJtNy43MDcgMjAuNjc3IDIuNTYgMS45MzUgMS41NTUgMS4xNzZhMS4wNTEgMS4wNTEgMCAwIDAgMS4yNjggMGwxLjU1NS0xLjE3NiAyLjU2LTEuOTM1LTQuNzQzLTMuNTg0LTQuNzU1IDMuNTg0WiIKICAgICAgICBmaWxsPSIjRkNBMzI2Ii8+CiAgPHBhdGggZD0iTTUuMDEgMTEuNDYxYTExLjQzIDExLjQzIDAgMCAwLTQuNTYtMi4wNUwuNDE2IDkuNWE2LjI5NyA2LjI5NyAwIDAgMCAyLjA5IDcuMjc4bC4wMTIuMDEuMDMuMDIyIDUuMTYgMy44NjcgNC43NDUtMy41ODQtNy40NDQtNS42MzJaIgogICAgICAgIGZpbGw9IiNGQzZEMjYiLz4KPC9zdmc+Cg==" alt="GitLab" /><br />
  </h1>
  <div class="container">
    <div class="cf-browser-verification cf-im-under-attack">
    <noscript>
        <h1 style="color:#bd2426;">Please turn JavaScript on and reload the page.</h1>
    </noscript>
    <div id="cf-content">
        <div id="cf-bubbles">
            <div class="bubbles"></div>
            <div class="bubbles"></div>
            <div class="bubbles"></div>
        </div>
        <h1>Checking your browser before accessing gitlab.com.</h1>
        <div id="no-cookie-warning" class="cookie-warning" style="display:none">
            <p style="color:#bd2426;">Please enable Cookies and reload the page</p>
        </div>
        <p>This process is automatic. Your browser will redirect to your requested content shortly.</p>
        <p id="cf-spinner-allow-5-secs">Please allow up to 5 seconds...</p>
        <p id="cf-spinner-redirecting" style="display:none">Redirecting...</p>
    </div>
    <form id="challenge-form" class="challenge-form" action="/users/sign_in?__cf_chl_f_tk=HXtYm_4ziDxcn2QOzIf1hRcbUwhx1Nq3DkBAp5O0R7c-1678119864-0-gaNycGzNCBA" method="POST" enctype="application/x-www-form-urlencoded">
        <input type="hidden" name="md" value="46NIaWXSUWZ1979PeJ3JhZ4.Jb7XLPFQuYMQscurr10-1678119864-0-AUUSHcj3pg4_7vLliy1Drk-fkrvm4zQztSDOeZKfkWf_N9w_v2UN4AHH8V17xJmc2d398tWRD0QzmBaeQ_fKA1mNGROKZogaDqI-dJ9I1C-ArOORh53A7haYLVvIvLyyLuoti5fWoQn_kHWFfEJos-xLbUFsQlspr5liw4RkYJEJmitCEhz3HO0FCiX4XjJ-NuYFzzJKGWpGqsnwzDJcQ_VZ46YnJQ1S3Oo3kovU7rTFXW6dM1vnHW7TkAKM1-E0-29Grn9yd29gOd17kZrLJMR33xNw72Yi5LA4RcQX2AK4j_OXcu3J7tsUKsE9H0EMt55ERaUN8ZfnQwT9kluK73SYiNXAfpLp-7uP51IDNw_B2JND_ya8Ih0NDHQ9kwjQd_6ycU2hUJNfpN6wO6uwUB8YNx4OZDu2TopTTLoqN5xG0dY6uKZt8OUyhW3WZ-cNbpwtgKBp2hgzqnYoL4o7oXsbmwLiJjiWzDW71PxifPcJQgtSAm3UntJhy00z3Q8R2sQUu0tILQ-nsgivahA3mHrPhzIBSY4p2Miu433TPCMSp3toPwHOBntBW3-4MeuTiyXg-CIhsRdr3KThoxF2f9cYmJB-H8ouZ3TQ82FfxQrfgelsxEx7YDlMcvzpaQWYYz_qUw2Jos_P1ua9hSecTTl0m-v9fbzyLgs4w57oO1KBeRJyU0I7eompfPqBNP-5tkYKM6rsju3s-cjeEbaX1jUknx61ATvm6GTPPpR4DTOSU548uaVoXAFMYQGm2PWxwnfD1TQWJEy22oi-zur3yXo25elwYhpe94KnDa0pmf4p5pPc6QLTeia7TiKlvhj4X1JxRzwbEzXy0vuLMGvlEEMbasqglbfIqkfs8Yf2SSf5ycpRBfStTy23FxX47HJ9I18mUoyl6m3qmyc0h9c4ylPteE15EFm1BD2yGEHUo0aS8rEf5v1kPSeobVuN0NgaNCdIvseVo6sLY4i1PBMjYQmGhwHRi9T8QAxbr1ycwE29mTuQGT8whXz3B5-2x6o5t4x8UJeGq2v4Euu4kfpRllfJ125X9gtoMQGwNbCdoc7J0ppW_5RhQXnfj85A3MrvNE-Jy9xq-IhQYccrM1l8ozvd6yllM1nzafsMFGgbVDRVnjh9DeCxzn_q1lyy7T4i-RhyzZKrxO6xjPm4GIHrvUQ9TNka9Tt5-5i8hGYp8lGy6rbY7ALRfNJZQVRTad2XP6WANnhMXMEBpPfSx33tT4bSdVz4nrCOFi9kI8aTkQN7Hxd4GB60dlpZ1cr-GSGIMVlB-G7XtBXlUd426EDogsh9J-NZsBYAUDN0P0Gmfi_S286CpPRD2uM0y7Q5i9mxnqnvp_cooO5p7OaqxkQJUNdK6ZUrLXCZyX1AN8p4c-a4jh3phDgk52jp-OvMXC_ev31Ve9KOftm1Vnfns-v-v9r5lFrJGYlusZnTcmlICQKrCOq075QIUZ0YUltC7TrEXUjWTGUJJ92NvQPUtk9w-XksIUD6ZR0WD7lVkzHQ19ra6myx3Ryq7n3r2jjuQQPK2mpIA7v5N3iaoMw8pnIJ9We6OgJEpMf4mZR6xYKhdQhcm3IwqQmYnQVJtNfBHm1YXiGnWvQYl_k8HZV0x9w5tmEP7uFKH1zJvJiRhGiuYyTiYPlceyD_6U_d4ZHLO0HNHGUelXmdis7mGEMQ2e2tansPuuo6ydDr63ZGap2apmalS-5uTb6GvEIyEML9m7r58VpjrWgJTStL_AX5xeGg1s-GhSFY7oeXaD7VrUb375u__DLnD2HXoLmnIslK-U6KHJG7rJFaUdabS_VkEqS2HMdKnxlvbVQy_LyKK0VkfNgeYRwHHZhTkHGLDT9Uhz-iYDhrLsOHLoTnj6F--5sdVvsfXmA5vbEBBIPLV0Uim4pTRey1LtEhaqYpzopOPjRLHxpSa2Ku50bju8b7Bda3wcMOD_J1Dd_ewB7voaDr4O2gLVVqQIY8pyKZ9hDneH13C3S5Iu94Jpr34bwZSAx7uGk" />
    </form>
    <div id="trk_jschal_js" style="display:none;background-image:url('/cdn-cgi/images/trace/jsch/nojs/transparent.gif?ray=7a3bf2de2d6f0a75')"></div>
    <script>
    (function(){
        window._cf_chl_opt={
            cvId: '2',
            cZone: 'gitlab.com',
            cType: 'non-interactive',
            cNounce: '46662',
            cRay: '7a3bf2de2d6f0a75',
            cHash: '3c3fe4246c48b37',
            cUPMDTk: "\/users\/sign_in?__cf_chl_tk=HXtYm_4ziDxcn2QOzIf1hRcbUwhx1Nq3DkBAp5O0R7c-1678119864-0-gaNycGzNCBA",
            cFPWv: 'b',
            cTTimeMs: '1000',
            cMTimeMs: '60000',
            cTplV: 1,
            cTplB: 'cf',
            cK: "",
            cRq: {
                ru: 'aHR0cHM6Ly9naXRsYWIuY29tL3VzZXJzL3NpZ25faW4=',
                ra: 'cHl0aG9uLWdpdGxhYi8zLjEzLjA=',
                rm: 'R0VU',
                d: 'B3yIpEyJbuUfzQpeI+5VYyHhFJujPE8wHnh8geEMeVb2f5/p0aNkXyQMJCAiUHBc6dImP/67K3V3KNNb1792CIXcZetsKsvk+jaZ4NQXlnj8FIsCyF6Lsfmy4GTmGArhtyfJVxbTUO3luOhNiW8FpmZ1PhAtUCMnWCdPBt7cNQLTBcEvqOJoSCiNbzzXoSyjw6dcclny4L5mQj9hbLMbjoohjD0noCNEg1vzM07FEgDlegbONGgvIFt8dBedIw1V/Kt4QY/4jiNQ3e29pFWXeLIHNRoBNdmAsLREMY3o/Go0tGtQiihNvXV4zKjmgWMQNw+wltGx5UlkKUulN6iCRRbKfSNJ6csyeUnZhM0DoRBuvqSf741dSur2Hx5BIeVnrZXpUjbF20EIlZhC+L7Vcs9sw539NqPJCGms+TiQDlgHnYzhY0iuyfwzgSLus23fOHJ2GM+4TFT6NStUZobWFL4BoVZR8dd9A3kVopFEZmhyS5ssBKUOvYDZNNwxr2h+2ku/5/UM5y5SvaEUeO5H3gsQICvQ6JwIE4LL/BiOKR+YZuVG+pNwV3apzcFy1eEoptQx2NlVNBMFh4AbDEeypj3iG0atjcb//H33YhN6cSN2BZdE7t7MJVH5OWrc4okDBJzUXMUN8WbmcAnFNZIZ2jfUt/pc3Ja+QAXC8IYodgzWMXOq9Fg+FDBzNYSeN5I3eML6IpD1txEr6h8e7viWSPWlOej06nNZwWCZmrlQv04=',
                t: 'MTY3ODExOTg2NC4wMjUwMDA=',
                m: 'tPf2duYHQqeZ79CyPyPT7knlZ+oqJuXmvQjj+5uUCl8=',
                i1: 'QiCTfwprsc9qNgV4heVf+A==',
                i2: 'XhY9ULEAaSyWaGSjPMZyBQ==',
                zh: 'UnJDyo9FrWqFHAM0dnr3Qrw4Ll86sU7CDCiveOM3u04=',
                uh: '/JJ6xz4e5TdtnGO7Lwv2QeQChXwkznt+lwJStmxJQ7U=',
                hh: 'lGQbzypQ55vDVgAzrKu7GNtEf1PrcZK3oqezycJ79vw=',
            }
        };
        var trkjs = document.createElement('img');
        trkjs.setAttribute('src', '/cdn-cgi/images/trace/jsch/js/transparent.gif?ray=7a3bf2de2d6f0a75');
        trkjs.setAttribute('alt', '');
        trkjs.setAttribute('style', 'display: none');
        document.body.appendChild(trkjs);
        var cpo = document.createElement('script');
        cpo.src = '/cdn-cgi/challenge-platform/h/b/orchestrate/jsch/v1?ray=7a3bf2de2d6f0a75';
        window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;
        window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.slice(0, location.href.length - window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search;    
        if (window.history && window.history.replaceState) {
            var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;
            history.replaceState(null, null, "\/users\/sign_in?__cf_chl_rt_tk=HXtYm_4ziDxcn2QOzIf1hRcbUwhx1Nq3DkBAp5O0R7c-1678119864-0-gaNycGzNCBA" + window._cf_chl_opt.cOgUHash);
            cpo.onload = function() {
                history.replaceState(null, null, ogU);
            };
        }
        document.getElementsByTagName('head')[0].appendChild(cpo);
    }());
</script>

</div>

    <hr />
  </div>
</body>
</html>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\tom\.conda\envs\unstructured\lib\site-packages\gitlab\exceptions.py", line 339, in wrapped_f
    raise error(e.error_message, e.response_code, e.response_body) from e
gitlab.exceptions.GitlabListError: 403: <!DOCTYPE html>
<html>
<head>
  <meta content="width=device-width, initial-scale=1, maximum-scale=1" name="viewport">
  <title>Checking your Browser - GitLab</title>
  <style>body{align-items:center;color:#666;display:flex;flex-direction:column;font-family:Helvetica Neue,Helvetica,Arial,sans-serif;font-size:14px;justify-content:center;margin:auto;text-align:center}hr{border:0;border-bottom:1px solid #fff;border-top:1px solid #eee;margin:18px auto;max-width:800px}img{max-width:40vw}.container{margin:auto 20px}.cferror_details{list-style-type:none}.cf-error-details h1{color:#456;font-size:20px;font-weight:400;line-height:28px}</style>
<meta http-equiv="refresh" content="35">
</head>

<body>
  <h1>
    <img src="data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjE5MiIgdmlld0JveD0iMCAwIDI1IDI0IiBmaWxsPSJub25lIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciPgogIDxwYXRoIGQ9Im0yNC41MDcgOS41LS4wMzQtLjA5TDIxLjA4Mi41NjJhLjg5Ni44OTYgMCAwIDAtMS42OTQuMDkxbC0yLjI5IDcuMDFINy44MjVMNS41MzUuNjUzYS44OTguODk4IDAgMCAwLTEuNjk0LS4wOUwuNDUxIDkuNDExLjQxNiA5LjVhNi4yOTcgNi4yOTcgMCAwIDAgMi4wOSA3LjI3OGwuMDEyLjAxLjAzLjAyMiA1LjE2IDMuODY3IDIuNTYgMS45MzUgMS41NTQgMS4xNzZhMS4wNTEgMS4wNTEgMCAwIDAgMS4yNjggMGwxLjU1NS0xLjE3NiAyLjU2LTEuOTM1IDUuMTk3LTMuODkuMDE0LS4wMUE2LjI5NyA2LjI5NyAwIDAgMCAyNC41MDcgOS41WiIKICAgICAgICBmaWxsPSIjRTI0MzI5Ii8+CiAgPHBhdGggZD0ibTI0LjUwNyA5LjUtLjAzNC0uMDlhMTEuNDQgMTEuNDQgMCAwIDAtNC41NiAyLjA1MWwtNy40NDcgNS42MzIgNC43NDIgMy41ODQgNS4xOTctMy44OS4wMTQtLjAxQTYuMjk3IDYuMjk3IDAgMCAwIDI0LjUwNyA5LjVaIgogICAgICAgIGZpbGw9IiNGQzZEMjYiLz4KICA8cGF0aCBkPSJtNy43MDcgMjAuNjc3IDIuNTYgMS45MzUgMS41NTUgMS4xNzZhMS4wNTEgMS4wNTEgMCAwIDAgMS4yNjggMGwxLjU1NS0xLjE3NiAyLjU2LTEuOTM1LTQuNzQzLTMuNTg0LTQuNzU1IDMuNTg0WiIKICAgICAgICBmaWxsPSIjRkNBMzI2Ii8+CiAgPHBhdGggZD0iTTUuMDEgMTEuNDYxYTExLjQzIDExLjQzIDAgMCAwLTQuNTYtMi4wNUwuNDE2IDkuNWE2LjI5NyA2LjI5NyAwIDAgMCAyLjA5IDcuMjc4bC4wMTIuMDEuMDMuMDIyIDUuMTYgMy44NjcgNC43NDUtMy41ODQtNy40NDQtNS42MzJaIgogICAgICAgIGZpbGw9IiNGQzZEMjYiLz4KPC9zdmc+Cg==" alt="GitLab" /><br />
  </h1>
  <div class="container">
    <div class="cf-browser-verification cf-im-under-attack">
    <noscript>
        <h1 style="color:#bd2426;">Please turn JavaScript on and reload the page.</h1>
    </noscript>
    <div id="cf-content">
        <div id="cf-bubbles">
            <div class="bubbles"></div>
            <div class="bubbles"></div>
            <div class="bubbles"></div>
        </div>
        <h1>Checking your browser before accessing gitlab.com.</h1>
        <div id="no-cookie-warning" class="cookie-warning" style="display:none">
            <p style="color:#bd2426;">Please enable Cookies and reload the page</p>
        </div>
        <p>This process is automatic. Your browser will redirect to your requested content shortly.</p>
        <p id="cf-spinner-allow-5-secs">Please allow up to 5 seconds...</p>
        <p id="cf-spinner-redirecting" style="display:none">Redirecting...</p>
    </div>
    <form id="challenge-form" class="challenge-form" action="/users/sign_in?__cf_chl_f_tk=HXtYm_4ziDxcn2QOzIf1hRcbUwhx1Nq3DkBAp5O0R7c-1678119864-0-gaNycGzNCBA" method="POST" enctype="application/x-www-form-urlencoded">
        <input type="hidden" name="md" value="46NIaWXSUWZ1979PeJ3JhZ4.Jb7XLPFQuYMQscurr10-1678119864-0-AUUSHcj3pg4_7vLliy1Drk-fkrvm4zQztSDOeZKfkWf_N9w_v2UN4AHH8V17xJmc2d398tWRD0QzmBaeQ_fKA1mNGROKZogaDqI-dJ9I1C-ArOORh53A7haYLVvIvLyyLuoti5fWoQn_kHWFfEJos-xLbUFsQlspr5liw4RkYJEJmitCEhz3HO0FCiX4XjJ-NuYFzzJKGWpGqsnwzDJcQ_VZ46YnJQ1S3Oo3kovU7rTFXW6dM1vnHW7TkAKM1-E0-29Grn9yd29gOd17kZrLJMR33xNw72Yi5LA4RcQX2AK4j_OXcu3J7tsUKsE9H0EMt55ERaUN8ZfnQwT9kluK73SYiNXAfpLp-7uP51IDNw_B2JND_ya8Ih0NDHQ9kwjQd_6ycU2hUJNfpN6wO6uwUB8YNx4OZDu2TopTTLoqN5xG0dY6uKZt8OUyhW3WZ-cNbpwtgKBp2hgzqnYoL4o7oXsbmwLiJjiWzDW71PxifPcJQgtSAm3UntJhy00z3Q8R2sQUu0tILQ-nsgivahA3mHrPhzIBSY4p2Miu433TPCMSp3toPwHOBntBW3-4MeuTiyXg-CIhsRdr3KThoxF2f9cYmJB-H8ouZ3TQ82FfxQrfgelsxEx7YDlMcvzpaQWYYz_qUw2Jos_P1ua9hSecTTl0m-v9fbzyLgs4w57oO1KBeRJyU0I7eompfPqBNP-5tkYKM6rsju3s-cjeEbaX1jUknx61ATvm6GTPPpR4DTOSU548uaVoXAFMYQGm2PWxwnfD1TQWJEy22oi-zur3yXo25elwYhpe94KnDa0pmf4p5pPc6QLTeia7TiKlvhj4X1JxRzwbEzXy0vuLMGvlEEMbasqglbfIqkfs8Yf2SSf5ycpRBfStTy23FxX47HJ9I18mUoyl6m3qmyc0h9c4ylPteE15EFm1BD2yGEHUo0aS8rEf5v1kPSeobVuN0NgaNCdIvseVo6sLY4i1PBMjYQmGhwHRi9T8QAxbr1ycwE29mTuQGT8whXz3B5-2x6o5t4x8UJeGq2v4Euu4kfpRllfJ125X9gtoMQGwNbCdoc7J0ppW_5RhQXnfj85A3MrvNE-Jy9xq-IhQYccrM1l8ozvd6yllM1nzafsMFGgbVDRVnjh9DeCxzn_q1lyy7T4i-RhyzZKrxO6xjPm4GIHrvUQ9TNka9Tt5-5i8hGYp8lGy6rbY7ALRfNJZQVRTad2XP6WANnhMXMEBpPfSx33tT4bSdVz4nrCOFi9kI8aTkQN7Hxd4GB60dlpZ1cr-GSGIMVlB-G7XtBXlUd426EDogsh9J-NZsBYAUDN0P0Gmfi_S286CpPRD2uM0y7Q5i9mxnqnvp_cooO5p7OaqxkQJUNdK6ZUrLXCZyX1AN8p4c-a4jh3phDgk52jp-OvMXC_ev31Ve9KOftm1Vnfns-v-v9r5lFrJGYlusZnTcmlICQKrCOq075QIUZ0YUltC7TrEXUjWTGUJJ92NvQPUtk9w-XksIUD6ZR0WD7lVkzHQ19ra6myx3Ryq7n3r2jjuQQPK2mpIA7v5N3iaoMw8pnIJ9We6OgJEpMf4mZR6xYKhdQhcm3IwqQmYnQVJtNfBHm1YXiGnWvQYl_k8HZV0x9w5tmEP7uFKH1zJvJiRhGiuYyTiYPlceyD_6U_d4ZHLO0HNHGUelXmdis7mGEMQ2e2tansPuuo6ydDr63ZGap2apmalS-5uTb6GvEIyEML9m7r58VpjrWgJTStL_AX5xeGg1s-GhSFY7oeXaD7VrUb375u__DLnD2HXoLmnIslK-U6KHJG7rJFaUdabS_VkEqS2HMdKnxlvbVQy_LyKK0VkfNgeYRwHHZhTkHGLDT9Uhz-iYDhrLsOHLoTnj6F--5sdVvsfXmA5vbEBBIPLV0Uim4pTRey1LtEhaqYpzopOPjRLHxpSa2Ku50bju8b7Bda3wcMOD_J1Dd_ewB7voaDr4O2gLVVqQIY8pyKZ9hDneH13C3S5Iu94Jpr34bwZSAx7uGk" />
    </form>
    <div id="trk_jschal_js" style="display:none;background-image:url('/cdn-cgi/images/trace/jsch/nojs/transparent.gif?ray=7a3bf2de2d6f0a75')"></div>
    <script>
    (function(){
        window._cf_chl_opt={
            cvId: '2',
            cZone: 'gitlab.com',
            cType: 'non-interactive',
            cNounce: '46662',
            cRay: '7a3bf2de2d6f0a75',
            cHash: '3c3fe4246c48b37',
            cUPMDTk: "\/users\/sign_in?__cf_chl_tk=HXtYm_4ziDxcn2QOzIf1hRcbUwhx1Nq3DkBAp5O0R7c-1678119864-0-gaNycGzNCBA",
            cFPWv: 'b',
            cTTimeMs: '1000',
            cMTimeMs: '60000',
            cTplV: 1,
            cTplB: 'cf',
            cK: "",
            cRq: {
                ru: 'aHR0cHM6Ly9naXRsYWIuY29tL3VzZXJzL3NpZ25faW4=',
                ra: 'cHl0aG9uLWdpdGxhYi8zLjEzLjA=',
                rm: 'R0VU',
                d: 'B3yIpEyJbuUfzQpeI+5VYyHhFJujPE8wHnh8geEMeVb2f5/p0aNkXyQMJCAiUHBc6dImP/67K3V3KNNb1792CIXcZetsKsvk+jaZ4NQXlnj8FIsCyF6Lsfmy4GTmGArhtyfJVxbTUO3luOhNiW8FpmZ1PhAtUCMnWCdPBt7cNQLTBcEvqOJoSCiNbzzXoSyjw6dcclny4L5mQj9hbLMbjoohjD0noCNEg1vzM07FEgDlegbONGgvIFt8dBedIw1V/Kt4QY/4jiNQ3e29pFWXeLIHNRoBNdmAsLREMY3o/Go0tGtQiihNvXV4zKjmgWMQNw+wltGx5UlkKUulN6iCRRbKfSNJ6csyeUnZhM0DoRBuvqSf741dSur2Hx5BIeVnrZXpUjbF20EIlZhC+L7Vcs9sw539NqPJCGms+TiQDlgHnYzhY0iuyfwzgSLus23fOHJ2GM+4TFT6NStUZobWFL4BoVZR8dd9A3kVopFEZmhyS5ssBKUOvYDZNNwxr2h+2ku/5/UM5y5SvaEUeO5H3gsQICvQ6JwIE4LL/BiOKR+YZuVG+pNwV3apzcFy1eEoptQx2NlVNBMFh4AbDEeypj3iG0atjcb//H33YhN6cSN2BZdE7t7MJVH5OWrc4okDBJzUXMUN8WbmcAnFNZIZ2jfUt/pc3Ja+QAXC8IYodgzWMXOq9Fg+FDBzNYSeN5I3eML6IpD1txEr6h8e7viWSPWlOej06nNZwWCZmrlQv04=',
                t: 'MTY3ODExOTg2NC4wMjUwMDA=',
                m: 'tPf2duYHQqeZ79CyPyPT7knlZ+oqJuXmvQjj+5uUCl8=',
                i1: 'QiCTfwprsc9qNgV4heVf+A==',
                i2: 'XhY9ULEAaSyWaGSjPMZyBQ==',
                zh: 'UnJDyo9FrWqFHAM0dnr3Qrw4Ll86sU7CDCiveOM3u04=',
                uh: '/JJ6xz4e5TdtnGO7Lwv2QeQChXwkznt+lwJStmxJQ7U=',
                hh: 'lGQbzypQ55vDVgAzrKu7GNtEf1PrcZK3oqezycJ79vw=',
            }
        };
        var trkjs = document.createElement('img');
        trkjs.setAttribute('src', '/cdn-cgi/images/trace/jsch/js/transparent.gif?ray=7a3bf2de2d6f0a75');
        trkjs.setAttribute('alt', '');
        trkjs.setAttribute('style', 'display: none');
        document.body.appendChild(trkjs);
        cpo.src = '/cdn-cgi/challenge-platform/h/b/orchestrate/jsch/v1?ray=7a3bf2de2d6f0a75';
        window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;
        window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.slice(0, location.href.length - window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search;    
        if (window.history && window.history.replaceState) {
            var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;
            history.replaceState(null, null, "\/users\/sign_in?__cf_chl_rt_tk=HXtYm_4ziDxcn2QOzIf1hRcbUwhx1Nq3DkBAp5O0R7c-1678119864-0-gaNycGzNCBA" + window._cf_chl_opt.cOgUHash);
            cpo.onload = function() {
                history.replaceState(null, null, ogU);
            };
        }
        document.getElementsByTagName('head')[0].appendChild(cpo);
    }());
</script>

</div>

    <hr />
  </div>
</body>
</html>
```
</details>

I receive the same Traceback regardless of using `gl.projects.get`, `gl.projects.list`, `gl.registry_repositories.get`, etc. and regardless of whether I use a private access token or not.

When saved and opened, the following page appears: 
![image](https://user-images.githubusercontent.com/37621491/223168214-1e825eb6-8789-49d5-ad2e-ab2a34477926.png)

## Specifications

  - python-gitlab version:3.13.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): gitlab.com

**Comment by JohnVillalovos** [comment]
Change it to:

```
>>> gl = gitlab.Gitlab("https://gitlab.com")
```

That should fix your issue.

**Comment by tomaarsen** [comment]
Thank you for the swift response! I'll try it out soon.

**Comment by tomaarsen** [comment]
Works like a charm. Thanks for the concise answer! I'll close this.
