### ISSUE TITLE
unexpected exception when getting group

### ISSUE THREAD

**Issue by jalanh11640** [python-gitlab/python-gitlab#2560]
group = gl.groups.get(10) # Works just fine..  group.id = 10, group.name = "myGroup"
gl.groups.get(group.name) # gitlab.exceptions.GitlabGetError: 404: 404 Group Not Found

## Expected Behavior
Should return group object

## Actual Behavior
Generates GitlabGetError exception.  Here's the full backtrace

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gitlab/exceptions.py", line 336, in wrapped_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/gitlab/mixins.py", line 122, in get
    server_data = self.gitlab.http_get(path, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/gitlab/client.py", line 829, in http_get
    "get", path, query_data=query_data, streamed=streamed, **kwargs
  File "/usr/local/lib/python3.7/site-packages/gitlab/client.py", line 797, in http_request
    response_body=result.content,
gitlab.exceptions.GitlabHttpError: 404: 404 Group Not Found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/gitlab/v4/objects/groups.py", line 373, in get
    return cast(Group, super().get(id=id, lazy=lazy, **kwargs))
  File "/usr/local/lib/python3.7/site-packages/gitlab/exceptions.py", line 338, in wrapped_f
    raise error(e.error_message, e.response_code, e.response_body) from e
gitlab.exceptions.GitlabGetError: 404: 404 Group Not Found

## Specifications

  - python-gitlab 3.14.0:
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): GitLab Enterprise Edition [15.6.8-ee](https://gitlab.com/gitlab-org/gitlab/-/tags/v15.6.8-ee)

**Comment by JohnVillalovos** [comment]
What is the value of `group.path` and `group.full_path`

See: https://docs.gitlab.com/ee/api/groups.html#details-of-a-group

It can take an integer ID or the path to the group. `group.name` is not necessarily the path to the group.

**Comment by jalanh11640** [comment]
group.path = "myGroup"
group.full_path = "software/myGroup"

**Comment by JohnVillalovos** [comment]
My theory is that if you use `group.full_path` it will work.

**Comment by jalanh11640** [comment]
> My theory is that if you use `group.full_path` it will work.

You are correct.
