### ISSUE TITLE
APIs request the same path, one works, one 404

### ISSUE THREAD

**Issue by Breezewrf** [python-gitlab/python-gitlab#2671]
## Description of the problem, including code/CLI snippet
I run a local GitLab in localhost, and try to get file using APIs like following:
`f = project.files.get(file_path='demo1/demo1.png', ref='master')`
`f = project.files.raw(file_path='demo1/demo1.png', ref='master')`

+ when I run `f = project.files.get(file_path='demo1/demo1.png', ref='master')`, the response is success.
> send: b'GET /api/v4/projects/1 HTTP/1.1\r\nHost: gitlab.local:30080\r\nUser-Agent: python-gitlab/3.15.0\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nPRIVATE-TOKEN: 2o1JzNEftsiLzEbkjAJM\r\nContent-type: application/json\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Server: nginx
header: Date: Wed, 27 Sep 2023 07:47:56 GMT
header: Content-Type: application/json
header: Transfer-Encoding: chunked
header: Connection: keep-alive
header: Cache-Control: max-age=0, private, must-revalidate
header: Etag: W/"1b5c65bcf50a63d493ce0e0baf011237"
header: Vary: Origin
header: X-Request-Id: e332099f-6e06-4f51-8a9c-0ce662093140
header: X-Runtime: 0.030084
header: Strict-Transport-Security: max-age=31536000
header: Content-Encoding: gzip
DEBUG:urllib3.connectionpool:http://gitlab.local:30080 "GET /api/v4/projects/1 HTTP/1.1" 200 None
send: b'GET /api/v4/projects/1/repository/files/demo1%2Fdemo1.png?ref=master HTTP/1.1\r\nHost: gitlab.local:30080\r\nUser-Agent: python-gitlab/3.15.0\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nPRIVATE-TOKEN: 2o1JzNEftsiLzEbkjAJM\r\nContent-type: application/json\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Server: nginx
header: Date: Wed, 27 Sep 2023 07:47:56 GMT
header: Content-Type: application/json
header: Transfer-Encoding: chunked
header: Connection: keep-alive
header: Cache-Control: max-age=0, private, must-revalidate
header: Etag: W/"ad33b03b0cd029fbef4b59144f6eaa8e"
header: Vary: Origin
header: X-Request-Id: a68bf7b7-9fec-401f-a476-aa7a8d97184d
header: X-Runtime: 0.019862
header: Strict-Transport-Security: max-age=31536000
header: Content-Encoding: gzip
DEBUG:urllib3.connectionpool:http://gitlab.local:30080 "GET /api/v4/projects/1/repository/files/demo1%2Fdemo1.png?ref=master HTTP/1.1" 200 None

+ But when I change api to f = project.files.raw(file_path='demo1/demo1.png', ref='master'), keeping file_path unchanged, which causes a 404 error:
> send: b'GET /api/v4/projects/1 HTTP/1.1\r\nHost: gitlab.local:30080\r\nUser-Agent: python-gitlab/3.15.0\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nPRIVATE-TOKEN: 2o1JzNEftsiLzEbkjAJM\r\nContent-type: application/json\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Server: nginx
header: Date: Wed, 27 Sep 2023 07:49:42 GMT
header: Content-Type: application/json
header: Transfer-Encoding: chunked
header: Connection: keep-alive
header: Cache-Control: max-age=0, private, must-revalidate
header: Etag: W/"1b5c65bcf50a63d493ce0e0baf011237"
header: Vary: Origin
header: X-Request-Id: 9c69e108-d505-4c4a-ac8e-55de58562bc7
header: X-Runtime: 0.028998
header: Strict-Transport-Security: max-age=31536000
header: Content-Encoding: gzip
DEBUG:urllib3.connectionpool:http://gitlab.local:30080 "GET /api/v4/projects/1 HTTP/1.1" 200 None
send: b'GET /api/v4/projects/1/repository/files/demo1%2Fdemo1.png/raw?ref=master HTTP/1.1\r\nHost: gitlab.local:30080\r\nUser-Agent: python-gitlab/3.15.0\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nPRIVATE-TOKEN: 2o1JzNEftsiLzEbkjAJM\r\nContent-type: application/json\r\n\r\n'
reply: 'HTTP/1.1 404 Not Found\r\n'
header: Server: nginx
header: Date: Wed, 27 Sep 2023 07:49:42 GMT
header: Content-Type: application/json
header: Transfer-Encoding: chunked
header: Connection: keep-alive
header: Cache-Control: no-cache
header: Vary: Origin
header: X-Request-Id: 0d6bf544-70d9-4963-9aaf-b419b91323dc
header: X-Runtime: 0.018493
header: Content-Encoding: gzip
DEBUG:urllib3.connectionpool:http://gitlab.local:30080 "GET /api/v4/projects/1/repository/files/demo1%2Fdemo1.png/raw?ref=master HTTP/1.1" 404 None
Traceback (most recent call last):
  File "/home/lscm/.conda/envs/restful/lib/python3.8/site-packages/gitlab/exceptions.py", line 336, in wrapped_f
    return f(*args, **kwargs)
  File "/home/lscm/.conda/envs/restful/lib/python3.8/site-packages/gitlab/v4/objects/files.py", line 264, in raw
    result = self.gitlab.http_get(
  File "/home/lscm/.conda/envs/restful/lib/python3.8/site-packages/gitlab/client.py", line 828, in http_get
    result = self.http_request(
  File "/home/lscm/.conda/envs/restful/lib/python3.8/site-packages/gitlab/client.py", line 794, in http_request
    raise gitlab.exceptions.GitlabHttpError(
gitlab.exceptions.GitlabHttpError: 404: 404 File Not Found
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "src/main.py", line 62, in <module>
    f = project.files.raw(file_path='demo1/demo1.png', ref='master')
  File "/home/lscm/.conda/envs/restful/lib/python3.8/site-packages/gitlab/cli.py", line 71, in wrapped_f
    return f(*args, **kwargs)
  File "/home/lscm/.conda/envs/restful/lib/python3.8/site-packages/gitlab/exceptions.py", line 338, in wrapped_f
    raise error(e.error_message, e.response_code, e.response_body) from e
gitlab.exceptions.GitlabGetError: 404: 404 File Not Found

## Expected Behavior
`f = project.files.raw(file_path='demo1/demo1.png', ref='master')` is expected to response 200 like the api `f = project.files.get(file_path='demo1/demo1.png', ref='master')` 

## Actual Behavior
`f = project.files.raw(file_path='demo1/demo1.png', ref='master')` responses with 404

## Specifications

  - python-gitlab version: Version: 3.15.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 3.15.0

**Comment by Breezewrf** [comment]
I think it is the problem of Requests that modified the url https://github.com/psf/requests/blob/ee93fac6b2f715151f1aa9a1a06ddba9f7dcc59a/src/requests/models.py#L480C23-L480C23

**Comment by Breezewrf** [comment]
Sorry for my confused version of Gitlab, I will check it later again
