### ISSUE TITLE
ProjectFile.delete error

### ISSUE THREAD

**Issue by james-powis** [python-gitlab/python-gitlab#283]
Greetings, I am encountering the following error:
```
Traceback (most recent call last):
  File "create_new_customer.py", line 76, in <module>
    'commit_message': 'Cleaning up for customer use'
  File "/Users/jrp/Desktop/terraform/new_aws_customer/SRC/lib/python3.6/site-packages/gitlab/base.py", line 154, in delete
    self.gitlab.delete(self.obj_cls, id, **args)
  File "/Users/jrp/Desktop/terraform/new_aws_customer/SRC/lib/python3.6/site-packages/gitlab/__init__.py", line 503, in delete
    params[k] = getattr(obj, k)
AttributeError: type object 'ProjectFile' has no attribute 'branch_name'
```

Referencing this listing blog I should still be fine using the V3 api (hard set in the code) https://docs.gitlab.com/ee/api/v3_to_v4.html

and here is the relevant block of code (reduced for simplicity)
```python
#!/usr/bin/env python3
...
fork = parent_project.forks.create({'namespace': 'aws_customer'})
child = gl.projects.get(fork.id)
files = ['file1', 'file2']
for f in files:
    child.files.delete({'file_path': f,
        'branch': 'master',
        'commit_message': 'post fork cleanup'
    })
```

Any advice would be appreciated.

**Comment by gpocentek** [comment]
Hi,

I guess the deletion code for v3 is kind of broken. The following should help you:

```python
for f in files:
    gitlab_file = child.files.get(file_path=f, ref='master')
    gitlab_file.delete(branch_name='master', commit_message='post fork cleanup')
```

Thinks should work better with v4 API.

**Comment by gpocentek** [comment]
I'm closing this issue as there is a workaround for v3. Feel free to reopen if this still doesn't work.

Thanks.
