### ISSUE TITLE
403 Forbidden  - Not authorized to access /api/v4/users

### ISSUE THREAD

**Issue by fourier11** [python-gitlab/python-gitlab#292]
I use V3 API like the following:
```
git = gitlab.Gitlab(GITLAB_HOST, GITLAB_TOKEN)
user_id = git.users.list(username=gitlab_id)
```

**Traceback**
```
`Traceback (most recent call last):
  File "/Users/admin/PycharmProjects/scripts/mrcount/mr_count_android_old.py", line 128, in <module>
    dev_slack_id = get_slack_id_from_gitlab_id(author)
  File "/Users/admin/PycharmProjects/scripts/mrcount/mr_count_android_old.py", line 51, in get_slack_id_from_gitlab_id
    user_id = git.users.list(username=gitlab_id)
  File "/usr/local/lib/python2.7/site-packages/gitlab/base.py", line 117, in list
    return self.obj_cls.list(self.gitlab, **args)
  File "/usr/local/lib/python2.7/site-packages/gitlab/base.py", line 253, in list
    return gl.list(cls, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/gitlab/__init__.py", line 441, in list
    return self._raw_list(url, obj_class, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/gitlab/__init__.py", line 361, in _raw_list
    raise_error_from_response(r, GitlabListError)
  File "/usr/local/lib/python2.7/site-packages/gitlab/exceptions.py", line 204, in raise_error_from_response
    response_body=response.content)
gitlab.exceptions.GitlabListError: 403: 403 Forbidden  - Not authorized to access /api/v4/users`
```

When I uninstall python-gitlab,then I use pyapi-gitlab, everything is OK.
`users = git.getusers(search=gitlab_id, per_page=200)`

Thanks for the help!

**Comment by lichuanxiao** [comment]
I have the same prolem at gitlab 9.4.0 , it seem that the gitlab's issue , but when I upgrade gitlab to 9.4.1.  everything is ok!

**Comment by martingabelmann** [comment]
I can confirm @lichuanxiao`s  answer, updating gitlab fixed it.

**Comment by fourier11** [comment]
When I update gitlab to 9.4.2，it's fixed.
