### ISSUE TITLE
Feature : Add API get-file-metadata-only

### ISSUE THREAD

**Issue by usinelogicielle** [python-gitlab/python-gitlab#2962]
## Description of the problem, including code/CLI snippet

When a file is very large, the ProjectFileManager.get() sends an error 500 because the server can't give the file content.
It would be nice to have only metadata with this API: https://docs.gitlab.com/ee/api/repository_files.html#get-file-metadata-only 
Perhaps add a boolean “metadata” parameter to make an HTTP HEAD instead of an HTTP GET and fill the ProjectFile object without the contents.

## Expected Behavior

Get only the metadata of file in repository and not the content because if file is too big, Gitlab server will throw an error 500.

## Actual Behavior

```
Traceback (most recent call last):
  File "/work/jenkins_workspace_qualif/workspace/es_pratiques_gitlab_files_master/ul/analyzer/gitlab/files_size_type.py", line 241, in do_analysis
    gitlab_files = self.gitlab.get_gitlab_files(gitlab_project, branch)
  File "/work/jenkins_workspace_qualif/workspace/es_pratiques_gitlab_files_master/ul/common/utils/gitlab_utils.py", line 261, in get_gitlab_files
    raise e
  File "/work/jenkins_workspace_qualif/workspace/es_pratiques_gitlab_files_master/ul/common/utils/gitlab_utils.py", line 247, in get_gitlab_files
    file = project.files.get(file_path=repository_file["path"], ref=branch)
  File "/work/jenkins_workspace_qualif/workspace/es_pratiques_gitlab_files_master/.venv/lib/python3.8/site-packages/gitlab/cli.py", line 71, in wrapped_f
    return f(*args, **kwargs)
  File "/work/jenkins_workspace_qualif/workspace/es_pratiques_gitlab_files_master/.venv/lib/python3.8/site-packages/gitlab/v4/objects/files.py", line 131, in get
    return cast(ProjectFile, GetMixin.get(self, file_path, ref=ref, **kwargs))
  File "/work/jenkins_workspace_qualif/workspace/es_pratiques_gitlab_files_master/.venv/lib/python3.8/site-packages/gitlab/exceptions.py", line 338, in wrapped_f
    raise error(e.error_message, e.response_code, e.response_body) from e
gitlab.exceptions.GitlabGetError: 500: 500 Internal Server Error
```

## Specifications

  - python-gitlab version: 3.15.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 16.4.1

**Comment by nejch** [comment]
@usinelogicielle all resources that support `get()` should already also support `head()` as well. Have you tried that? Let us know if it's not clear enough in the docs.

**Comment by nejch** [comment]
Hm, seems to already be documented as well: https://python-gitlab.readthedocs.io/en/stable/gl_objects/projects.html

**Comment by usinelogicielle** [comment]
Hi @nejch ,

Sorry, I didn't see this page.
I close this issue.
