### ISSUE TITLE
Can't connect to GitLab server (maximum recursion depth exceeded while calling a Python object)

### ISSUE THREAD

**Issue by fgimian** [python-gitlab/python-gitlab#298]
Hi there folks, thanks so much for your efforts on this awesome library.

I'm using the very latest version of the library available in pip and am running it on a Python 3.5.1 installation on CentOS 7.

We have one project in particular that contains many thousands of builds, and when attempting to obtain them, I see the exception in the summary above.

Here's some sample code I'm using (names replaced for privacy reasons):

```python
from gitlab import Gitlab
gitlab = Gitlab.from_config(gitlab_id='lab')
project = gitlab.projects.get('test/TEST')
builds = project.builds.list(all=True)
```

When running this in either a script or the interactive Python shell, I get the following exception:

```
Python 3.5.1 (default, Oct 21 2016, 21:37:19)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from gitlab import Gitlab
>>> gitlab = Gitlab.from_config(gitlab_id='lab')
>>> project = gitlab.projects.get('test/TEST')
>>> builds = project.builds.list(all=True)
Traceback (most recent call last):
  File "/var/tmp/gitlab-test/lib/python3.5/site-packages/gitlab/__init__.py", line 342, in _raw_get
    **opts)
  File "/var/tmp/gitlab-test/lib/python3.5/site-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/var/tmp/gitlab-test/lib/python3.5/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/tmp/gitlab-test/lib/python3.5/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/var/tmp/gitlab-test/lib/python3.5/site-packages/requests/adapters.py", line 525, in send
    return self.build_response(request, resp)
  File "/var/tmp/gitlab-test/lib/python3.5/site-packages/requests/adapters.py", line 263, in build_response
    response = Response()
  File "/var/tmp/gitlab-test/lib/python3.5/site-packages/requests/models.py", line 599, in __init__
    self.headers = CaseInsensitiveDict()
  File "/var/tmp/gitlab-test/lib/python3.5/site-packages/requests/structures.py", line 46, in __init__
    self.update(data, **kwargs)
  File "/var/tmp/gitlab-test/lib64/python3.5/_collections_abc.py", line 771, in update
    if isinstance(other, Mapping):
  File "/var/tmp/gitlab-test/lib64/python3.5/abc.py", line 182, in __instancecheck__
    if subclass in cls._abc_cache:
  File "/var/tmp/gitlab-test/lib64/python3.5/_weakrefset.py", line 72, in __contains__
    wr = ref(item)
RecursionError: maximum recursion depth exceeded while calling a Python object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/tmp/gitlab-test/lib/python3.5/site-packages/gitlab/base.py", line 117, in list
    return self.obj_cls.list(self.gitlab, **args)
  File "/var/tmp/gitlab-test/lib/python3.5/site-packages/gitlab/base.py", line 253, in list
    return gl.list(cls, **kwargs)
  File "/var/tmp/gitlab-test/lib/python3.5/site-packages/gitlab/__init__.py", line 441, in list
    return self._raw_list(url, obj_class, **kwargs)
  File "/var/tmp/gitlab-test/lib/python3.5/site-packages/gitlab/__init__.py", line 385, in _raw_list
    raise e
  File "/var/tmp/gitlab-test/lib/python3.5/site-packages/gitlab/__init__.py", line 379, in _raw_list
    results.extend(self.list(cls, **args))
  File "/var/tmp/gitlab-test/lib/python3.5/site-packages/gitlab/__init__.py", line 441, in list
    return self._raw_list(url, obj_class, **kwargs)
  File "/var/tmp/gitlab-test/lib/python3.5/site-packages/gitlab/__init__.py", line 385, in _raw_list
    raise e
  File "/var/tmp/gitlab-test/lib/python3.5/site-packages/gitlab/__init__.py", line 379, in _raw_list
    results.extend(self.list(cls, **args))
  File "/var/tmp/gitlab-test/lib/python3.5/site-packages/gitlab/__init__.py", line 441, in list
    return self._raw_list(url, obj_class, **kwargs)
  File "/var/tmp/gitlab-test/lib/python3.5/site-packages/gitlab/__init__.py", line 385, in _raw_list
    raise e
  File "/var/tmp/gitlab-test/lib/python3.5/site-packages/gitlab/__init__.py", line 379, in _raw_list
    results.extend(self.list(cls, **args))
  File "/var/tmp/gitlab-test/lib/python3.5/site-packages/gitlab/__init__.py", line 441, in list
    return self._raw_list(url, obj_class, **kwargs)
  File "/var/tmp/gitlab-test/lib/python3.5/site-packages/gitlab/__init__.py", line 385, in _raw_list
    raise e
  File "/var/tmp/gitlab-test/lib/python3.5/site-packages/gitlab/__init__.py", line 379, in _raw_list
    results.extend(self.list(cls, **args))
  File "/var/tmp/gitlab-test/lib/python3.5/site-packages/gitlab/__init__.py", line 441, in list
    return self._raw_list(url, obj_class, **kwargs)
  File "/var/tmp/gitlab-test/lib/python3.5/site-packages/gitlab/__init__.py", line 385, in _raw_list
    raise e
  File "/var/tmp/gitlab-test/lib/python3.5/site-packages/gitlab/__init__.py", line 379, in _raw_list
    results.extend(self.list(cls, **args))
  File "/var/tmp/gitlab-test/lib/python3.5/site-packages/gitlab/__init__.py", line 441, in list
    return self._raw_list(url, obj_class, **kwargs)
...
  File "/var/tmp/gitlab-test/lib/python3.5/site-packages/gitlab/__init__.py", line 360, in _raw_list
    r = self._raw_get(path_, **params)
  File "/var/tmp/gitlab-test/lib/python3.5/site-packages/gitlab/__init__.py", line 345, in _raw_get
    "Can't connect to GitLab server (%s)" % e)
gitlab.exceptions.GitlabConnectionError: Can't connect to GitLab server (maximum recursion depth exceeded while calling a Python object)
>>>
```

Funnily enough, if I run it in IPython, it actually works:

```
Python 3.5.1 (default, Oct 21 2016, 21:37:19)
Type 'copyright', 'credits' or 'license' for more information
IPython 6.1.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from gitlab import Gitlab

In [2]: gitlab = Gitlab.from_config(gitlab_id='lab')

In [3]: project = gitlab.projects.get('test/TEST')

In [4]: builds = project.builds.list(all=True)

In [5]: len(builds)
Out[5]: 8071
```

Any help would be greatly appreciated! 😄 

Cheers
Fotis

**Comment by gpocentek** [comment]
Hi @fgimian 

This is a known problem in python-gitlab, and a complex one to fix in the v3 API. You should probably use explicit pagination to workaround the recursion limit, with the `page` and `per_page` parameters of the `list()` method. Something like:

```python
page = 1
while True:
    next_100 = project.builds.list(per_page=100, page=page)
    if not next_100:
        break
    # store the data or do what you need to do
    page += 1
```
FYI the upcoming v4 support should fix this issue (using generators instead of recursive functions).


Hope this helps.

**Comment by fgimian** [comment]
Ah, thanks so much for your reply @gpocentek 😄
