### ISSUE TITLE
NameError: name 'httpx' is not defined in latest release 4.11.0

### ISSUE THREAD

**Issue by fliiiix** [python-gitlab/python-gitlab#2983]
The latest release (4.11.0) broke something: 

```
Traceback (most recent call last):
  File "/home//work/steps_web/.env/bin/send-steps", line 5, in <module>
    from send_steps import main
  File "/home//work/steps_web/cli/send_steps.py", line 13, in <module>
    from gitlab import Gitlab
  File "/home//work/steps_web/.env/lib/python3.10/site-packages/gitlab/__init__.py", line 30, in <module>
    from gitlab.client import Gitlab, GitlabList, GraphQL  # noqa: F401
  File "/home//work/steps_web/.env/lib/python3.10/site-packages/gitlab/client.py", line 1279, in <module>
    class GraphQL:
  File "/home//work/steps_web/.env/lib/python3.10/site-packages/gitlab/client.py", line 1286, in GraphQL
    client: Optional[httpx.Client] = None,
NameError: name 'httpx' is not defined
```

I guess the type `httpx.Client` should only be used when `_GQL_INSTALLED` is true.

**Comment by fliiiix** [comment]
Ah nice thanks for 4.11.1 did not know that https://github.com/python-gitlab/python-gitlab/commit/b41b2de8884c2dc8c8be467f480c7161db6a1c87 this will work :tada:

**Comment by nejch** [comment]
Thanks @fliiiix, see #2981 for the initial discussion.
