### ISSUE TITLE
`ValueError: unsupported format character '/'` on `release.save()`

### ISSUE THREAD

**Issue by dbeecham** [python-gitlab/python-gitlab#301]
To reproduce:

```bash
$ docker run -it --rm alpine:latest sh
$ sed -i 's:v3.6:edge:g' /etc/apk/repositories
$ apk update
$ apk add python py-pip
$ pip install python-gitlab
$ python
>>> from gitlab import Gitlab
>>> gl = Gitlab(A_GITLAB_SITE, API_KEY)
>>> gl.auth()
>>> project = gl.projects.get("dbe/ci-test")
>>> tag = project.tags.list()[0]        # project name is 'v0.1'
>>> tag.release.save()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/gitlab/base.py", line 326, in save
    self._update(**kwargs)
  File "/usr/lib/python2.7/site-packages/gitlab/base.py", line 321, in _update
    json = self.gitlab.update(self, **kwargs)
  File "/usr/lib/python2.7/site-packages/gitlab/__init__.py", line 594, in update
    url = self._construct_url(id_=obj_id, obj=obj, parameters=params)
  File "/usr/lib/python2.7/site-packages/gitlab/__init__.py", line 261, in _construct_url
    url = obj_url % args
ValueError: unsupported format character '/' (0x2f) at index 52
```

**Comment by gpocentek** [comment]
Thanks for the report, there is indeed a bug there.

If your goal is to update you should use `tag.set_release_description('your description')` and you should be fine.

**Comment by dbeecham** [comment]
Ok! I'll try that. I've been doing `tag.release.description = ... `.

**Comment by gpocentek** [comment]
@dbeecham I'm closing the issue, feel free to reopen if the provided solution doesn't work for you. Thanks!
