### ISSUE TITLE
Error during authentication in v4 by using email+password

### ISSUE THREAD

**Issue by ViachaslauKabak** [python-gitlab/python-gitlab#311]
switching to v4
updated python-gitlab to 1.0.0
pyhon 2.7
>> import gitlab
>> gl3 = gitlab.Gitlab('http://servername', email='Jenkins_git', password='PassW0rd', api_version=4)
>> gl3.auth()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/gitlab/__init__.py", line 184, in auth
    self._credentials_auth()
  File "/usr/lib/python2.7/site-packages/gitlab/__init__.py", line 203, in _credentials_auth
    manager = self._objects.CurrentUserManager()
TypeError: __init__() takes at least 2 arguments (1 given)

**Comment by ViachaslauKabak** [comment]
The problem is only for user/password auth
Works ok if using token (but no need to auth when using token).
