### ISSUE TITLE
Error using v4 credential authentication

### ISSUE THREAD

**Issue by d0c-s4vage** [python-gitlab/python-gitlab#315]
# Problem

When using credential authentication with `api_version="4"` set, an error occurs when calling `client.auth()`:

# Reproduce

```python
client = gitlab.Gitlab(config.host,
                       email=email,
                       password=password,
                       api_version="4")
client.auth()
```

# Details

```
Traceback (most recent call last):
  ...
  File "repro.py", line XX, in function
    client.auth()
  File "/usr/local/lib/python2.7/dist-packages/gitlab/__init__.py", line 184, in auth
    self._credentials_auth()
  File "/usr/local/lib/python2.7/dist-packages/gitlab/__init__.py", line 203, in _credentials_auth
    manager = self._objects.CurrentUserManager()
```

**Comment by gpocentek** [comment]
Thank you for taking the time to report this problem.

This issue has already been addressed in the master branch, it will be available in the next release. See #311 and 89bf53f.

**Comment by d0c-s4vage** [comment]
Great! I searched open tickets, forgot to search the closed ones.
