### ISSUE TITLE
Set default branch for a given project

### ISSUE THREAD

**Issue by arnaudgelas** [python-gitlab/python-gitlab#330]
It would be great if we could change the default branch with python-gitlab (see documentation):

https://docs.gitlab.com/ce/api/projects.html#edit-project

**Comment by gpocentek** [comment]
Hi @arnaudgelas,

I've not tested this code but it should work:

```python
p = gl.projects.get(project_id)  # get the project
p.default_branch = 'develop'
p.save()
```

**Comment by arnaudgelas** [comment]
While iterating on group's project, I have tried saving but it fails:

```
g = gl.groups.get(group_id)
projects = g.projects.list(all=True)
for p in projects:
    p.default=branch = 'develop'
    p.save()
```

I get the following error:
```
Traceback (most recent call last):
  File "./default_branch.py", line 76, in <module>
    p.save()
  File "/usr/local/lib/python2.7/dist-packages/gitlab/mixins.py", line 275, in save
    updated_data = self._get_updated_data()
  File "/usr/local/lib/python2.7/dist-packages/gitlab/mixins.py", line 254, in _get_updated_data
    required, optional = self.manager.get_update_attrs()
AttributeError: 'GroupProjectManager' object has no attribute 'get_update_attrs'
```
