### ISSUE TITLE
gitlab.v4.objects.ProjectJob artifacts fails (no attribute 'get_http')

### ISSUE THREAD

**Issue by mgoodhand** [python-gitlab/python-gitlab#338]
I tried to use the `artifacts()` method on `gitlab.v4.objects.ProjectJob`, but got the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mrg/git/xdash/env/lib/python2.7/site-packages/gitlab/cli.py", line 42, in wrapped_f
    return f(*args, **kwargs)
  File "/Users/mrg/git/xdash/env/lib/python2.7/site-packages/gitlab/exceptions.py", line 231, in wrapped_f
    return f(*args, **kwargs)
  File "/Users/mrg/git/xdash/env/lib/python2.7/site-packages/gitlab/v4/objects.py", line 692, in artifacts
    result = self.manager.gitlab.get_http(path, streamed=streamed,
AttributeError: 'Gitlab' object has no attribute 'get_http'
```

`get_http` should actually be `http_get`.

Looking at the latest code in GitHub, I see that this has already been fixed:

https://github.com/python-gitlab/python-gitlab/commit/bb5a1df9a52c048bf2cb1ab54a4823a3bb57be9b

Raising the bug anyway, FTR, in case anyone else goes searching.

**Comment by gpocentek** [comment]
Hi @mgoodhand 

Are you using the latest version of python-gitlab (1.0.2)?

**Comment by mgoodhand** [comment]
Sorry, should have said. I was on 1.0.0.

I've just upgraded to 1.0.2 and it works as expected. Thanks.
