### ISSUE TITLE
crash while trying to save default branch for a given project

### ISSUE THREAD

**Issue by arnaudgelas** [python-gitlab/python-gitlab#346]
As mentioned in #330, while iterating on group's project, I have tried saving but it crashes:

```
g = gl.groups.get(group_id)
projects = g.projects.list(all=True)
for p in projects:
    p.default=branch = 'develop'
    p.save()
```
I get the following error:

```
Traceback (most recent call last):
  File "./default_branch.py", line 76, in <module>
    p.save()
  File "/usr/local/lib/python2.7/dist-packages/gitlab/mixins.py", line 275, in save
    updated_data = self._get_updated_data()
  File "/usr/local/lib/python2.7/dist-packages/gitlab/mixins.py", line 254, in _get_updated_data
    required, optional = self.manager.get_update_attrs()
AttributeError: 'GroupProjectManager' object has no attribute 'get_update_attrs'
```

**Comment by gpocentek** [comment]
Hi @arnaudgelas,

You hit a python-gitlab problem: `GroupProject` objects should probably not inherit from `Project` because they don't reflect the same API. And thus they should not expose a `save()` method.

That being said, a simple solution is to create lazy `Project` objects in your loop, and use their `save()` method:

```
g = gl.groups.get(group_id)
projects = g.projects.list(all=True)
for group_p in projects:
    p = gl.projects.get(group_p.id, lazy=True)
    p.default_branch = 'develop'
    p.save()
```

Let me know if this works for you.

**Comment by arnaudgelas** [comment]
Hi @gpocentek This solution works fine!
