### ISSUE TITLE
error with trigger_pipeline

### ISSUE THREAD

**Issue by bleuchtang** [python-gitlab/python-gitlab#348]
I try to trigger pipeline with this code:

    gl.auth()
    project = gl.projects.get(1)
    project.trigger_pipeline('master', 'xxx', {'extra_var1': 'foo', 'extra_var2': 'bar'})

But I get this error:

    Traceback (most recent call last):
      File "/[...]/lib/python3.5/site-packages/gitlab/exceptions.py", line 239, in wrapped_f
        return f(*args, **kwargs)
      File "/[...]/lib/python3.5/site-packages/gitlab/v4/objects.py", line 2086, in trigger_pipeline
        self.manager.gitlab.http_post(path, post_data=post_data, **kwargs)
      File "/[...]/lib/python3.5/site-packages/gitlab/__init__.py", line 793, in http_post
        post_data=post_data, files=files, **kwargs)
      File "/[...]/lib/python3.5/site-packages/gitlab/__init__.py", line 700, in http_request
        response_body=result.content) 
    gitlab.exceptions.GitlabHttpError: 404: 404 Not Found
     
    During handling of the above exception, another exception occurred:
     
    Traceback (most recent call last):
      File "api.py", line 39, in <module>
        project.trigger_pipeline(branch, gitlab_token, {'extra_var1': 'foo', 'extra_var2': 'bar'})
      File "[...]/lib/python3.5/site-packages/gitlab/cli.py", line 42, in wrapped_f
        return f(*args, **kwargs)
      File "/[...]/lib/python3.5/site-packages/gitlab/exceptions.py", line 241, in wrapped_f
        raise error(e.error_message, e.response_code, e.response_body)
    gitlab.exceptions.GitlabCreateError: 404: 404 Not Found

BTW the pipeline is triggered on gitlab side. I run gitlab 10.0.1-ce and python-gitlab 1.0.2.

**Comment by gpocentek** [comment]
@bleuchtang Sorry for the late answer.

I've not beene able to reproduce the problem with the following setup:
* python2.7 / python3.6
* gitlab 10.1
* python-gitlab master

Did you have a change to test with a more recent gitlab version since you reported the issue?

Thanks.

**Comment by gpocentek** [comment]
@bleuchtang feel free to reopen the issue if you still have the problem. Thanks.
