### ISSUE TITLE
Regression: AttributeError, while acessing issues in 1.1.0

### ISSUE THREAD

**Issue by max-wittig** [python-gitlab/python-gitlab#388]
For some projects, there seem to be the issue, that you cannot access the issues attribute in version 1.1.0. It worked in version 1.0.2
```python
self.gl_project.issues.list(all=True)
```

This issue is also caused, when just trying to access `gl_project.issues`

**Traceback**:
```
  File "/home/projects/tools/venv/lib/python3.5/site-packages/gitlab/base.py", line 582, in __getattr__
    return self.__dict__['_updated_attrs'][name]
KeyError: 'issues'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/projects/tool/venv/lib/python3.5/site-packages/gitlab/base.py", line 585, in __getattr__
    value = self.__dict__['_attrs'][name]
KeyError: 'issues'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/projects/tool/venv/lib/python3.5/site-packages/gitlab/base.py", line 605, in __getattr__
    return self.__dict__['_parent_attrs'][name]
KeyError: 'issues'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/projects/tool/tool.py", line 193, in <module>
    main()
  File "/home/projects/tool/tool.py", line 144, in main
    g_checker.create_issues()
  File "/home/projects/tool/scanner.py", line 87, in create_issues
    issue_creator.create_issues(issue_list, reopen=True)
  File "/home/projects/tool/tool.py", line 37, in create_issues
    if not self.issue_exists(current_issue):
  File "/home/projects/tool/tool.py", line 65, in issue_exists
    project_issues = self.gl_project.issues.list(all=True)
  File "/home/projects/tool/venv/lib/python3.5/site-packages/gitlab/base.py", line 607, in __getattr__
    raise AttributeError(name)
AttributeError: issues
```

**Comment by gpocentek** [comment]
@max-wittig Thank you for reporting this problem.

I have not been able to reproduce it though. How did you create `self.gl_project`? Is there a chance that the `issues` attribute got deleted at some point?

I've tried to reproduce on gitlab.com and an internal gitlab instance, with python 2.7 and 3.6, everything worked fine.

Could you provide additional information? Thanks.

**Comment by max-wittig** [comment]
The weird thing is that it works with python-gitlab 1.0.2, but breaks in python-gitlab 1.1.0
```python
def issue_exists(self, issue):
        project_issues = self.gl_project.issues.list(all=True)
        if len(project_issues) > 0:
            logging.debug("Project already contains issues. Checking if issue already exists...")
            for current_issue in project_issues:
                if current_issue.title == issue.title:
                    logging.debug("Issue does already exist.")
                    return True
            logging.debug("Issue doesn't exist yet.")
            return False
        else:
            logging.debug("This project has no issues")
            return False
```

gl_project comes from this 

```python
for gl_project in gl_group.projects.list(as_list=False):
```

**Comment by max-wittig** [comment]
Any more info needed here?

**Comment by max-wittig** [comment]
Seems that this happens, when the group functionality is used and projects of a group are shown.

The ProjectIssueManager seems to be missing then.

### python-gitlab version 1.0.2

```
{ '_attrs': { '_links': { 'events': 'http://***/api/v4/projects/12926/events',
                          'issues': 'http://***/api/v4/projects/12926/issues',
                          'labels': 'http://***/api/v4/projects/12926/labels',
                          'members': 'http://***/api/v4/projects/12926/members',
                          'merge_requests': 'http://***/api/v4/projects/12926/merge_requests',
                          'repo_branches': 'http://***/api/v4/projects/12926/repository/branches',
                          'self': 'http://***/api/v4/projects/12926'},
              'archived': False,
              'avatar_url': None,
              'ci_config_path': '',
              'container_registry_enabled': False,
              'created_at': '2017-09-10T19:27:21.030+02:00',
              'creator_id': 11,
              'default_branch': 'master',
              'description': '***',
              'forks_count': 0,
              'http_url_to_repo': 'https://***/***/***.git',
              'id': 12926,
              'import_status': 'none',
              'issues_enabled': True,
              'jobs_enabled': True,
              'last_activity_at': '2017-12-07T17:21:33.909+01:00',
              'lfs_enabled': True,
              'merge_requests_enabled': True,
              'name': '***',
              'name_with_namespace': '***',
              'namespace': { 'full_path': '***',
                             'id': 3259,
                             'kind': 'group',
                             'name': '***',
                             'parent_id': None,
                             'path': '***'},
              'only_allow_merge_if_all_discussions_are_resolved': True,
              'only_allow_merge_if_pipeline_succeeds': True,
              'open_issues_count': 6,
              'path': '***',
              'path_with_namespace': '***/***',
              'printing_merge_request_link_enabled': True,
              'public_jobs': False,
              'request_access_enabled': False,
              'resolve_outdated_diff_discussions': False,
              'shared_runners_enabled': False,
              'shared_with_groups': [],
              'snippets_enabled': False,
              'ssh_url_to_repo': 'git@***:***/***.git',
              'star_count': 0,
              'tag_list': [],
              'visibility': 'internal',
              'web_url': 'https://***/***/***',
              'wiki_enabled': False},
  '_module': <module 'gitlab.v4.objects' from '/home/projects/***/venv/lib/python3.5/site-packages/gitlab/v4/objects.py'>,
  '_parent_attrs': {'group_id': 3259},
  '_updated_attrs': {},
  'accessrequests': <gitlab.v4.objects.ProjectAccessRequestManager object at 0x7f3fa19d0080>,
  'boards': <gitlab.v4.objects.ProjectBoardManager object at 0x7f3fa19d0cf8>,
  'branches': <gitlab.v4.objects.ProjectBranchManager object at 0x7f3fa19d0048>,
  'commits': <gitlab.v4.objects.ProjectCommitManager object at 0x7f3fa19d05f8>,
  'deployments': <gitlab.v4.objects.ProjectDeploymentManager object at 0x7f3fa19d0b70>,
  'environments': <gitlab.v4.objects.ProjectEnvironmentManager object at 0x7f3fa19d0a20>,
  'events': <gitlab.v4.objects.ProjectEventManager object at 0x7f3fa19d06d8>,
  'files': <gitlab.v4.objects.ProjectFileManager object at 0x7f3fa19d07b8>,
  'forks': <gitlab.v4.objects.ProjectForkManager object at 0x7f3fa19d0c88>,
  'hooks': <gitlab.v4.objects.ProjectHookManager object at 0x7f3fa19d09e8>,
  'issues': <gitlab.v4.objects.ProjectIssueManager object at 0x7f3fa19d08d0>,
  'jobs': <gitlab.v4.objects.ProjectJobManager object at 0x7f3fa19d0908>,
  'keys': <gitlab.v4.objects.ProjectKeyManager object at 0x7f3fa19d0390>,
  'labels': <gitlab.v4.objects.ProjectLabelManager object at 0x7f3fa19d03c8>,
  'manager': <gitlab.v4.objects.GroupProjectManager object at 0x7f3fa234aba8>,
  'members': <gitlab.v4.objects.ProjectMemberManager object at 0x7f3fa19d0cc0>,
  'mergerequests': <gitlab.v4.objects.ProjectMergeRequestManager object at 0x7f3fa19d0d68>,
  'milestones': <gitlab.v4.objects.ProjectMilestoneManager object at 0x7f3fa19d0128>,
  'notes': <gitlab.v4.objects.ProjectNoteManager object at 0x7f3fa19d0208>,
  'notificationsettings': <gitlab.v4.objects.ProjectNotificationSettingsManager object at 0x7f3fa19d0198>,
  'pipelines': <gitlab.v4.objects.ProjectPipelineManager object at 0x7f3fa19d0358>,
  'protectedbranches': <gitlab.v4.objects.ProjectProtectedBranchManager object at 0x7f3fa2374b70>,
  'runners': <gitlab.v4.objects.ProjectRunnerManager object at 0x7f3fa2374b00>,
  'services': <gitlab.v4.objects.ProjectServiceManager object at 0x7f3fa2374cc0>,
  'snippets': <gitlab.v4.objects.ProjectSnippetManager object at 0x7f3fa2374d30>,
  'tags': <gitlab.v4.objects.ProjectTagManager object at 0x7f3fa2374208>,
  'triggers': <gitlab.v4.objects.ProjectTriggerManager object at 0x7f3fa2374c88>,
  'variables': <gitlab.v4.objects.ProjectVariableManager object at 0x7f3fa2374320>}
```

### python-gitlab version 1.1.0

```
{ '_attrs': { '_links': { 'events': 'http://***/api/v4/projects/16211/events',
                          'issues': 'http://***/api/v4/projects/16211/issues',
                          'labels': 'http://***/api/v4/projects/16211/labels',
                          'members': 'http://***/api/v4/projects/16211/members',
                          'merge_requests': 'http://***/api/v4/projects/16211/merge_requests',
                          'repo_branches': 'http://***/api/v4/projects/16211/repository/branches',
                          'self': 'http://***/api/v4/projects/16211'},
              'archived': False,
              'avatar_url': None,
              'ci_config_path': '',
              'container_registry_enabled': False,
              'created_at': '2017-11-02T10:26:43.713+01:00',
              'creator_id': 6349,
              'default_branch': 'master',
              'description': "***",
              'forks_count': 0,
              'http_url_to_repo': 'https://***/***/***.git',
              'id': 16211,
              'import_status': 'none',
              'issues_enabled': True,
              'jobs_enabled': True,
              'last_activity_at': '2017-12-01T09:44:54.440+01:00',
              'lfs_enabled': True,
              'merge_requests_enabled': True,
              'name': '***',
              'name_with_namespace': '*** / ***',
              'namespace': { 'full_path': '***',
                             'id': 3259,
                             'kind': 'group',
                             'name': '***',
                             'parent_id': None,
                             'path': '***'},
              'only_allow_merge_if_all_discussions_are_resolved': True,
              'only_allow_merge_if_pipeline_succeeds': True,
              'open_issues_count': 1,
              'path': '***',
              'path_with_namespace': '***/***',
              'printing_merge_request_link_enabled': True,
              'public_jobs': False,
              'request_access_enabled': False,
              'resolve_outdated_diff_discussions': False,
              'shared_runners_enabled': False,
              'shared_with_groups': [],
              'snippets_enabled': False,
              'ssh_url_to_repo': 'git@***:***/***.git',
              'star_count': 0,
              'tag_list': ['python', 'csv', 'ssh', 'users'],
              'visibility': 'internal',
              'web_url': 'https://***/***/***',
              'wiki_enabled': False},
  '_module': <module 'gitlab.v4.objects' from '/home/projects/***/venv/lib/python3.5/site-packages/gitlab/v4/objects.py'>,
  '_parent_attrs': {'group_id': 3259},
  '_updated_attrs': {},
  'manager': <gitlab.v4.objects.GroupProjectManager object at 0x7f600afebac8>}
```

**Comment by gpocentek** [comment]
@max-wittig sorry for the late answer.

So this is actually not a bug but a feature: http://python-gitlab.readthedocs.io/en/stable/release_notes.html#changes-from-1-0-2-to-1-1

This is a choice I made to avoid dealing with some issues: the objects now strictly reflect the GitLab API. So `GroupProject` doesn't implement the same features than `Project`. If you need to get issues related to a `GroupProject`, you have to create a `Project` object first:

```python
group_project = group.projects.list()[0]
issues = gl.projects.get(group_project.id, lazy=True).issues.list()
```

Hope this helps.
