### ISSUE TITLE
Unable to create impersonation tokens in v1.2.0

### ISSUE THREAD

**Issue by rcrelia** [python-gitlab/python-gitlab#418]
Hi,

I want to start managing impersonation tokens in an application that is already leveraging v1.2.0 of python-gitlab for other user/project tasks. 

I verified with the native GitLab API and curl that I can create impersonation tokens for a given user, but when I try to do so with the python-gitlab using the same creds and API v4 like so:

```
gl = gitlab.Gitlab(gl_host, gl_token, gl_api)
user = gl.users.create({'email': myEmail, 'password': myPasswd, 'username': myUser, 'name': myName})
impToken = user.impersonationtokens.create({'name': 'mytoken', 'scopes': ['api']})
```
I only get the user created and an error from the user.impersonationtokens.create call. 

I don't have good insight to the exact error message as it is happening in a serverless context and my logging is still just sucky old print()'s.

Can you confirm that the impersonation token creation method is working for certain in python-gitlab? If so, I'll invest more time in trying to debug further on my end... thank you! 

Rick

**Comment by gpocentek** [comment]
Hi @rcrelia 

Impersonation tokens creation works fine for me.

Your Gitlab instance creation will not work as expected with your example (but maybe it's not exactly what you're using in your application), because you will end up using the v3 API. What you need is `gl = gitlab.Gitlab(gl_host, gl_token, api_version=gl_api)`.

**Comment by rcrelia** [comment]
@gpocentek 

Thanks for that tip. I have api_version=4 set manually now instead of a variable, I think it was falling back to v3 for some reason when that variable was used because I had some other code that was not using v4 syntax and it worked.

I'm still seeing the impersonation token creation error after the change, though. I took some time to add traceback printing to get more information. Do you recognize the possible cause of the AttributeError?

```
Something happened during GitLab user impersonation token creation:

Traceback (most recent call last):
File "/var/task/process1.py", line 124, in mainHndlr
impToken = user.impersonationtokens.create({'name': ‘mytoken', 'scopes': ['api']})
File "/var/task/gitlab/base.py", line 607, in __getattr__
raise AttributeError(name)
AttributeError: impersonationtokens

# which then impacts attempts at using the impToken object like so…

Something happened during update of processing table with new impersonation token: local variable 'impToken' referenced before assignment
```

**Comment by gpocentek** [comment]
Could you print/get the class of the `user` object? One possible reason for the AttributeError exception is that you use an object that is not a `User` instance.

**Comment by rcrelia** [comment]
Yes. Here is the print() of the user object that is created before trying to assign the impersonation token to the user:

```
User object: <class 'gitlab.v4.objects.User'> => {u'two_factor_enabled': False, u'username': u'jsmith', u'theme_id': 1, u'can_create_project': True, u'bio': None, u'confirmed_at': None, u'twitter': u'', u'linkedin': u'', u'color_scheme_id': 1, u'last_sign_in_at': None, u'web_url': u'https://git.foo.com/jsmith', u'last_activity_on': None, u'external': False, u'skype': u'', u'identities': [], u'id': 316, u'name': u'jsmith', u'can_create_group': True, u'projects_limit': 10, u'current_sign_in_at': None, u'created_at': u'2018-01-29T12:43:24.199Z', u'state': u'active', u'avatar_url': u'https://secure.gravatar.com/avatar/ba0ca61b51209ff82cce316d4dcc3e6f?s=80&d=identicon', u'location': None, u'organization': None, u'email': u'jsmith@foo.com', u'website_url': u''}
```

Thank you for your time and assistance!

**Comment by gpocentek** [comment]
Hi @rcrelia 

Everything seems to be OK, I don't understand why this attribute is not available.

At this stage I wonder if your installation of python-gitlab is correct. Is it possible that you're actually running an older version? Could you check the `User` class in `/var/task/gitlab/v4/objects.py` to make sure the `_managers` attribute defines `impersonationtokens`?

**Comment by rcrelia** [comment]
Hmmm ok. Here's that information:

```
[root@ip-172-16-0-61 ~]# less /usr/local/lib/python2.7/site-packages/gitlab/v4/objects.py
[root@ip-172-16-0-61 ~]# grep -A 8 -B 8 impersonationtokens !$
grep -A 8 -B 8 impersonationtokens /usr/local/lib/python2.7/site-packages/gitlab/v4/objects.py


class User(SaveMixin, ObjectDeleteMixin, RESTObject):
    _short_print_attr = 'username'
    _managers = (
        ('customattributes', 'UserCustomAttributeManager'),
        ('emails', 'UserEmailManager'),
        ('gpgkeys', 'UserGPGKeyManager'),
        ('impersonationtokens', 'UserImpersonationTokenManager'),
        ('keys', 'UserKeyManager'),
        ('projects', 'UserProjectManager'),
    )

    @cli.register_custom_action('User')
    @exc.on_http_error(exc.GitlabBlockError)
    def block(self, **kwargs):
        """Block the user.
[root@ip-172-16-0-61 ~]#
```

**Comment by rcrelia** [comment]
Oops, that's the wrong server. The code in question is actually running in a serverless environment, but I'll see what I can do about accessing the local filesystem for a readonly operation of the code.

**Comment by rcrelia** [comment]
Ok, yes confirmed that it includes that:

```
[ seamus | v4 ]$ grep -A 8 -B 8 impersonationtokens objects.py


class User(SaveMixin, ObjectDeleteMixin, RESTObject):
    _short_print_attr = 'username'
    _managers = (
        ('customattributes', 'UserCustomAttributeManager'),
        ('emails', 'UserEmailManager'),
        ('gpgkeys', 'UserGPGKeyManager'),
        ('impersonationtokens', 'UserImpersonationTokenManager'),
        ('keys', 'UserKeyManager'),
        ('projects', 'UserProjectManager'),
    )

    @cli.register_custom_action('User')
    @exc.on_http_error(exc.GitlabBlockError)
    def block(self, **kwargs):
        """Block the user.
```

**Comment by rcrelia** [comment]
@gpocentek 

Here's a script that replicates the error. Hopefully, it will be useful to you. Note that you need to set two env vars, the GL server path and a GL admin token. Following the script, is the output I get from running it. 

```
#!/usr/bin/env python

from __future__ import print_function

import os
import string
import random
import hashlib
from datetime import datetime
import traceback
import gitlab

gl_host = os.environ['gl_host']
gl_token = os.environ['gl_token']

gl = gitlab.Gitlab(gl_host, gl_token, api_version='4')

email = 'jsmith2@gmail.com'
userName = '0123456789ABCD'
groupName = 'jsdev'

try:
    size = 16
    chars = string.ascii_uppercase + string.digits
    passwd = ''.join(random.choice(chars) for _ in range(size))
    user = gl.users.create(
        {'email': email, 'password': passwd, 'username': userName, 'name': userName})
    print("User %s with id %d created..." %
            (user.name, user.id))
    # create project group to set namespace correctly later
    group = gl.groups.create(
        {'name': groupName, 'path': groupName})
    group.description = 'Project for ' + str(groupName)
    group.visibility = 'private'
    group.save()
    # add user to project group
    member = group.members.create({'user_id': user.id, 'access_level': gitlab.DEVELOPER_ACCESS})
except Exception as e:
    raise Exception("Something happened during GitLab user and group creation: %s" % e)

try:
    impToken = user.impersonationtoken.create({'name': 'camtoken', 'scopes': ['api']})
    print("Impersonation token %s created..." % str(impToken.name))
except:
    print("Something happened during GitLab user impersonation token creation")
    traceback.print_exc()

try:
    print("Creating project %s ..." % userName)
    project = gl.projects.create({'name': userName, 'namespace_id': group.id})
    print("Creating %s branch files ..." % 'master')
    readme = project.files.create({'file_path': 'README.md', 'branch': 'master',
                                    'content': '', 'commit_message': 'Initial commit'})
except Exception as projecterr:
    print("Something happened when creating GitLab project: " + str(projecterr))
    traceback.print_exc()
```
and the output:

```
[ seamus | python-gitlab (pygitlab-testing %=) ]$ ./createImpToken.py
User 0123456789ABCD with id 440 created...
Something happened during GitLab user impersonation token creation
Traceback (most recent call last):
  File "./createImpToken.py", line 42, in <module>
    impToken = user.impersonationtoken.create({'name': 'camtoken', 'scopes': ['api']})
  File "/usr/local/lib/python2.7/site-packages/gitlab/base.py", line 607, in __getattr__
    raise AttributeError(name)
AttributeError: impersonationtoken
Creating project 0123456789ABCD ...
Creating master branch files ...
[ seamus | python-gitlab (pygitlab-testing %=) ]$
```

**Comment by rcrelia** [comment]
Good grief... this is embarrassing. I just got this to work by using the correct User attribute:

impToken = user.impersonationtoken**s**.create({'name': 'camtoken', 'scopes': ['api']})

My apologies for not catching this sooner.

**Comment by gpocentek** [comment]
I've spent so many hours dealing with that type of mistakes, this is kind of cool to see I'm not the only one ;)

I'm glad it works now!
