### ISSUE TITLE
__init()__ fails during docker RUN

### ISSUE THREAD

**Issue by knusperkrone** [python-gitlab/python-gitlab#424]
Hey,
First of all I love your library!

I try to prepopulate an gitlab-docker-image with some data for integration testing.
Therefore I extend the originial [docker-ce dockefile](https://hub.docker.com/r/gitlab/gitlab-ce/~/dockerfile/).<br>
What i currently do is ```gitlab-ctl reconfigure```  with the following settings:
```Ruby
# Docker options
# Prevent Postgres from trying to allocate 25% of total memory
postgresql['shared_buffers'] = '1MB'
gitlab_rails['initial_root_password'] = "PASSWORD"
gitlab_rails['gitlab_shell_ssh_port'] = 10022
external_url 'http://127.0.0.1:10080'
```

As I just created this gitlab-instance I have to manually create an private-API-token. I do this with an request session, inspired by your [gist](https://gist.github.com/gpocentek/bd4c3fbf8a6ce226ebddc4aad6b46c0a). I get an error in this line:

```python
GITLAB_URL= http://127.0.0.1:10080 # Should be valid, I used it for the login session before
glab = gitlab.Gitlab(GITLAB_URL, private_token=private_token, api_version=4)
glab.auth()
```
The error message is:
```python
Traceback (most recent call last):
  File "/assets/database_init/main.py", line 44, in <module>
    main()
  File "/assets/database_init/main.py", line 38, in main
    glab = auth.auth()
  File "/assets/database_init/gitlab_module/auth.py", line 46, in auth
    glab.auth()
  File "/usr/local/lib/python3.4/dist-packages/gitlab/__init__.py", line 204, in auth
    self._token_auth()
  File "/usr/local/lib/python3.4/dist-packages/gitlab/__init__.py", line 226, in _token_auth
    self.user = self._objects.CurrentUserManager(self).get()
  File "/usr/local/lib/python3.4/dist-packages/gitlab/exceptions.py", line 247, in wrapped_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/gitlab/mixins.py", line 67, in get
    server_data = self.gitlab.http_get(self.path, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/gitlab/__init__.py", line 721, in http_get
    streamed=streamed, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/gitlab/__init__.py", line 677, in http_request
    files=files, **opts)
TypeError: __init__() got an unexpected keyword argument 'json'
```

This is only during inside of the docker container (RUN/CMD), when I call the same method inside my hosting machine, it works like a charm.

So i am not even sure if this is an issue with your framework, or with docker/gitlab.

**Comment by knusperkrone** [comment]
Was an issue with my installed python libraries. Never mind.
