### ISSUE TITLE
unable to create project in gitlab dynamically

### ISSUE THREAD

**Issue by jaydip189** [python-gitlab/python-gitlab#461]
Create a project:

project = gl.projects.create({'name': 'project1'})

**Comment by jaydip189** [comment]
Traceback (most recent call last):
  File "thread.py", line 33, in <module>
    glab.create_project ( "gitlabproject1" )
  File "thread.py", line 25, in create_project
    return self.gitlab_client.projects.create({'name': 'project1'})
  File "C:\Users\jaydipsinh.jadeja\AppData\Local\Programs\Python\Python36-32\lib\site-packages\gitlab\exceptions.py", line 251, in wrapped_f
    return f(*args, **kwargs)
  File "C:\Users\jaydipsinh.jadeja\AppData\Local\Programs\Python\Python36-32\lib\site-packages\gitlab\mixins.py", line 176, in create
    return self._obj_cls(self, server_data)
  File "C:\Users\jaydipsinh.jadeja\AppData\Local\Programs\Python\Python36-32\lib\site-packages\gitlab\base.py", line 567, in __init__
    self._create_managers()
  File "C:\Users\jaydipsinh.jadeja\AppData\Local\Programs\Python\Python36-32\lib\site-packages\gitlab\base.py", line 632, in _create_managers
    manager = cls(self.manager.gitlab, parent=self)
  File "C:\Users\jaydipsinh.jadeja\AppData\Local\Programs\Python\Python36-32\lib\site-packages\gitlab\base.py", line 754, in __init__
    self._computed_path = self._compute_path()
  File "C:\Users\jaydipsinh.jadeja\AppData\Local\Programs\Python\Python36-32\lib\site-packages\gitlab\base.py", line 768, in _compute_path
    for self_attr, parent_attr in self._from_parent_attrs.items()}
  File "C:\Users\jaydipsinh.jadeja\AppData\Local\Programs\Python\Python36-32\lib\site-packages\gitlab\base.py", line 768, in <dictcomp>
    for self_attr, parent_attr in self._from_parent_attrs.items()}
  File "C:\Users\jaydipsinh.jadeja\AppData\Local\Programs\Python\Python36-32\lib\site-packages\gitlab\base.py", line 585, in __getattr__
    value = self.__dict__['_attrs'][name]
TypeError: list indices must be integers or slices, not str

**Comment by jaydip189** [comment]
used gitlab url https and working fine now.
