### ISSUE TITLE
Cannot create issue

### ISSUE THREAD

**Issue by mjmare** [python-gitlab/python-gitlab#475]
## Description of the problem, including code/CLI snippet

Hi,
I'm trying to add a new issue (based on the example in the docs) with this test script. It fails on the issue creation line with the error below:

```
import gitlab


TOKEN = '<removed>'
TRACKER_ID = <removed>

# private token or personal token authentication
gl = gitlab.Gitlab('http://gitlab.com', private_token=TOKEN)

gl.auth()

project = gl.projects.get(TRACKER_ID)
print(project)

issue = project.issues.create({'title': 'I have a bug', 'description': 'Something useful here.'})

print(issue)
```
This is the error:

```
Traceback (most recent call last):
  File "/Users/mjm/Dropbox/Devel/_Experiments/Gitlab/venv3/lib/python3.6/site-packages/gitlab/base.py", line 582, in __getattr__
    return self.__dict__['_updated_attrs'][name]
KeyError: 'project_id'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/mjm/Applications/PyCharm.app/Contents/helpers/pydev/pydev_run_in_console.py", line 53, in run_file
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Users/mjm/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/mjm/Dropbox/Devel/_Experiments/Gitlab/create_issue.py", line 20, in <module>
    issue = project.issues.create({'title': 'I have a bug', 'description': 'Something useful here.'})
  File "/Users/mjm/Dropbox/Devel/_Experiments/Gitlab/venv3/lib/python3.6/site-packages/gitlab/exceptions.py", line 251, in wrapped_f
    return f(*args, **kwargs)
  File "/Users/mjm/Dropbox/Devel/_Experiments/Gitlab/venv3/lib/python3.6/site-packages/gitlab/mixins.py", line 176, in create
    return self._obj_cls(self, server_data)
  File "/Users/mjm/Dropbox/Devel/_Experiments/Gitlab/venv3/lib/python3.6/site-packages/gitlab/base.py", line 567, in __init__
    self._create_managers()
  File "/Users/mjm/Dropbox/Devel/_Experiments/Gitlab/venv3/lib/python3.6/site-packages/gitlab/base.py", line 632, in _create_managers
    manager = cls(self.manager.gitlab, parent=self)
  File "/Users/mjm/Dropbox/Devel/_Experiments/Gitlab/venv3/lib/python3.6/site-packages/gitlab/base.py", line 754, in __init__
    self._computed_path = self._compute_path()
  File "/Users/mjm/Dropbox/Devel/_Experiments/Gitlab/venv3/lib/python3.6/site-packages/gitlab/base.py", line 768, in _compute_path
    for self_attr, parent_attr in self._from_parent_attrs.items()}
  File "/Users/mjm/Dropbox/Devel/_Experiments/Gitlab/venv3/lib/python3.6/site-packages/gitlab/base.py", line 768, in <dictcomp>
    for self_attr, parent_attr in self._from_parent_attrs.items()}
  File "/Users/mjm/Dropbox/Devel/_Experiments/Gitlab/venv3/lib/python3.6/site-packages/gitlab/base.py", line 585, in __getattr__
    value = self.__dict__['_attrs'][name]
TypeError: list indices must be integers or slices, not str
```
## Expected Behavior
Creation of a new issue

## Specifications

  - python-gitlab version: 1.3.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): gitlab.com
  - python: 3.6

**Comment by gpocentek** [comment]
Hi @mjmare 

I have not been able to reproduce the problem on gitlab.com. Are you using this exact code snippet?

**Comment by mjmare** [comment]
Yes, except that the token and project id are filled in, of course.

**Comment by gpocentek** [comment]
Sorry for this really late answer but I see the problem now: you need to use `https` in the URL, not `http`.

This is an HTTP protocol "feature": when POST request gets a 3xx answer (redirect), the new request is sent without data/body.

Update the URL to `https://gitlab.com` and you should be fine.
