### ISSUE TITLE
py_functional_tests are broken?

### ISSUE THREAD

**Issue by max-wittig** [python-gitlab/python-gitlab#486]
## Description of the problem, including code/CLI snippet
Running this in a python3 venv
```bash
# run the python API tests:
./tools/py_functional_tests.sh
```

yields the following error
```python
TypeError: 'cmp' is an invalid keyword argument for this function
```

---

Even when using the old python2, tests fail, because of many reasons
```python
Traceback (most recent call last):
  File "./tools/python_test_v4.py", line 129, in <module>
    email = new_user.emails.create({'email': 'foo2@bar.com'})
  File "/home/projects/python-gitlab/gitlab/exceptions.py", line 253, in wrapped_f
    raise error(e.error_message, e.response_code, e.response_body)
gitlab.exceptions.GitlabCreateError: 500: 500 Internal Server Error
```

```python
Traceback (most recent call last):
  File "./tools/python_test_v4.py", line 145, in <module>
    {'name': 'token1', 'scopes': ['api', 'read_user']})
  File "/home/projects/python-gitlab/gitlab/exceptions.py", line 253, in wrapped_f
    raise error(e.error_message, e.response_code, e.response_body)
gitlab.exceptions.GitlabCreateError: 400: {"error":"scopes is invalid"}
ERROR: 'python ./tools/python_test_v4.py' failed
```

```python
Traceback (most recent call last):
  File "./tools/python_test_v4.py", line 148, in <module>
    mail = gl.user.emails.create({'email': 'current@user.com'})
  File "/home/projects/python-gitlab/gitlab/exceptions.py", line 253, in wrapped_f
    raise error(e.error_message, e.response_code, e.response_body)
gitlab.exceptions.GitlabCreateError: 500: 500 Internal Server Error
ERROR: 'python ./tools/python_test_v4.py' failed
```

....

Are these tests maintained or what am I doing wrong here?

## Expected Behavior
Tests run through for the latest master

## Actual Behavior
See above

## Specifications

  - python-gitlab version: latest master (1.3.0+)
  - API version you are using (v3/v4): v3+v4
  - Gitlab server version (or gitlab.com): localhost (tests)

**Comment by max-wittig** [comment]
Honestly I'm not sure why these tests pass in the CI.

They still don't work for me. Also it looks like they are still python2 only.

**Comment by gpocentek** [comment]
You can run the tests using python3 with the `-a 3` option.

Are you sure you use the latest version of the docker image?

**Comment by max-wittig** [comment]
I think python_test_v4.py is just not compatible with python3

In python3, you would use `key` instead of `cmp` I think
```python3
usercmp = lambda x,y: cmp(x.id, y.id)
expected = sorted([new_user, foobar_user], cmp=usercmp)
actual = sorted(list(gl.users.list(search='foo')), cmp=usercmp)
```

**Comment by gpocentek** [comment]
Oh I see now. Will have a look at that. Thank you.

**Comment by max-wittig** [comment]
Also this still fails sometimes for some reason and the GitLab version in the test image is a little old.
```python
Traceback (most recent call last):
  File "./tools/python_test_v4.py", line 129, in <module>
    email = new_user.emails.create({'email': 'foo2@bar.com'})
  File "/home/projects/python-gitlab/gitlab/exceptions.py", line 253, in wrapped_f
    raise error(e.error_message, e.response_code, e.response_body)
gitlab.exceptions.GitlabCreateError: 500: 500 Internal Server Error
```
