### ISSUE TITLE
User has no attribute `save`

### ISSUE THREAD

**Issue by peircej** [python-gitlab/python-gitlab#547]
## Description of the problem, including code/CLI snippet
```
session = gitlab.Gitlab(url=gitlabRepo, oauth_token=myToken)
session.auth()
user = session.user
print(session.user.username)  # this is fine
user.bio = 'test1'
user.save()
```

## Expected Behavior

user bio is updated to "test"

## Actual Behavior

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gitlab/base.py", line 582, in __getattr__
    return self.__dict__['_updated_attrs'][name]
KeyError: 'save'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gitlab/base.py", line 585, in __getattr__
    value = self.__dict__['_attrs'][name]
KeyError: 'save'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gitlab/base.py", line 605, in __getattr__
    return self.__dict__['_parent_attrs'][name]
KeyError: 'save'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lpzjwp/Dropbox/psychopyStuff/gitlabSetUserStuff.py", line 10, in <module>
    user.save()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gitlab/base.py", line 607, in __getattr__
    raise AttributeError(name)
AttributeError: save

```

## Specifications

  - python-gitlab version: 1.3.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 11.0.2-ee

**Comment by gpocentek** [comment]
Hi @peircej 

This is expected. The `CurrentUser` object is read-only (this comes from the GitLab API: https://docs.gitlab.com/ce/api/users.html#user). To modify a user you need to create a `User` object. For example in your context:

```python
# lazy=False avoids a new API call
editable_user = session.users.get(session.user.id, lazy=False)
editable_user.bio = 'test1'
editable_user.save()
```

**Comment by peircej** [comment]
Thanks for the info. Seems like a funny design decision -(by gitlab, not you). You would have though that the current user should be editable, maybe the *only* user that should be editable!

It looks like only admin users can edit users in this case (making the facility a bit pointless for me). I want the user to be able to update their profile from within my desktop app, but I guess not.

Thanks though for your quick response and for your work on gitlab-python. It's proving very useful for me.
