### ISSUE TITLE
"project-job trace" print nothing

### ISSUE THREAD

**Issue by liaoya** [python-gitlab/python-gitlab#548]
## Description of the problem, including code/CLI snippet
Gitlab API provide trace endpoint for job (https://docs.gitlab.com/ee/api/jobs.html). I find I run `gitlab project-job trace --project-id 5623 --id 872795` and nothing return. But when I run `curl -X GET -sL --header "PRIVATE-TOKEN: xxxxxx" "https://xxx.xxxx.com/api/v4/projects/5623/jobs/860966/trace"`, I can find the output

## Expected Behavior
`gitlab project-job trace` should output the trace

## Actual Behavior
`gitlab project-job trace` should does not show the trace

## Specifications

  - python-gitlab version: 1.5.11
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): {"version":"10.6.3","revision":"753d851"}

## Some investigation
I dig the code and find the root cause, `gitlab.v4.cli.run` method only handle four type and has no else statement. 

```python
def run(gl, what, action, args, verbose, output, fields):
    g_cli = GitlabCLI(gl, what, action, args)
    data = g_cli()

    printer = PRINTERS[output]()

    if isinstance(data, dict):
        printer.display(data, verbose=True, obj=data)
    elif isinstance(data, list):
        printer.display_list(data, fields, verbose=verbose)
    elif isinstance(data, gitlab.base.RESTObject):
        printer.display(get_dict(data, fields), verbose=verbose, obj=data)
    elif isinstance(data, six.string_types):
        print(data)
```

But `ProjectJob.trace()` return bytes (<class 'bytes'>), so display operation. And `requests.Response.content` is bytes and `requests.Response.text` is unicode. `project-job trace` is a little special, it does not a file downloadable or a json string as most of gitlab API does.

**Comment by liaoya** [comment]
I really appreciate your python-gitlab, this is the best gitlab client I found.

**Comment by liaoya** [comment]
I have verified your fix and it's correct for gitlab project-job trace

**Comment by liaoya** [comment]
@gpocentek You fix has some issue. I use your fix and I find the following error when run `gitlab project-branch delete`

```bash
gitlab project-branch delete  --project-id (urlencode thunderbird/smi/openid) --name deploy
Traceback (most recent call last):
  File "/opt/vpy2/bin/gitlab", line 11, in <module>
    sys.exit(main())
  File "/opt/vpy2/local/lib/python2.7/site-packages/gitlab/cli.py", line 179, in main
    cli_module.run(gl, what, action, args, verbose, output, fields)
  File "/opt/vpy2/local/lib/python2.7/site-packages/gitlab/v4/cli.py", line 370, in run
    print(data.decode())
AttributeError: 'NoneType' object has no attribute 'decode'
```
Please add None check in the code.

**Comment by gpocentek** [comment]
Hi @liaoya 

This should be fixed in commit a139179ea. Can you check with the current master?

Thanks!

**Comment by liaoya** [comment]
Yes, that code is better.
