### ISSUE TITLE
Any project download result: gitlab.exceptions.GitlabCreateError: 404: b'{"error":"404 Not Found"}' 

### ISSUE THREAD

**Issue by fanghuafan** [python-gitlab/python-gitlab#556]
## Description of the problem, including code/CLI snippet
```
#!/usr/bin/python
# -*- coding: UTF-8 -*-

import gitlab

def auth():
    gl = gitlab.Gitlab('http://', private_token='')
    gl.auth()

    return gl

def project_list():
    gl = auth()
    projects = gl.projects.list(all=True)
    if(projects != None):
        for project in projects:
            download_project(gl, project)

def download_project(gl, p):
    export = p.exports.create({})

    # Wait for the 'finished' status
    export.refresh()
    while export.export_status != 'finished':
        time.sleep(1)
        export.refresh()

    # Download the result
    with open('C://', 'wb') as f:
       export.download(streamed=True, action=f.write)

project_list()
```

## Expected Behavior
Download project.

## Actual Behavior
Any project get result:

```
Traceback (most recent call last):
  File "e:\source\python\download_gitlab\download_project.py", line 32, in <module>
    project_list()
  File "e:\source\python\download_gitlab\download_project.py", line 17, in project_list
    download_project(gl, project)
  File "e:\source\python\download_gitlab\download_project.py", line 20, in download_project
    export = p.exports.create({})
  File "C:\Users\jack_fan\AppData\Local\Programs\Python\Python37\lib\site-packages\gitlab\exceptions.py", line 244, in wrapped_f
    raise error(e.error_message, e.response_code, e.response_body)
gitlab.exceptions.GitlabCreateError: 404: b'{"error":"404 Not Found"}'
```

## Specifications

  - python-gitlab version:  GitLab Community Edition 9.4.5
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com):  

Thanks for your help!

**Comment by gpocentek** [comment]
Hello @fanghuafan 

You are using a version of GitLab that doesn't support import/export. You need at least GitLab 10.6 (https://docs.gitlab.com/ee/api/project_import_export.html).

**Comment by fanghuafan** [comment]
Thanks……
