### ISSUE TITLE
Create wiki page fails

### ISSUE THREAD

**Issue by FranzForstmayr** [python-gitlab/python-gitlab#565]
## Description of the problem, including code/CLI snippet
Creating a wiki page fails with a TypeError. When i omit content, i get a warning about missing content.

## Expected Behavior
Create a Wikipage :)

## Actual Behavior
```
Traceback (most recent call last):
  File "/home/franz/.local/lib/python3.6/site-packages/gitlab/base.py", line 56, in __getattr__
    return self.__dict__['_updated_attrs'][name]
KeyError: '_managers'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "py-gitlab.py", line 13, in <module>
    page = project.wikis.create({'title': 'Wiki Page 1', "id" : 1, "content" : "Test123#"})
  File "/home/franz/.local/lib/python3.6/site-packages/gitlab/exceptions.py", line 242, in wrapped_f
    return f(*args, **kwargs)
  File "/home/franz/.local/lib/python3.6/site-packages/gitlab/mixins.py", line 205, in create
    return self._obj_cls(self, server_data)
  File "/home/franz/.local/lib/python3.6/site-packages/gitlab/base.py", line 41, in __init__
    self._create_managers()
  File "/home/franz/.local/lib/python3.6/site-packages/gitlab/base.py", line 100, in _create_managers
    managers = getattr(self, '_managers', None)
  File "/home/franz/.local/lib/python3.6/site-packages/gitlab/base.py", line 59, in __getattr__
    value = self.__dict__['_attrs'][name]
TypeError: list indices must be integers or slices, not str

```

## Specifications

  - python-gitlab version: 1.5.1
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): sorry, i don't know. But basic communication with server works. Also getting wiki pages from server

**Comment by gpocentek** [comment]
Hi @FranzForstmayr 

I've not been able to reproduce the problem here. Could you provide a sample code that I could try?

You can use `gl.version()` to get the gitlab server version.

If your server uses https, can you make sure that you are also using it in your python-gitlab configuration?

Thanks.

**Comment by FranzForstmayr** [comment]
Ok, gl.version() returns 10.8.6
I should mention, that i'm using `ssl_verify=false`, if this is a problem.

**Comment by gpocentek** [comment]
`ssl_verify=false` but you still should still use `https://`in the URL configuration is SSL/TLS is enabled on  the server side.

**Comment by FranzForstmayr** [comment]
ok, this resolved my issue. However, deleting a page was working even without the https, so i didn't thought further about the ssl/tls things. Maybe a more precise error would be nice too.
