### ISSUE TITLE
Notes API doesn't work

### ISSUE THREAD

**Issue by jtrees** [python-gitlab/python-gitlab#567]
## Description of the problem, including code/CLI snippet

The notes api doesn't work.

```python
import gitlab

gl = gitlab.Gitlab('https://example.com', private_token='123isnotarealaccesstoken')

issues = gl.issues.list()

for issue in issues:
  notes_count = issue.attributes['user_notes_count']
  if notes_count > 0:
    issue.notes # <-- This doesn't work.
```

Traceback:

```
Traceback (most recent call last):
  File "/home/johndoe/.local/share/virtualenvs/foo/lib/python3.5/site-packages/gitlab/base.py", line 56, in __getattr__
    return self.__dict__['_updated_attrs'][name]
KeyError: 'notes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/johndoe/.local/share/virtualenvs/foo/lib/python3.5/site-packages/gitlab/base.py", line 59, in __getattr__
    value = self.__dict__['_attrs'][name]
KeyError: 'notes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/johndoe/.local/share/virtualenvs/foo/lib/python3.5/site-packages/gitlab/base.py", line 79, in __getattr__
    return self.__dict__['_parent_attrs'][name]
KeyError: 'notes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 17, in <module>
    issue.notes
  File "/home/johndoe/.local/share/virtualenvs/foo/lib/python3.5/site-packages/gitlab/base.py", line 83, in __getattr__
    raise AttributeError(name)
AttributeError: notes
```

## Expected Behavior

It should be possible to access an issue's notes.

## Actual Behavior

Calling `notes` on an issue leads to an error.

## Specifications

  - python-gitlab version: 1.5.1
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 11.0.4

**Comment by gpocentek** [comment]
Hi @jtrees 

`Issue` objects retrieved with `gl.issues.list()` don't have a `notes` manager. This reflects the GitLab API.

You need to create a `ProjectIssue` object to access its `notes` manager:

```
for issue in issues:
    project_issue = gl.projects.get(issue.project_id, lazy=True).issues.get(issue.iid, lazy=True)
    project_issue.notes  # now this works
```
The `lazy` avoid making extra calls to the API.

**Comment by jtrees** [comment]
Sweet. Thanks for this. Perhaps you could make this a bit clearer in the docs?
