### ISSUE TITLE
Initial setup issues

### ISSUE THREAD

**Issue by nwhobart** [python-gitlab/python-gitlab#570]
## Description of the problem, including code/CLI snippet
Cannot connect to gitlab server for initial setup
```
[global]
default = http://git.blah.com
private_token = the_right_token
api_version = 4
```

## Expected Behavior
`gitlab project list` to not error out

## Actual Behavior
```
Traceback (most recent call last):
  File "/usr/local/bin/gitlab", line 9, in <module>
    load_entry_point('python-gitlab==1.5.1', 'console_scripts', 'gitlab')()
  File "/Library/Python/2.7/site-packages/gitlab/cli.py", line 144, in main
    options.config_file)
  File "/Library/Python/2.7/site-packages/gitlab/config.py", line 58, in __init__
    "configuration (%s)" % self.gitlab_id)
gitlab.config.GitlabDataError: Impossible to get gitlab informations from configuration (http://git.blah.com)
```

## Specifications

  - python-gitlab version: `1.5.1`
  - API version you are using (v3/v4): `v4`
  - Gitlab server version (or gitlab.com): `10.5.2-ee`

**Comment by gpocentek** [comment]
Hi @hobakill 

The syntax of your configuration file is not valid, it should be something like this:

```
[global]
default = blah

[blah]
url = http://git.blah.com
private_token = the_right_token
api_version = 4
```
