### ISSUE TITLE
docs example for create issue

### ISSUE THREAD

**Issue by yamagoya** [python-gitlab/python-gitlab#580]
The following code, based on the documentation at:
  https://python-gitlab.readthedocs.io/en/stable/gl_objects/issues.html 
fails with an exception and stack trace:

    import gitlab, os
    token = os.environ['TOKEN']
    gl = gitlab.Gitlab('http://gitlab.com', private_token=token)
    p = gl.projects.get('yamagoya/iss')
    p.issues.create (
        {'title': 'I have a bug',
         'description': 'Something useful here.'})

    Traceback (most recent call last):
      File "/home/stuart/.local/lib/python3.6/site-packages/gitlab/base.py", line 56, in __getattr__
        return self.__dict__['_updated_attrs'][name]
    KeyError: 'project_id'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "xx.py", line 7, in <module>
        'description': 'Something useful here.'})
      File "/home/stuart/.local/lib/python3.6/site-packages/gitlab/exceptions.py", line 246, in wrapped_f
        return f(*args, **kwargs)
      File "/home/stuart/.local/lib/python3.6/site-packages/gitlab/mixins.py", line 205, in create
        return self._obj_cls(self, server_data)
      File "/home/stuart/.local/lib/python3.6/site-packages/gitlab/base.py", line 41, in __init__
        self._create_managers()
      File "/home/stuart/.local/lib/python3.6/site-packages/gitlab/base.py", line 106, in _create_managers
        manager = cls(self.manager.gitlab, parent=self)
      File "/home/stuart/.local/lib/python3.6/site-packages/gitlab/base.py", line 228, in __init__
        self._computed_path = self._compute_path()
      File "/home/stuart/.local/lib/python3.6/site-packages/gitlab/base.py", line 242, in _compute_path
        for self_attr, parent_attr in self._from_parent_attrs.items()}
      File "/home/stuart/.local/lib/python3.6/site-packages/gitlab/base.py", line 242, in <dictcomp>
        for self_attr, parent_attr in self._from_parent_attrs.items()}
      File "/home/stuart/.local/lib/python3.6/site-packages/gitlab/base.py", line 59, in __getattr__
        value = self.__dict__['_attrs'][name]
    TypeError: list indices must be integers or slices, not str

I am not sure if I understood the docs correctly or am doing something wrong.

  - python-gitlab version: 1.6.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): gitlab.com

**Comment by Nothing4You** [comment]
For `gl.projects.get()` you have to pass a project id, not the project path.
If you look at https://gitlab.com/yamagoya/iss/edit in the General Project area you should see your project id.

Also, you should use https to access the API, otherwise your API key may be read by others.

**Comment by gpocentek** [comment]
@yamagoya 

The URL should be 'https://gitlab.com' (explicitly set `https`).

@Nothing4You it's actually possible to use the project path.

**Comment by yamagoya** [comment]
@gpocentek, thank you, using "https" rather than "http" in the url does indeed fix the problem.  But I did a quick scan of the docs and I didn't notice anything that would have told me that.  Did I miss something?  And I don't think I need to point out the the error raised could be clearer.  No intent to be critical -- just wondering if some changes might save future users some time and pain.  Thanks for the help.

@Nothing4You , thanks for the reminder about the security point -- you are of course correct.

**Comment by gpocentek** [comment]
@yamagoya I've added some notes in the docs, and fixed the check that should raise an explicit exception in case of http/https problems. It will be part of the 1.6.1 release.
