### ISSUE TITLE
gitlab project-tag set-release-notes always fails

### ISSUE THREAD

**Issue by nvgoldin** [python-gitlab/python-gitlab#590]
## Description of the problem, including code/CLI snippet
gitlab project-tag set-release-notes always fails:

Using the CLI:
```shell
gitlab project-tag set-release-description --project-id 53 --name 0.4.0 --description "test"
Traceback (most recent call last):
  File "/home/ngoldin/virtualenv/gitlab/bin/gitlab", line 11, in <module>
    sys.exit(main())
  File "/home/ngoldin/virtualenv/gitlab/local/lib/python2.7/site-packages/gitlab/cli.py", line 179, in main
    cli_module.run(gl, what, action, args, verbose, output, fields)
  File "/home/ngoldin/virtualenv/gitlab/local/lib/python2.7/site-packages/gitlab/v4/cli.py", line 379, in run
    data = g_cli()
  File "/home/ngoldin/virtualenv/gitlab/local/lib/python2.7/site-packages/gitlab/v4/cli.py", line 69, in __call__
    return self.do_custom()
  File "/home/ngoldin/virtualenv/gitlab/local/lib/python2.7/site-packages/gitlab/v4/cli.py", line 84, in do_custom
    return getattr(o, method_name)(**self.args)
  File "/home/ngoldin/virtualenv/gitlab/local/lib/python2.7/site-packages/gitlab/cli.py", line 42, in wrapped_f
    return f(*args, **kwargs)
  File "/home/ngoldin/virtualenv/gitlab/local/lib/python2.7/site-packages/gitlab/v4/objects.py", line 1944, in set_release_description
    if self.release is None:
  File "/home/ngoldin/virtualenv/gitlab/local/lib/python2.7/site-packages/gitlab/base.py", line 81, in __getattr__
    raise AttributeError(name)
AttributeError: release
```

## Expected Behavior
Setting the release notes.

## Actual Behavior
Exception is thrown

Note I did the save with python (by fetching the Tag and calling set_release_notes method) and it works.
Did I get something wrong in the CLI?

## Specifications

  - python-gitlab version:1.6.0
  - API version you are using (v3/v4):4
  - Gitlab server version (or gitlab.com): 11.2.3-ee

**Comment by gpocentek** [comment]
Hi @nvgoldin 

The CLI is less tested than the python API so it is highly possible that there is a bug there.

**Comment by nejch** [comment]
Closing as this API has been deprecated for a while in GitLab.

https://docs.gitlab.com/ee/api/tags.html

The new API for this is:
https://docs.gitlab.com/ee/api/releases/#update-a-release

See https://python-gitlab.readthedocs.io/en/latest/cli-objects.html#gitlab-project-release-update for the CLI docs.
