### ISSUE TITLE
Gitlab CLI did not generate Json output

### ISSUE THREAD

**Issue by vikramuk** [python-gitlab/python-gitlab#631]
## Description of the problem, including code/CLI snippet
Gitlab CLI option flag -o Json is broken
https://python-gitlab.readthedocs.io/en/stable/cli.html#cli

--output, -o
Output format. Defaults to a custom format. Can also be yaml or json.

## Expected Behavior
Expect listed attributes to be in Json format

## Actual Behavior
Observed only yaml format is displayed

## Specifications

  - python-gitlab version:1.6
  - API version you are using (v3/v4):v4
  - Gitlab server version (or gitlab.com):11.3.4

**Comment by max-wittig** [comment]
Thanks for your issue. We will look at this soon.

**Comment by vikramuk** [comment]
Hi,
  we were testing the Scripts to generate the python-gitlab list of Projects on Gitlab CE 11.3.4 version.

```
Command:
gitlab -o json -f id,description -g SOURCE  -c /home/user/Scripts/python-gitlab.cfg project list  --all >ProjectList.txt &

```
```
[user@ip-10-106-133-48 Scripts]$ gitlab -o json -f id,description -g Destination  -c /home/user/Scripts/python-gitlab.cfg project list
Traceback (most recent call last):
  File "/usr/local/bin/gitlab", line 11, in <module>
    load_entry_point('python-gitlab==1.6.0', 'console_scripts', 'gitlab')()
  File "build/bdist.linux-x86_64/egg/gitlab/cli.py", line 144, in main
  File "build/bdist.linux-x86_64/egg/gitlab/config.py", line 58, in __init__
gitlab.config.GitlabDataError: Impossible to get gitlab informations from configuration (Destination)
[user@ip-10-106-133-48 Scripts]$
```

**Comment by gpocentek** [comment]
So the problem comes from you configuration file, something is not correctly setup. Have a look at the docs: https://python-gitlab.readthedocs.io/en/stable/cli.html#content

**Comment by vikramuk** [comment]
Configuration was correct. The -o switch/flag for Json did not generate Json.
We received values with "u'" indicating yaml.

**Comment by gpocentek** [comment]
Having `u` in the output doesn't mean that it's yaml. Could you provide a sample output?
