### ISSUE TITLE
Object of type 'GitlabGetError' is not JSON serializable

### ISSUE THREAD

**Issue by spring-bu** [python-gitlab/python-gitlab#674]
## Description of the problem, including code/CLI snippet

```
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/celery/app/trace.py", line 439, in trace_task
    parent_id=uuid, root_id=root_id,
  File "/usr/local/python3/lib/python3.6/site-packages/celery/canvas.py", line 218, in apply_async
    return _apply(args, kwargs, **options)
  File "/usr/local/python3/lib/python3.6/site-packages/celery/app/task.py", line 535, in apply_async
    **options
  File "/usr/local/python3/lib/python3.6/site-packages/celery/app/base.py", line 745, in send_task
    amqp.send_task_message(P, name, message, **options)
  File "/usr/local/python3/lib/python3.6/site-packages/celery/app/amqp.py", line 552, in send_task_message
    **properties
  File "/usr/local/python3/lib/python3.6/site-packages/kombu/messaging.py", line 169, in publish
    compression, headers)
  File "/usr/local/python3/lib/python3.6/site-packages/kombu/messaging.py", line 252, in _prepare
    body) = dumps(body, serializer=serializer)
  File "/usr/local/python3/lib/python3.6/site-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/usr/local/python3/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/python3/lib/python3.6/site-packages/kombu/serialization.py", line 54, in _reraise_errors
    reraise(wrapper, wrapper(exc), sys.exc_info()[2])
  File "/usr/local/python3/lib/python3.6/site-packages/vine/five.py", line 178, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/python3/lib/python3.6/site-packages/kombu/serialization.py", line 50, in _reraise_errors
    yield
  File "/usr/local/python3/lib/python3.6/site-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/usr/local/python3/lib/python3.6/site-packages/kombu/utils/json.py", line 69, in dumps
    **dict(default_kwargs, **kwargs))
  File "/usr/local/python3/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/python3/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/python3/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/python3/lib/python3.6/site-packages/kombu/utils/json.py", line 59, in default
    return super(JSONEncoder, self).default(o)
  File "/usr/local/python3/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
kombu.exceptions.EncodeError: Object of type 'GitlabGetError' is not JSON serializable
```

## Specifications

  - python-gitlab version:
1.7.0

  - API version you are using (v3/v4):
 v4

  - Gitlab server version (or gitlab.com):
10.3.5

**Comment by gpocentek** [comment]
Please provide more information about your problem, the trace is unusable.
