### ISSUE TITLE
Merge Request approvals failing on get() with 404

### ISSUE THREAD

**Issue by NaffanDroo** [python-gitlab/python-gitlab#675]
## Description of the problem, including code/CLI snippet
404 error with merge request approval get()

```p_mras = project.approvals.get()```

## Expected Behavior
Returned object that I can interact with as suggested here: https://python-gitlab.readthedocs.io/en/stable/gl_objects/mr_approvals.html

## Actual Behavior
  File "/Users/.../Library/Python/3.6/lib/python/site-packages/gitlab/exceptions.py", line 251, in wrapped_f
    return f(*args, **kwargs)
  File "/Users/.../Library/Python/3.6/lib/python/site-packages/gitlab/mixins.py", line 68, in get
    server_data = self.gitlab.http_get(self.path, **kwargs)
  File "/Users/.../Library/Python/3.6/lib/python/site-packages/gitlab/__init__.py", line 532, in http_get
    streamed=streamed, **kwargs)
  File "/Users/.../Library/Python/3.6/lib/python/site-packages/gitlab/__init__.py", line 510, in http_request
    response_body=result.content)
gitlab.exceptions.GitlabHttpError: 404: 404 Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./setup-project.py", line 67, in <module>
    p_mras = project.approvals.get()
  File "/Users/.../Library/Python/3.6/lib/python/site-packages/gitlab/exceptions.py", line 253, in wrapped_f
    raise error(e.error_message, e.response_code, e.response_body)
gitlab.exceptions.GitlabGetError: 404: 404 Not Found

## Specifications

  - python-gitlab version: 1.7.0
  - API version you are using (v3/v4): v4 I think
  - Gitlab server version (or gitlab.com): gitlab/gitlab-ee:10.2.4-ee.0

**Comment by NaffanDroo** [comment]
We did upgrade gitlab to a 11.x version and this is no longer a problem it seems...

**Comment by max-wittig** [comment]
I don't think that we should support versions that are not supported by GitLab itself.
10.x is really old and has a lot of security holes. No one should use it.
