### ISSUE TITLE
docker image using yaml config

### ISSUE THREAD

**Issue by AkhilaDamera** [python-gitlab/python-gitlab#679]
## I have below Dockerfile:
I am using yaml config instead of cfg in the dockerfile as below 

_FROM python:slim
RUN pip install --upgrade python-gitlab
# Copy config file
COPY python-gitlab.yml /
ENTRYPOINT ["gitlab", "--config-file", "/python-gitlab.yml"]_

I am getting the parser error within gitlab packages..can i use yaml as config for the dockerfile or it should be cfg format?

Error:
Traceback (most recent call last):
  File "/usr/local/bin/gitlab", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/gitlab/cli.py", line 150, in main
    options.config_file
  File "/usr/local/lib/python3.7/site-packages/gitlab/config.py", line 62, in __init__
    self._config.read(_files)
  File "/usr/local/lib/python3.7/configparser.py", line 696, in read
    self._read(fp, filename)
  File "/usr/local/lib/python3.7/configparser.py", line 1079, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: '/python-gitlab.yml', line: 1
'global:\n'

## Specifications

  - python-gitlab version: 1.7.0
  - API version you are using (v3/v4): v4
 
Thanks,
Akhila

**Comment by max-wittig** [comment]
Currently we only support the .cfg format. If you want to add the yaml format as config file, I would be happy to review your PR.
