### ISSUE TITLE
Merge request approval API missing attributes

### ISSUE THREAD

**Issue by MMollyy** [python-gitlab/python-gitlab#691]
## Description of the problem, including code/CLI snippet
Trying to change values for two project attributes, but these attributes aren't showing up.

Missing attributes:
reset_approvals_on_push | boolean | no | Reset approvals on a new push
disable_overriding_approvers_per_merge_request | boolean | no | Allow/Disallow overriding approvers per MR

code snippet, see actual behaviour for output:
```
gitlab = Gitlab(GITLAB_URL, GITLAB_TOKEN, api_version=GITLAB_API_VERSION)

projects=gitlab.projects.list(all=True)
projects[1].attributes
```

## Expected Behavior
To retrieve the attributes just like I can for:
approvals_before_merge | integer | no | How many approvals are required before an MR can be merged

Which is from the same API

## Actual Behavior
```
{u'lfs_enabled': True, u'request_access_enabled': False, u'approvals_before_merge': 2, u'forks_count': 0, u'only_allow_merge_if_all_discussions_are_resolved': False, u'http_url_to_repo': u'https://url.com/namespace/name.git', u'web_url': u'https://url.com/namespace/name', u'mirror': False, u'wiki_enabled': True, u'id': 1236, u'shared_with_groups': [], u'archived': False, u'snippets_enabled': True, u'merge_method': u'merge', u'description': None, u'namespace': {u'kind': u'group', u'name': u'namespace', u'parent_id': None, u'path': u'namespace', u'id': 136, u'full_path': u'namespace'}, u'star_count': 0, u'avatar_url': None, u'_links': {u'repo_branches': u'https://url.com/api/v4/projects/1236/repository/branches', u'merge_requests': u'https://url.com/api/v4/projects/1236/merge_requests', u'self': u'https://url.com/api/v4/projects/1236', u'labels': u'https://url.com/api/v4/projects/1236/labels', u'members': u'https://url.com/api/v4/projects/1236/members', u'events': u'https://url.com/api/v4/projects/1236/events', u'issues': u'https://url.com/api/v4/projects/1236/issues'}, u'resolve_outdated_diff_discussions': False, u'issues_enabled': True, u'path_with_namespace': u'namespace/name', u'repository_storage': u'default', u'ci_config_path': None, u'merge_requests_enabled': True, u'default_branch': u'master', u'visibility': u'private', u'readme_url': u'https://url.com/namespace/name/blob/master/README.rst', u'ssh_url_to_repo': u'ssh://git@url.com:2240/namespace/name.git', u'public_jobs':
True, u'path': u'name', u'import_status': u'none', u'only_allow_merge_if_pipeline_succeeds': False, u'open_issues_count': 0, u'last_activity_at': u'2019-01-24T11:29:43.614Z', u'name': u'name', u'printing_merge_request_link_enabled': True, u'name_with_namespace': u'namespace/name', u'created_at': u'2018-04-23T11:31:09.213Z', u'creator_id': 1, u'shared_runners_enabled': True, u'container_registry_enabled': True, u'permissions': {u'group_access': {u'notification_level': #, u'access_level': ##}, u'project_access': None}, u'tag_list': [], u'jobs_enabled': True}
```
```
projects[1].reset_approvals_on_push
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\python\pythonpipenv\.venv\lib\site-packages\gitlab\base.py", line 81, in __getattr__
    raise AttributeError(name)
AttributeError: reset_approvals_on_push
```
Same error for: disable_overriding_approvers_per_merge_request

## Specifications

  - python-gitlab version: 1.7.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 11.4.13-ee (c161d18)

Maybe I'm doing something wrong, or completely looking over the value. I'm a total beginner so I would expect it to happen. :)

**Comment by gpocentek** [comment]
Hi @MMollyy 

You can update the attributes even if they are not available in the objects. This should work just fine:

```python
projects = gitlab.projects.list(all=True)
projects[1].approvals_before_merge = 2
projects[1].save()
```

**Comment by MMollyy** [comment]
Hi @gpocentek 

That's what I'm saying: 
"approvals_before_merge" attribute works.

The other two however don't:
```
>>> projects[1].reset_approvals_on_push
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\users\moll\onedrive\documenten\repositories\enexis\python\pythonpipenv\.venv\lib\site-packages\gitlab\base.py", line 81, in __getattr__
    raise AttributeError(name)
AttributeError: reset_approvals_on_push

reset_approvals_on_push

>>> projects[1].disable_overriding_approvers_per_merge_request
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\users\moll\onedrive\documenten\repositories\enexis\python\pythonpipenv\.venv\lib\site-packages\gitlab\base.py", line 81, in __getattr__
    raise AttributeError(name)
AttributeError: disable_overriding_approvers_per_merge_request

disable_overriding_approvers_per_merge_request
```

Maybe I should have included those two errors to begin with :)

**Comment by gpocentek** [comment]
It look like the GitLab documentation is not correct.

We have examples in the python-gitlab docs: https://python-gitlab.readthedocs.io/en/stable/gl_objects/mr_approvals.html

**Comment by hvithval** [comment]
@gpocentek it would be better to add more examples to the python-gitlab, because what you have right now is not 100% clear.
