### ISSUE TITLE
pip install fails with UnicodeDecodeError: 'gbk' codec can't decode byte 0xa2 in position 202: illegal multibyte sequence

### ISSUE THREAD

**Issue by Iarcky** [python-gitlab/python-gitlab#692]
I used `pip install gitlab` failed.

```sh
PS J:\webhook> pip3 install gitlab
Collecting gitlab
  Using cached https://files.pythonhosted.org/packages/ad/c5/91cb054390cafd6739eab83dfb5d739b699f10b4ff139602f98345e787ef/gitlab-1.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-jlxxe42e\gitlab\setup.py", line 4, in <module>
        long_description = fh.read()
    UnicodeDecodeError: 'gbk' codec can't decode byte 0xa2 in position 202: illegal multibyte sequence

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-jlxxe42e\gitlab\
```
- python version: Python 3.6.5
- pip version: pip 19.0.1
- system info: win10

I get similar issue：https://github.com/JuliaPy/pyjulia/issues/218

Maybe  fix.

**Comment by gpocentek** [comment]
Hi @Iarcky 

The package name is `python-gitlab` if you are really trying to use this project.
