### ISSUE TITLE
error with pip install

### ISSUE THREAD

**Issue by vruge** [python-gitlab/python-gitlab#737]
## Description of the problem, including code/CLI snippet
```bash
 python -m pip install gitlab
Collecting gitlab
  Using cached .../gitlab-1.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\XXXX\AppData\Local\Temp\pip-install-udnnw0gy\gitlab\setup.py", line 4, in <module>
        long_description = fh.read()
      File "XXX\Python3\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 243: character maps to <undefined>

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in XXX\AppData\Local\Temp\pip-install-udnnw0gy\gitlab\

```

## Specifications
  Python-Version: Python 3.7.2
  pip-Version: 19.0.3

**Comment by max-wittig** [comment]
This package is called  `python-gitlab`, so you'll need to install it with

```bash
pip install python-gitlab
```
