### ISSUE TITLE
Creating protected branch produces TypeError

### ISSUE THREAD

**Issue by konrad-fil** [python-gitlab/python-gitlab#755]
## Description of the problem, including code/CLI snippet
Setting
p_branch = project.protectedbranches.create({
    'name': 'test-*',
    'merge_access_level': gitlab.DEVELOPER_ACCESS,
    'push_access_level': gitlab.DEVELOPER_ACCESS
})
Produces TypeError: list indecies must be integers, not str

## Expected Behavior
Creates new protected branch with regex

## Actual Behavior
```
>>> pbb = p.protectedbranches.create({'name':'test-*', 'merge_access_level':gitlab.DEVELOPER_ACCESS, 'push_access_level':gitlab.DEVELOPER_ACCESS})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/gitlab/exceptions.py", line 251, in wrapped_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gitlab/mixins.py", line 226, in create
    return self._obj_cls(self, server_data)
  File "/usr/local/lib/python2.7/dist-packages/gitlab/base.py", line 567, in __init__
    self._create_managers()
  File "/usr/local/lib/python2.7/dist-packages/gitlab/base.py", line 626, in _create_managers
    managers = getattr(self, '_managers', None)
  File "/usr/local/lib/python2.7/dist-packages/gitlab/base.py", line 585, in __getattr__
    value = self.__dict__['_attrs'][name]
TypeError: list indices must be integers, not str
>>> pbb = p.protectedbranches.create({'name':'test-*', 'merge_access_level':0, 'push_access_level':0})
```

## Specifications

  - python-gitlab version: python 2.7/gitlab-python 1.4.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 11.6

**Comment by konrad-fil** [comment]
It was resolved in higher gitlab-python version
