### ISSUE TITLE
access to projects' statistics is broken

### ISSUE THREAD

**Issue by Karreg** [python-gitlab/python-gitlab#756]
## Description of the problem, including code/CLI snippet

With the version 1.6.0 to 1.8.0, with GitLab 11.8-11.9, access to projects statistics is broken.
It was working fine with GitLab 11.7.

Here is an example on direct API access, showing project statistics:

```bash
curl -k https://URL/api/v4/projects/5109\?private_token\=TOKEN\&statistics\=true | jq

{
  "id": 5109,
  "description": "",
  ...
  "statistics": {
    "commit_count": 12,
    "storage_size": 1027604,
    "repository_size": 1027604,
    "lfs_objects_size": 0,
    "job_artifacts_size": 0
  },
}

```

And a sample script, failing.

```python
#!/usr/bin/env python
from gitlab import Gitlab
import argparse
import urllib3
import json
import time
import sys
import os
import datetime

class GitlabProject(object):

    def __init__(self, id, name, url, size):
        self.id = id
        self.name = name
        self.url = url
        self.size = size
    
    def __repr__(self):
        return "{}(ID: {!r}, Name: {!r}, URL: {!r}, Size: {!r})".format(self.__class__.__name__, self.id, self.name, self.url, self.size)


class ProjectAnalyzer:

    args = {}

    def load_args(self):

        parser = argparse.ArgumentParser(description='Test script')
        parser.add_argument('--token', nargs='?',help='GitLab admin access token')
        parser.add_argument('--url', nargs='?', help='GitLab URL')

        self.args = parser.parse_args()

    def load_gitlab_projects(self):
        urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
        gl = Gitlab(self.args.url, private_token=self.args.token, ssl_verify=False)

        projects = gl.projects.list(as_list=False, per_page=500, statistics=True)

        project_referential = {}
        for project in projects:
            gitlab_project = GitlabProject("{}".format(project.id), project.name_with_namespace, project.web_url, project.statistics['storage_size'])
            project_referential[gitlab_project.id] = gitlab_project

        return project_referential

    def main(self):

        self.load_args()
        projects = self.load_gitlab_projects()

if __name__== "__main__":
    analyzer = ProjectAnalyzer()
    analyzer.main()
```

The command to execute, and the result:

```bash
$ ./test.py --url https://URL --token TOKEN
Traceback (most recent call last):
  File "./test.py", line 55, in <module>
    analyzer.main()
  File "./test.py", line 51, in main
    projects = self.load_gitlab_projects()
  File "./test.py", line 43, in load_gitlab_projects
    gitlab_project = GitlabProject("{}".format(project.id), project.name_with_namespace, project.web_url, project.statistics['storage_size'])
  File "/home/gmaitral/.local/lib/python2.7/site-packages/gitlab/base.py", line 81, in __getattr__
    raise AttributeError(name)
AttributeError: statistics
```

## Expected Behavior

The data were correctly fetched with python-gitlab 1.6.0 on GitLab 11.7.X and previous versions

## Actual Behavior

Not working anymore with python-gitlab 1.6+ on GitLab > 11.7

## Specifications

  - python-gitlab version: 1.6.0, 1.8.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 11.9.6, Break detected with upgrade to GitLab 11.8

**Comment by max-wittig** [comment]
GitLab changed it so it doesn't always return statistics. You have to handle the case, where GitLab doesn't return any. We can't fix GitLab with our wrapper.

```python
  project = gl.projects.list(statistics=True)
  if project.get("statistics"):
      print("Do something with it")

**Comment by Karreg** [comment]
Does it mean the statistics are not given when all values are equal to 0 ?

**Comment by Karreg** [comment]
And thanks for the reply, I'll fix the script with this :)

**Comment by max-wittig** [comment]
@Karreg I think so. Can't find the upstream issue now but they changed this behavior in on of the recent versions.

**Comment by jgeorgeson** [comment]
Hoping I'm just missing it, but it looks like there's no option to enable returning statistics with the `project get` CLI command (python-gitlab v1.8.0). Is that correct?

**Comment by jgeorgeson** [comment]
Actually it looks like I can kludge it like this:

```bash
$ gitlab -o json project get --id 'MyGroup/my-project?statistics=true'
```

**Comment by mitar** [comment]
Interesting, to me statistics inside a group are never available: https://gitlab.com/gitlab-org/gitlab/issues/38544

**Comment by max-wittig** [comment]
@mitar You'll need to convert the GroupProject to a real project

```python
groupProject = gl.groups.get(1).projects.list()[0]
project = gl.projects.get(groupProject.id)
```

**Comment by mitar** [comment]
Yes, I have to make one more HTTP request. That is sad. :-(

**Comment by max-wittig** [comment]
@mitar I know, but that's what Gitlab does.
