### ISSUE TITLE
Project-Export returns with 404

### ISSUE THREAD

**Issue by monsdar** [python-gitlab/python-gitlab#786]
## Description of the problem, including code/CLI snippet
Same as in #667: I'm trying to export a project and get a 404 in return. Difference to #667 is that I'm on a new GitLab version though.

Code (excerpt):
```
sourceGitlab = gitlab.Gitlab('http://...', api_version=4, private_token='XYZ')
project = sourceGitlab.projects.get("Group/ProjectName")
export = project.exports.create({})
```

Error:
```
Traceback (most recent call last):
  File "C:\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\gitlab\exceptions.py", line 255, in wrapped_f
    return f(*args, **kwargs)
  File "C:\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\gitlab\mixins.py", line 204, in create
    **kwargs)
  File "C:\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\gitlab\__init__.py", line 629, in http_post
    post_data=post_data, files=files, **kwargs)
  File "C:\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\gitlab\__init__.py", line 531, in http_request
    response_body=result.content)
gitlab.exceptions.GitlabHttpError: 404: 404 Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Workspace\Sandbox\docker-testbed\ci_testbed\populate.py", line 133, in <module>
    main()
  File "E:\Workspace\Sandbox\docker-testbed\ci_testbed\populate.py", line 23, in main
    transferProject(sourceGitlab, targetGitlab, "Group/ProjectName")
  File "E:\Workspace\Sandbox\docker-testbed\ci_testbed\populate.py", line 43, in transferProject
    exportProject(sourceGl, projectSlug, 'export.tgz')
  File "E:\Workspace\Sandbox\docker-testbed\ci_testbed\populate.py", line 51, in exportProject
    export = project.exports.create({})
  File "C:\Users\brinkmann_n\AppData\Local\Programs\Python\Python37\lib\site-packages\gitlab\exceptions.py", line 257, in wrapped_f
    raise error(e.error_message, e.response_code, e.response_body)
gitlab.exceptions.GitlabCreateError: 404: 404 Not Found
```

The project gets found correctly, it contains everything necessary. Seems as if the expected API endpoint does not exist though.

## Expected Behavior
Project gets exported.

## Actual Behavior
404 Error, API endpoint seems not to work.

## Specifications

  - python-gitlab version: 1.8.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 11.10.4 (62c464651d2)

**Comment by max-wittig** [comment]
Do you have the correct permissions in the project? Please try with a new project in your instance.

**Comment by monsdar** [comment]
I found that exporting projects was disabled under `Admin -> Settings -> Visibility and access controls -> Project export enabled`

Closing here, sorry for the inconvenience.
