### ISSUE TITLE
TypeError: 'Response' object is not subscriptable

### ISSUE THREAD

**Issue by atodorov** [python-gitlab/python-gitlab#863]
## Description of the problem, including code/CLI snippet

Error while trying to use the client library

```
>>> rpc = gitlab.Gitlab(gl.base_url, private_token=gl.api_password)
>>> repo_id = '/'.join(gl.base_url.strip().strip('/').split('/')[-2:])
>>> repo_id
'atodorov/test-me'
>>> r = rpc.projects.get(repo_id)
Traceback (most recent call last):
  File "/home/senko/.virtualenvs/kiwi_django2/lib/python3.6/site-packages/gitlab/base.py", line 59, in __getattr__
    return self.__dict__["_updated_attrs"][name]
KeyError: 'id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/senko/.virtualenvs/kiwi_django2/lib/python3.6/site-packages/gitlab/exceptions.py", line 259, in wrapped_f
    return f(*args, **kwargs)
  File "/home/senko/.virtualenvs/kiwi_django2/lib/python3.6/site-packages/gitlab/mixins.py", line 51, in get
    return self._obj_cls(self, server_data)
  File "/home/senko/.virtualenvs/kiwi_django2/lib/python3.6/site-packages/gitlab/base.py", line 44, in __init__
    self._create_managers()
  File "/home/senko/.virtualenvs/kiwi_django2/lib/python3.6/site-packages/gitlab/base.py", line 126, in _create_managers
    manager = cls(self.manager.gitlab, parent=self)
  File "/home/senko/.virtualenvs/kiwi_django2/lib/python3.6/site-packages/gitlab/base.py", line 249, in __init__
    self._computed_path = self._compute_path()
  File "/home/senko/.virtualenvs/kiwi_django2/lib/python3.6/site-packages/gitlab/base.py", line 264, in _compute_path
    for self_attr, parent_attr in self._from_parent_attrs.items()
  File "/home/senko/.virtualenvs/kiwi_django2/lib/python3.6/site-packages/gitlab/base.py", line 264, in <dictcomp>
    for self_attr, parent_attr in self._from_parent_attrs.items()
  File "/home/senko/.virtualenvs/kiwi_django2/lib/python3.6/site-packages/gitlab/base.py", line 62, in __getattr__
    value = self.__dict__["_attrs"][name]
TypeError: 'Response' object is not subscriptable
```

## Specifications

  - python-gitlab version:
gitlab==1.0.2
python-gitlab==1.10.0

  - API version you are using (v3/v4):
  - Gitlab server version (or gitlab.com): gitlab.com

**Comment by bbeale** [comment]
Did you close this issue because you resolved it? I have the same stack trace. Would be curious to know how you fixed it.

**Comment by atodorov** [comment]
I had wrong base url being passed to the Gitlab object. Instead of gitlab.com it was the repo url.

**Comment by bbeale** [comment]
Hey thanks for such a quick response! I just checked and I am passing the repo URL. Looks like I have a little more digging to do this afternoon.
