### ISSUE TITLE
GitLab Status API - status can't be saved for other users

### ISSUE THREAD

**Issue by oerdnj** [python-gitlab/python-gitlab#902]
## Description of the problem, including code/CLI snippet

The status can't be saved, looks like the `save()` method is missing:
```
user = gl.users.list(username='megrea01')[0]
status = user.status.get()
status.message = None
status.emoji = None
status.save()
```

## Expected Behavior

Status saved...

## Actual Behavior

```
>>> status.save()
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gitlab/base.py", line 59, in __getattr__
    return self.__dict__["_updated_attrs"][name]
KeyError: 'save'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gitlab/base.py", line 62, in __getattr__
    value = self.__dict__["_attrs"][name]
KeyError: 'save'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gitlab/base.py", line 82, in __getattr__
    return self.__dict__["_parent_attrs"][name]
KeyError: 'save'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/gitlab/base.py", line 84, in __getattr__
    raise AttributeError(name)
AttributeError: save
```

 See the difference between:
```
>>> user = gl.users.list(username='megrea01')[0]
>>> status = user.status.get()
>>> me = gl.user
>>> mystatus = me.status.get()
>>> dir(status)
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_attrs', '_create_managers', '_id_attr', '_module', '_parent_attrs', '_update_attrs', '_updated_attrs', 'attributes', 'get_id', 'manager']
>>> dir(mystatus)
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_attrs', '_create_managers', '_get_updated_data', '_id_attr', '_module', '_parent_attrs', '_short_print_attr', '_update_attrs', '_updated_attrs', 'attributes', 'get_id', 'manager', 'save']
```

## Specifications

  - python-gitlab version: 1.12.1
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 12.3.2

**Comment by max-wittig** [comment]
The Gitlab API doesn't allow this it seems.   https://docs.gitlab.com/ee/api/users.html#set-user-status

**Comment by max-wittig** [comment]
You can only modify your own status.
