### ISSUE TITLE
deploy key fails to be added when spaces in key comments

### ISSUE THREAD

**Issue by Shaps** [python-gitlab/python-gitlab#930]
## Description of the problem, including code/CLI snippet
( Apologies for the long issue, trying to give as much info as I can )
Hi, 
I maintain the ansible's gitlab modules that make use of this library. 
I got a bug report today where the user was unable to add the same deploy key to 2 separate projects. After some time of digging around, looks like the issue arises when the deploy key has spaces in the comment section. Below a simple repro code, with both output and the pubkeys I used. 
```python
import gitlab

gl = gitlab.Gitlab('https://gitlab.com', private_token='<TOKEN>')
gl.auth()

project = gl.projects.get(<PROJECT_ID>)
pkey = project.keys.list()
project2 = gl.projects.get(<PROJECT_ID>)
pkey2 = project2.keys.list()

working_key = project.keys.create({'title': 'test_key',
                                   'key': open('/tmp/id_ssh_rsa.pub').read()})
print(working_key)
working_key2 = project2.keys.create({'title': 'test_key',
                                     'key': open('/tmp/id_ssh_rsa.pub').read()})
print(working_key2)

broken_key = project.keys.create({'title': 'test_key2',
                                  'key': open('/tmp/id_ssh_rsa_broken.pub').read()})
print(broken_key)
broken_key2 = project2.keys.create({'title': 'test_key2',
                                    'key': open('/tmp/id_ssh_rsa_broken.pub').read()})
print(broken_key2)
```
**deploy_keys**
```shell
#Working key (/tmp/id_ssh_rsa.pub)
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDafi5NM5uX3Xt1jTvJpU7Xt3M6FfkSeyL83UUD3WTVgY33uwmFBeGgoAQWXELRgkh4ZsXjH7PdwnajiGi15epyFizax4iYajKcNxaE+7jtq0aJDQCtDnr94kK8gmEDNWt74Ny2YthOjITa2dx7fXKbHeNFFzxC7eBM4KbbgLuMuugp+XO9V5KBu7efy7dFyxn/FmGRw29mpfvAVu0eHwTRJ4mMY8CqhqFC+91tANzFOH0Fs6+2JjuAYAjb5yFSOJgAQLidHYu8Fs5//8YkoZtFm8hsWsq+7GPfUzpm0mPonS10p60PeAicI0dz9WQwQOTQmJlG3jtiZkA/DkodtvxEKoDxtMxBPZr9orshuCyLxmz/DE6hAypvMjG4+J+0pVykv6qudBq7drD4sfql1VSxrYtyGmh4+UhiuHAFmS+LmogdyLHbmIpksrD6+OAhefYvuKo0ec5OImaIPMVcTMCc0bCXVL+/CH/AB+w7kUy1aQ5g6UZ4gSiav33MN1Ywv1mKq6zv89TK5lR3x4E8Ot18HeOiqqaJRA6bCtpT/E4UsuEp3GPA7m6VvFYKLSxO6XOIE0JqqBl3B6haL2fUHh6CyCuXip1/pQJ6uRWQDtLnWCXDp/GLdiHZqUjf1nj6M1bhcQ+vvFJLySzdAyaniGQvMhUtOx4NgCmMHIka39FyIw== blah_with_no_spaces

#Not working key (/tmp/id_ssh_rsa_broken.pub)
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDCRBScyWBAYiP8SQcK4105cScYhRZrD5gYG2F9UQkN6UToJd3V+RB9Z05w8JkyWHXgCaIgzHFCNE8OcoOPpga4ZEzoAgVmg3SkK3nuwpvIkl+SzULUrX5v+mNu1NFNIyOLUjmDrqzsClzgi3mn4D4+O63Aw/XYxweeL/nc0XmC0o3YncpCgzJ4yatNx9M7268v7SgExGspV4wz3aNNthRpLy7Ve4lrodhkhxD+CFpC7KV8KHZoOCs89UFcf/R2OenlvO9snWjbEm7s74iP/XkQORTc8/xoBbEyxQiVrcQ5uKaR13WL9OKhdVN3tDzpIbjCkF/ie3/uJGPV5ySPy+BA6dzB57t5EbWp/6S9Kk93vAhdGw5N3mD99nwg09mr22jte83Z7tKL0v0bDxgVzsZoe9RsI6bqto4VqcLiE+QLLi/A32c2Y0te6I0+xTOEaDBfyeyfUBabr2yaEuz3fQ0LHQP3KSFQ/RhBUvlCX6ycf5Jbjtncpw8MuHnPDP2gB94aICXeylYe7KsGB2gLehUFBolYnV8ErrkXq9+ueVNBfb5ZXdTvvkyLhB7X/BFeRIYWTMBHuyj0gkbCsN/6BpMG/UfLL/ZswxIINJM0nu2tCr4dBJuP7PAj+usta53OjV1F59mSAs6W6NxmG/0Au5opUXx5fT3XKmhoeRrKiDLX7w== blah and something
```
**output**
```shell
<class 'gitlab.v4.objects.ProjectKey'> => {'id': 4325355, 'title': 'test_key', 'key': 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDafi5NM5uX3Xt1jTvJpU7Xt3M6FfkSeyL83UUD3WTVgY33uwmFBeGgoAQWXELRgkh4ZsXjH7PdwnajiGi15epyFizax4iYajKcNxaE+7jtq0aJDQCtDnr94kK8gmEDNWt74Ny2YthOjITa2dx7fXKbHeNFFzxC7eBM4KbbgLuMuugp+XO9V5KBu7efy7dFyxn/FmGRw29mpfvAVu0eHwTRJ4mMY8CqhqFC+91tANzFOH0Fs6
+2JjuAYAjb5yFSOJgAQLidHYu8Fs5//8YkoZtFm8hsWsq+7GPfUzpm0mPonS10p60PeAicI0dz9WQwQOTQmJlG3jtiZkA/DkodtvxEKoDxtMxBPZr9orshuCyLxmz/DE6hAypvMjG4+J+0pVykv6qudBq7drD4sfql1VSxrYtyGmh4+UhiuHAFmS+LmogdyLHbmIpksrD6+OAhefYvuKo0ec5OImaIPMVcTMCc0bCXVL+/CH/AB+w7kUy1aQ5g6UZ4gSiav33MN1Ywv1mKq6zv89TK5lR3x4E8Ot18HeOiqqaJRA6bCtpT/E4UsuEp3GPA7m6VvFYKLSxO6XOIE0JqqBl3B6haL2fUHh6CyCuXip1
/pQJ6uRWQDtLnWCXDp/GLdiHZqUjf1nj6M1bhcQ+vvFJLySzdAyaniGQvMhUtOx4NgCmMHIka39FyIw== blah_with_no_spaces', 'created_at': '2019-10-31T15:03:38.455Z', 'can_push': False}
<class 'gitlab.v4.objects.ProjectKey'> => {'id': 4325355, 'title': 'test_key', 'key': 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDafi5NM5uX3Xt1jTvJpU7Xt3M6FfkSeyL83UUD3WTVgY33uwmFBeGgoAQWXELRgkh4ZsXjH7PdwnajiGi15epyFizax4iYajKcNxaE+7jtq0aJDQCtDnr94kK8gmEDNWt74Ny2YthOjITa2dx7fXKbHeNFFzxC7eBM4KbbgLuMuugp+XO9V5KBu7efy7dFyxn/FmGRw29mpfvAVu0eHwTRJ4mMY8CqhqFC+91tANzFOH0Fs6
+2JjuAYAjb5yFSOJgAQLidHYu8Fs5//8YkoZtFm8hsWsq+7GPfUzpm0mPonS10p60PeAicI0dz9WQwQOTQmJlG3jtiZkA/DkodtvxEKoDxtMxBPZr9orshuCyLxmz/DE6hAypvMjG4+J+0pVykv6qudBq7drD4sfql1VSxrYtyGmh4+UhiuHAFmS+LmogdyLHbmIpksrD6+OAhefYvuKo0ec5OImaIPMVcTMCc0bCXVL+/CH/AB+w7kUy1aQ5g6UZ4gSiav33MN1Ywv1mKq6zv89TK5lR3x4E8Ot18HeOiqqaJRA6bCtpT/E4UsuEp3GPA7m6VvFYKLSxO6XOIE0JqqBl3B6haL2fUHh6CyCuXip1
/pQJ6uRWQDtLnWCXDp/GLdiHZqUjf1nj6M1bhcQ+vvFJLySzdAyaniGQvMhUtOx4NgCmMHIka39FyIw== blah_with_no_spaces', 'created_at': '2019-10-31T15:03:38.455Z', 'can_push': False}
<class 'gitlab.v4.objects.ProjectKey'> => {'id': 4325356, 'title': 'test_key2', 'key': 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDCRBScyWBAYiP8SQcK4105cScYhRZrD5gYG2F9UQkN6UToJd3V+RB9Z05w8JkyWHXgCaIgzHFCNE8OcoOPpga4ZEzoAgVmg3SkK3nuwpvIkl+SzULUrX5v+mNu1NFNIyOLUjmDrqzsClzgi3mn4D4+O63Aw/XYxweeL/nc0XmC0o3YncpCgzJ4yatNx9M7268v7SgExGspV4wz3aNNthRpLy7Ve4lrodhkhxD+CFpC7KV8K
HZoOCs89UFcf/R2OenlvO9snWjbEm7s74iP/XkQORTc8/xoBbEyxQiVrcQ5uKaR13WL9OKhdVN3tDzpIbjCkF/ie3/uJGPV5ySPy+BA6dzB57t5EbWp/6S9Kk93vAhdGw5N3mD99nwg09mr22jte83Z7tKL0v0bDxgVzsZoe9RsI6bqto4VqcLiE+QLLi/A32c2Y0te6I0+xTOEaDBfyeyfUBabr2yaEuz3fQ0LHQP3KSFQ/RhBUvlCX6ycf5Jbjtncpw8MuHnPDP2gB94aICXeylYe7KsGB2gLehUFBolYnV8ErrkXq9+ueVNBfb5ZXdTvvkyLhB7X/BFeRIYWTMBHuyj0gkbCsN/6BpMG/UfLL/
ZswxIINJM0nu2tCr4dBJuP7PAj+usta53OjV1F59mSAs6W6NxmG/0Au5opUXx5fT3XKmhoeRrKiDLX7w== blah', 'created_at': '2019-10-31T15:03:40.337Z', 'can_push': False}
Traceback (most recent call last):
  File "/home/shaps/.virtualenvs/ansible/lib/python3.7/site-packages/gitlab/exceptions.py", line 259, in wrapped_f
    return f(*args, **kwargs)
  File "/home/shaps/.virtualenvs/ansible/lib/python3.7/site-packages/gitlab/mixins.py", line 204, in create
    server_data = self.gitlab.http_post(path, post_data=data, files=files, **kwargs)
  File "/home/shaps/.virtualenvs/ansible/lib/python3.7/site-packages/gitlab/__init__.py", line 691, in http_post
    **kwargs
  File "/home/shaps/.virtualenvs/ansible/lib/python3.7/site-packages/gitlab/__init__.py", line 581, in http_request
    response_body=result.content,
gitlab.exceptions.GitlabHttpError: 400: {'deploy_key.fingerprint': ['has already been taken']}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_gitlab.py", line 22, in <module>
    'key': open('/tmp/id_ssh_rsa_broken.pub').read()})
  File "/home/shaps/.virtualenvs/ansible/lib/python3.7/site-packages/gitlab/exceptions.py", line 261, in wrapped_f
    raise error(e.error_message, e.response_code, e.response_body)
gitlab.exceptions.GitlabCreateError: 400: {'deploy_key.fingerprint': ['has already been taken']}
```

By looking at the output, looks like the comment is being truncated after the space, now I'm not sure if this happens in the API itself or here.

## Expected Behavior
Key with comments to be added correctly

## Actual Behavior
Key with comments creates error when added to additional projects

## Specifications

  - python-gitlab version: 1.12.1
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): Both gitlab.com and 12.4.1

**Comment by max-wittig** [comment]
> I got a bug report today where the user was unable to add the same deploy key to 2 separate projects

I think this has nothing todo with spaces. GitLab just doesn't allow the same deploy key in multiple projects

That's why you get this error message back from GitLab.:

```
gitlab.exceptions.GitlabCreateError: 400: {'deploy_key.fingerprint': ['has already been taken']}
```

The same would happen, if you would use something like `curl` to send this request. Python-gitlab can't help you here. Deploy keys need to be unique in GitLab.

**Comment by Shaps** [comment]
@max-wittig sorry but I'm not understanding this reply. In the code above, the first 2 `.key.create(` work fine, the key is the same in that case too, the only difference between the first two create and the second two is the space in the key comments.
While I appreciate your reply. I disagree with the fact deploy keys need to be unique per-project. You can have the same deploy key applied to multiple projects ( I have done this previously, also, the repro code above shows you that ). 
Deploy keys need to be unique within Gitlab, and that's correct, the issue comes up here, because the key is truncated after the first comment space. 
That said, this seems to be an issue with the underlying API and not python-gitlab itself. I wasn't entirely sure about it at the time of opening the issue and was hoping somebody from gitlab would chime in and direct me to the right location.

**Comment by max-wittig** [comment]
Gitlab doesn't maintain this library and is in no way associated with it.
