### ISSUE TITLE
Creation of project snippet raises GitlabCreateError due to visibility prameter

### ISSUE THREAD

**Issue by matusf** [python-gitlab/python-gitlab#956]
I tried to create a project snippet, however, `python-gitlab` is enforcing `visibility` parameter ~([which is not required](https://docs.gitlab.com/ee/api/snippets.html#create-new-snippet)).~ 
EDIT:
I just found out, project snippets do [require visibility parameter](https://docs.gitlab.com/ee/api/project_snippets.html#create-new-snippet). 

```python
>>> p = gl.projects.get('<project-id>')
>>> # visibility parameter is not required
>>> p.snippets.get_create_attrs()
(('title', 'file_name', 'code'), ('lifetime', 'visibility'))
>>> p.snippets.create({'title': 'snip title', 'file_name': 'snip filename', 'code': 'snip code'})
Traceback (most recent call last):
  File "/home/matus/.virtualenvs/psa/lib/python3.6/site-packages/gitlab/exceptions.py", line 259, in wrapped_f
    return f(*args, **kwargs)
  File "/home/matus/.virtualenvs/psa/lib/python3.6/site-packages/gitlab/mixins.py", line 204, in create
    server_data = self.gitlab.http_post(path, post_data=data, files=files, **kwargs)
  File "/home/matus/.virtualenvs/psa/lib/python3.6/site-packages/gitlab/__init__.py", line 674, in http_post
    **kwargs
  File "/home/matus/.virtualenvs/psa/lib/python3.6/site-packages/gitlab/__init__.py", line 564, in http_request
    response_body=result.content,
gitlab.exceptions.GitlabHttpError: 400: visibility is missing, visibility does not have a valid value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/matus/.virtualenvs/psa/lib/python3.6/site-packages/gitlab/exceptions.py", line 261, in wrapped_f
    raise error(e.error_message, e.response_code, e.response_body)
gitlab.exceptions.GitlabCreateError: 400: visibility is missing, visibility does not have a valid value
```

It fails with visibility parameter as well:
```python
>>> p.snippets.create({'title': 'snip title', 'file_name': 'snip filename', 'code': 'snip code', 'visibility': gitlab.VISIBILITY_PUBLIC})
Traceback (most recent call last):
  File "/home/matus/.virtualenvs/psa/lib/python3.6/site-packages/gitlab/exceptions.py", line 259, in wrapped_f
    return f(*args, **kwargs)
  File "/home/matus/.virtualenvs/psa/lib/python3.6/site-packages/gitlab/mixins.py", line 204, in create
    server_data = self.gitlab.http_post(path, post_data=data, files=files, **kwargs)
  File "/home/matus/.virtualenvs/psa/lib/python3.6/site-packages/gitlab/__init__.py", line 674, in http_post
    **kwargs
  File "/home/matus/.virtualenvs/psa/lib/python3.6/site-packages/gitlab/__init__.py", line 564, in http_request
    response_body=result.content,
gitlab.exceptions.GitlabHttpError: 400: visibility does not have a valid value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/matus/.virtualenvs/psa/lib/python3.6/site-packages/gitlab/exceptions.py", line 261, in wrapped_f
    raise error(e.error_message, e.response_code, e.response_body)
gitlab.exceptions.GitlabCreateError: 400: visibility does not have a valid value
```

## Specifications
  - python-gitlab version: 1.13.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 12.4.3-ee

**Comment by max-wittig** [comment]
Error code 400 is always directly send by your GitLab instance. I guess you cannot create a public snippet in an internal/private project.

**Comment by matusf** [comment]
I've edited the issue (see EDIT ^). The visibility is not required in personal snippets but required in project snippets. 

The exception was caused by wrong format of visibility parameter. `python-gitlab` has [numeric representation of visibility constants](https://github.com/python-gitlab/python-gitlab/blob/master/gitlab/const.py#L25-L27) while gitlab needs one of `{"private", "public", "internal"}` as described [here](https://docs.gitlab.com/ee/api/project_snippets.html#snippet-visibility-level). So all one needs to do is pass those arguments:

```python
p.snippets.create(
    {
        'title': 'snip title', 
        'file_name': 'snip filename', 
        'code': 'snip code', 
        'visibility': 'public'
    }
)
```

`python-gitlab` has actually the correct representation of visibility constants [here](https://github.com/python-gitlab/python-gitlab/blob/master/gitlab/v4/objects.py#L29-L31), however, they are not imported in `__init__.py`

---
The `get_create_args` should be probably modified as well. As there is no `lifetime` parameter in [gitlab api docs](https://docs.gitlab.com/ee/api/project_snippets.html#create-new-snippet) and the `description` parameter is missing from `get_create_args`.
