### ISSUE TITLE
Automatically retry transient API issues

### ISSUE THREAD

**Issue by mitar** [python-gitlab/python-gitlab#970]
So I see exceptions like that:

```
DEBUG:urllib3.connectionpool:https://gitlab.com:443 "GET /api/v4/...?...&page=111&per_page=100&... HTTP/1.1" 502 24
Traceback (most recent call last):
  File ".../gitlab/__init__.py", line 832, in next
    item = self._data[self._current]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  ...
  File ".../gitlab/base.py", line 184, in __next__
    return self.next()
  File ".../gitlab/base.py", line 187, in next
    data = self._list.next()
  File ".../gitlab/__init__.py", line 837, in next
    self._query(self._next_url)
  File ".../gitlab/__init__.py", line 766, in _query
    result = self._gl.http_request("get", url, query_data=query_data, **kwargs)
  File ".../gitlab/__init__.py", line 562, in http_request
    response_body=result.content,
gitlab.exceptions.GitlabHttpError: 502: GitLab is not responding
```

Those should just be retried, no?

**Comment by max-wittig** [comment]
I don't think so. You need to handle failures yourself. Maybe you want to check the health of your instance with python-gitlab.

```python
try:
    gl.projects.list()
except:
    # do retry
```

**Comment by mitar** [comment]
But if I in the middle of pagination, then this is something python-gitlab should do? I cannot just resume the generator?

**Comment by max-wittig** [comment]
I guess that is true. But then it should be optional maybe. Otherwise we change the behavior of existing scripts. Right?

**Comment by mitar** [comment]
Sure. A flag like `retry_transient_exceptions=5`. To retry up to 5 times.

**Comment by mitar** [comment]
I think all 500 errors should be retried, and 429 error.

**Comment by max-wittig** [comment]
If we get 429 we already wait until we can request new items again.
