### ISSUE TITLE
Project export fails with "AttributeError: exports" 

### ISSUE THREAD

**Issue by shaun-edwards** [python-gitlab/python-gitlab#977]
## Description of the problem, including code/CLI snippet
The project export as described in the documentation [here](https://python-gitlab.readthedocs.io/en/stable/gl_objects/projects.html) does not work.  The following code results in a `AttributeError: exports` at the line: `export = p.exports.create({})`

```
#!/usr/bin/env python3

import gitlab
import logging

logging.basicConfig(format='%(message)s', level=logging.INFO)

gl = gitlab.Gitlab('http://www.gitlab.com')
# Create the export
p = gl.projects.get('72724') #https://gitlab.com/gitlab-org/gitlab-test
logging.info("Getting project")
export = p.exports.create({})

# Wait for the 'finished' status
export.refresh()
while export.export_status != 'finished':
    time.sleep(1)
    export.refresh()

# Download the result
with open('/tmp/export.tgz', 'wb') as f:
    export.download(streamed=True, action=f.write)
```

## Expected Behavior
Based on the documentation, this code should initiated a project export and then download the resulting tar file

## Actual Behavior
The executing script fails at `export = p.exports.create({})`  with the following output:

```
shaun@8BYWYW2-Precision-5530:~/repos/devops/gitlab/scripts$ cd /home/shaun/repos/devops/gitlab/scripts ; env ELECTRON_RUN_AS_NODE=1 CLUTTER_IM_MODULE=xim XDG_MENU_PREFIX=gnome- SNAP_USER_DATA=/home/shaun/snap/code/22 LANG=en_US.UTF-8 DISPLAY=:0 GNOME_SHELL_SESSION_MODE=ubuntu SNAP_REVISION=22 DISABLE_WAYLAND=1 SNAP_ARCH=amd64 SNAP_INSTANCE_KEY= USERNAME=shaun XDG_VTNR=2 GIO_LAUNCHED_DESKTOP_FILE_PID=6456 SSH_AUTH_SOCK=/run/user/1000/keyring/ssh XDG_SESSION_ID=5 SNAP_USER_COMMON=/home/shaun/snap/code/common USER=shaun DESKTOP_SESSION=ubuntu QT4_IM_MODULE=xim TEXTDOMAINDIR=/usr/share/locale/ PWD=/home/shaun HOME=/home/shaun TEXTDOMAIN=im-config SNAP=/snap/code/22 SSH_AGENT_PID=2141 QT_ACCESSIBILITY=1 SNAP_COMMON=/var/snap/code/common XDG_SESSION_TYPE=x11 SNAP_NAME=code XDG_DATA_DIRS=/usr/share/ubuntu:/usr/local/share:/usr/share:/var/lib/snapd/desktop SNAP_INSTANCE_NAME=code SNAP_DATA=/var/snap/code/22 GSETTINGS_SCHEMA_DIR=/snap/code/22/usr/share/glib-2.0/schemas XDG_SESSION_DESKTOP=ubuntu GJS_DEBUG_OUTPUT=stderr GDK_PIXBUF_MODULE_FILE=/home/shaun/snap/code/common/.cache/gdk-pixbuf-loaders.cache GTK_MODULES=gail:atk-bridge SNAP_COOKIE=y7Yn3JrhkGdKVCxcKCrwRy3BPW8M2J2mQQGkc6ljj1yx WINDOWPATH=2 SHELL=/bin/bash QT_IM_MODULE=ibus XMODIFIERS=@im=ibus IM_CONFIG_PHASE=2 XDG_CURRENT_DESKTOP=Unity GPG_AGENT_INFO=/run/user/1000/gnupg/S.gpg-agent:0:1 BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/code_code.desktop SNAP_REEXEC= GIO_LAUNCHED_DESKTOP_FILE=/var/lib/snapd/desktop/applications/code_code.desktop XDG_SEAT=seat0 SHLVL=2 GDK_PIXBUF_MODULEDIR=/snap/code/22/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders GDMSESSION=ubuntu GNOME_DESKTOP_SESSION_ID=this-is-deprecated XDG_CACHE_HOME=/home/shaun/snap/code/common/.cache LOGNAME=shaun DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus XDG_RUNTIME_DIR=/run/user/1000/snap.code XAUTHORITY=/run/user/1000/gdm/Xauthority SNAP_CONTEXT=y7Yn3JrhkGdKVCxcKCrwRy3BPW8M2J2mQQGkc6ljj1yx XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/etc/xdg SNAP_VERSION=9579eda0 'GJS_DEBUG_TOPICS=JS ERROR;JS LOG' SNAP_LIBRARY_PATH=/var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl32:/var/lib/snapd/void DESKTOP_MODE=1 SESSION_MANAGER=local/8BYWYW2-Precision-5530:@/tmp/.ICE-unix/2046,unix/8BYWYW2-Precision-5530:/tmp/.ICE-unix/2046 GTK_IM_MODULE=ibus _=/snap/code/22/usr/share/code/code APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL=true VSCODE_CLI=1 ELECTRON_NO_ATTACH_CONSOLE=1 VSCODE_FORCE_USER_ENV=1 NO_AT_BRIDGE=1 CHROME_DESKTOP=code-url-handler.desktop 'VSCODE_NLS_CONFIG={"locale":"en-us","availableLanguages":{},"_languagePackSupport":true}' VSCODE_NODE_CACHED_DATA_DIR=/home/shaun/.config/Code/CachedData/9579eda04fdb3a9bba2750f15193e5fafe16b959 VSCODE_LOGS=/home/shaun/.config/Code/logs/20191217T185902 VSCODE_IPC_HOOK=/run/user/1000/snap.code/vscode-385fd8d5-1.41.0-main.sock VSCODE_PID=6507 'LESSCLOSE=/usr/bin/lesspipe %s %s' 'LESSOPEN=| /usr/bin/lesspipe %s' LS_COLORS= AMD_ENTRYPOINT=vs/workbench/services/extensions/node/extensionHostProcess PIPE_LOGGING=true VERBOSE_LOGGING=true VSCODE_IPC_HOOK_EXTHOST=/tmp/vscode-ipc-f182808d-3d72-4382-9367-1ead9f42b97f.sock VSCODE_HANDLES_UNCAUGHT_ERRORS=true VSCODE_LOG_STACK=false PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin PYTHONIOENCODING=UTF-8 PYTHONUNBUFFERED=1 /usr/bin/python3 /home/shaun/.vscode/extensions/ms-python.python-2019.10.41019/pythonFiles/ptvsd_launcher.py --default --nodebug --client --host localhost --port 40495 /home/shaun/repos/devops/gitlab/scripts/backup_test.py 
Getting project
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gitlab/base.py", line 582, in __getattr__
    return self.__dict__['_updated_attrs'][name]
KeyError: 'exports'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gitlab/base.py", line 585, in __getattr__
    value = self.__dict__['_attrs'][name]
KeyError: 'exports'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gitlab/base.py", line 605, in __getattr__
    return self.__dict__['_parent_attrs'][name]
KeyError: 'exports'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shaun/.vscode/extensions/ms-python.python-2019.10.41019/pythonFiles/ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "/home/shaun/.vscode/extensions/ms-python.python-2019.10.41019/pythonFiles/lib/python/old_ptvsd/ptvsd/__main__.py", line 432, in main
    run()
  File "/home/shaun/.vscode/extensions/ms-python.python-2019.10.41019/pythonFiles/lib/python/old_ptvsd/ptvsd/__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "/usr/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/usr/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/shaun/repos/devops/gitlab/scripts/backup_test.py", line 12, in <module>
    export = p.exports.create({})
  File "/usr/lib/python3/dist-packages/gitlab/base.py", line 607, in __getattr__
    raise AttributeError(name)
AttributeError: exports
shaun@8BYWYW2-Precision-5530:~/repos/devops/gitlab/scripts$ 
```

## Specifications

  - python-gitlab version: `python-gitlab-1.15.0`
  - API version you are using (v3/v4): `v4`
  - Gitlab server version (or gitlab.com): `gitlab.com`

**Comment by max-wittig** [comment]
Not sure what's going on. Just tried it with a couple of my projects and everything works just fine.

![image](https://user-images.githubusercontent.com/6639323/71070942-00204e80-217c-11ea-866e-9c07776f508c.png)

**Comment by max-wittig** [comment]
I think you can't export a project without being authenticated.

You should provide a token for 

```python
gl = gitlab.Gitlab('http://www.gitlab.com')
```

**Comment by max-wittig** [comment]
Feel free to re-open, if there was some other cause.

**Comment by shaun-edwards** [comment]
@max-wittig, I was able to get my code to work using `python2.7`, but not with `python3.6`.  Under `python3.6`, the `project` class does not have an `exports` member.  I can use `python2.7` for my usage, but others may not.  

I'll leave it up to you to reopen.  I'm happy to help continue debugging, but I don't know much about debugging different versions of python.

**Comment by max-wittig** [comment]
I've tested with 3.8. Python2 support will be dropped on 2020-01-01. 

Could you send the full code you've used for testing with 3.6?

**Comment by Johny-faillab** [comment]
Hi there.

Just come a cross the same issue. Was this issue solved somehow? What causing the 'AttributeError: exports' error?

**Code:**

```
#!/usr/bin/python3
import gitlab

gl = gitlab.Gitlab('https://gitlab.com', private_token='token')
groups = gl.projects.list()
group = gl.groups.get(group_id)
projects = group.projects.list(include_subgroups=True)
for each in projects:
    print("Exporting...")
    print(each.attributes['name'])
    # Create the export
    export = each.exports.create({})
    # Wait for the 'finished' status
    export.refresh()
    while export.export_status != 'finished':
        time.sleep(1)
        export.refresh()
    # Download the result
    with open('/tmp/export.tgz', 'wb') as f:
        export.download(streamed=True, action=f.write)
```

**Error:**

`Exporting...
<'project_name'>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gitlab/base.py", line 59, in __getattr__
    return self.__dict__["_updated_attrs"][name]
KeyError: 'exports'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gitlab/base.py", line 62, in __getattr__
    value = self.__dict__["_attrs"][name]
KeyError: 'exports'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gitlab/base.py", line 82, in __getattr__
    return self.__dict__["_parent_attrs"][name]
KeyError: 'exports'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/john/datamole_projects/gitlab-backup/main.py", line 12, in <module>
    export = each.exports.create({})
  File "/usr/local/lib/python3.8/dist-packages/gitlab/base.py", line 84, in __getattr__
    raise AttributeError(name)
AttributeError: exports`

**Specifications:**
python-gitlab version: python-gitlab-2.5.0
API version you are using (v3/v4): v4
Gitlab server version (or gitlab.com): gitlab.com
Python version: 3.8.5
System: Ubuntu 20.04

**Comment by philippludwig** [comment]
Had the same problem. This happens when you generated your project object e.g. via the groups call; you have to re-initiate the project with the call `gl.projects.get(<id>)`.
